### ISSUE TITLE
Docker Hub tag `latest` isnt. 

### ISSUE THREAD

**Issue by rmoff** [lycheeverse/lychee#1031]
The version of lychee on Docker Hub [under tag `latest`](https://hub.docker.com/layers/lycheeverse/lychee/latest/images/sha256-f7e3f111ee0732acbeade75974875ae56ee3b205cf3410b15118aa790f0a9cc9?context=explore) isn't the latest one. It's hash matches that of the image tagged [0.10.3](https://hub.docker.com/layers/lycheeverse/lychee/0.10.3/images/sha256-f7e3f111ee0732acbeade75974875ae56ee3b205cf3410b15118aa790f0a9cc9?context=explore)

For reference, version 0.11.1 is available on `master`: 

```
docker run --rm \
           --name lychee \
           --tty \
           lycheeverse/lychee:master -V

lychee 0.11.1
```

Could/should the Docker Hub tag be updated for `latest` to point to the latest release please?

**Comment by mre** [comment]
Thanks, @rmoff.
This is fixed now as of https://github.com/lycheeverse/lychee/commit/6c24a22df6e13af2f21da65db1b6657a19166564.
