### ISSUE TITLE
Publish to microsoft store in msix format

### ISSUE THREAD

**Issue by soredake** [lycheeverse/lychee#1041]
Example benefits of msix format:
https://github.com/felixrieseberg/windows95/issues/221 https://learn.microsoft.com/en-us/windows/msix/overview#key-features

lychee can be installed in windows right through winget, but has problems https://github.com/microsoft/winget-cli/issues/2802

Publishing lychee to microsoft store will make installation/updating lychee very easy.

**Comment by mre** [comment]
Interesting idea. Are there other command line applications, which support the MSIX format and are published on the Microsoft store?

**Comment by soredake** [comment]
This two i use for example: https://apps.microsoft.com/store/detail/XP8K0HKJFRXGCK https://apps.microsoft.com/store/detail/python-311/9NRWMJP3717K

**Comment by mre** [comment]
Nice. Yes, I'd welcome support for MSIX. Is that something you'd like to look into?

**Comment by lebensterben** [comment]
there's MSIX Packaging Tool that can convert .exe to .msix format. It has a command line interface so it's usable in CI, but it requires Windows 10.

**Comment by mre** [comment]
Closing this in order to keep the scope of the project manageable. If someone finds this and has the time to work on it, please feel free to add a comment and/or create a pull request. Appreciate the idea.
