### ISSUE TITLE
URL misinterpreted as email

### ISSUE THREAD

**Issue by thomas-zahner** [lycheeverse/lychee#1111]
When checking https://wikipedia.org for broken links with: `lychee https://wikipedia.org`
The result looks as follows:

```
Issues found in 1 input. Find details below.

[https://wikipedia.org/]:
✗ [ERR] portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png | Failed: Unreachable mail address: portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png: Invalid: Email doesn't exist or is syntactically incorrect
✗ [ERR] portal/wikipedia.org/assets/img/Wikipedia-logo-v2@1.5x.png | Failed: Unreachable mail address: portal/wikipedia.org/assets/img/Wikipedia-logo-v2@1.5x.png: Invalid: Email doesn't exist or is syntactically incorrect
✗ [ERR] portal/wikipedia.org/assets/img/Wikinews-logo_sister@2x.png | Failed: Unreachable mail address: portal/wikipedia.org/assets/img/Wikinews-logo_sister@2x.png: Invalid: Email doesn't exist or is syntactically incorrect

🔍 334 Total ✅ 330 OK 🚫 3 Errors (HTTP:3) 💤 1 Excluded
```

So `portal/wikipedia.org/assets/img/Wikipedia-logo-v2@2x.png` is erroneously detected as email address.
The problem can be isolated by creating the file "test.html" and then running `lychee test.html`.

test.html:

```html
<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <title>Test</title>
  </head>
  <body>
    <img srcset="v2@1.5x.png" alt="Wikipedia" width="200" height="183">
  </body>
</html>
```

So the same thing happens with a value of `v2@1.5x.png` for `srcset`. Probably the same happens for just `src` in `img` tags.
Does it make sense to check `src` and `srcset` for email addresses?

**Comment by mre** [comment]
Thanks for the issue. Checking src and srcset for emails makes no sense indeed. We should add a condition, which checks that. It would avoid a lot of false positives.
