### ISSUE TITLE
failing check on youtube channel

### ISSUE THREAD

**Issue by oupala** [lycheeverse/lychee#1115]
When checking a Youtube url from a Youtube channel, the check fails as it seems to be redirected:

> * [ERR] [https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA](https://www.youtube.com/channel/UC    aNlbnghtwlsGF-KzAFThqA) | Failed: Too many redirects: error following redirect for url (https://www.y    outube.com/channel/UCaNlbnghtwlsGF-KzAFThqA): too many redirects

I can't reproduce this behaviour and do not understand why the check fails.

**Comment by oupala** [comment]
I can't run the same command as you as I'm running lychee in a Docker container.

But I think I understand why it fails with the following command:

> lychee 'https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA'
? [IGNORED] ios-app://544007664/vnd.youtube/www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA | Unsupported: Error creating request client: builder error for url (ios-app://544007664/vnd.youtube/www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA): URL scheme is not allowed
⠁ 1/41 ETA 12s ░░░░░░░░░░░░░░░░░░░░ ? [IGNORED] ios-app://544007664/vnd.youtube/www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA | Unsupported: Error creating request client: builder error for url (ios-app://544? [IGNORED] android-app://com.google.android.youtube/http/www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA | Unsupported: Error creating request client: builder error for url (android-app://com.google.android.youtube/http/www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA): URL scheme is not allowed
⠁ 2/41 ETA 6s ░░░░░░░░░░░░░░░░░░░░ ? [IGNORED] android-app://com.google.android.youtube/http/www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA | Unsupported: Error creating request client: builder error for url (? [IGNORED] vnd.youtube://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA | Unsupported: Error creating request client: builder error for url (vnd.youtube://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA): URL scheme is not allowed
⠁ 3/41 ETA 4s █░░░░░░░░░░░░░░░░░░░ ? [IGNORED] vnd.youtube://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA | Unsupported: Error creating request client: builder error for url (vnd.youtube://www.youtube.com/ch✗ [ERR] http://sciencetonn/ | Failed: Network error: dns error: no record found for Query { name: Name("sciencetonn."), query_type: AAAA, query_class: IN }
✔ [200] https://www.youtube.com/s/desktop/7fca68b5/img/favicon.ico
✔ [200] https://www.youtube.com/creators/
✔ [200] https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700&family=YouTube+Sans:wght@300..900&display=swap
✔ [200] https://www.youtube.com/manifest.webmanifest
✔ [200] https://yt3.googleusercontent.com/ytc/AGIKgqP3QpuicmK3Hmc37hgP-enlsOw8ocJL2m2Zju8y=s900-c-k-c0x00ffffff-no-rj
✔ [200] https://www.youtube.com/s/desktop/7fca68b5/img/favicon_96x96.png
✔ [200] https://www.youtube.com/s/desktop/7fca68b5/img/favicon_48x48.png
✔ [200] https://www.youtube.com/s/desktop/7fca68b5/img/favicon_144x144.png
✔ [200] https://yt3.googleusercontent.com/ytc/AGIKgqP3QpuicmK3Hmc37hgP-enlsOw8ocJL2m2Zju8y=s900-c-k-c0x00ffffff-no-rj
✔ [200] https://www.youtube.com/s/desktop/7fca68b5/cssbin/www-main-desktop-watch-page-skeleton.css
✔ [200] https://www.youtube.com/s/desktop/7fca68b5/cssbin/www-onepick.css
✔ [200] https://www.youtube.com/s/_/ytmainappweb/_/ss/k=ytmainappweb.kevlar_base.FK8zOwYXjy0.L.X.O/am=AAU/d=0/rs=AGKMywEBDqxV38y24N8slkta-iUDwUPqgQ
✔ [200] https://www.youtube.com/s/desktop/7fca68b5/img/favicon_32x32.png
✔ [200] https://www.youtube.com/howyoutubeworks?utm_campaign=ytgen&utm_source=ythp&utm_medium=LeftNav&utm_content=txt&u=https%3A%2F%2Fwww.youtube.com%2Fhowyoutubeworks%3Futm_source%3Dythp%26utm_medium%3DLeftNav%26utm_campaign%3Dytgen
⠁ 18/41 ETA 0s ████████░░░░░░░░░░░░ ✔ [200] https://www.youtube.com/howyoutubeworks?utm_campaign=ytgen&utm_source=ythp&utm_medium=LeftNav&utm_content=txt&u=https%3A%2F%2Fwww.youtube.com%2Fhowyoutubeworks%3Futm_s✔ [200] https://www.youtube.com/about/copyright/
✔ [200] https://www.youtube.com/feeds/videos.xml?channel_id=UCaNlbnghtwlsGF-KzAFThqA
✔ [200] https://www.youtube.com/about/policies/
✔ [200] https://www.youtube.com/ads/
✔ [200] https://www.youtube.com/t/contact_us/
✔ [200] https://www.youtube.com/opensearch?locale=fr_FR
✔ [200] https://www.youtube.com/t/terms
✔ [200] https://www.youtube.com/
✔ [200] http://schema.org/Person
✔ [200] http://schema.org/ImageObject
✔ [200] https://www.youtube.com/about/
✔ [200] https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA
✔ [200] https://support.google.com/youtube/contact/FR_Complaints
✔ [200] https://www.youtube.com/t/privacy
✔ [200] https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA
✔ [200] https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA?feature=applinks
✔ [200] https://www.youtube.com/about/press/
✔ [200] https://m.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA
✔ [200] https://www.youtube.com/new
✔ [200] https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddesktop%26hl%3Dfr%26next%3D%252Fsignin_passive%26feature%3Dpassive&hl=fr
⠉ 38/41 ETA 0s ██████████████████░░ ✔ [200] https://accounts.google.com/ServiceLogin?service=youtube&uilel=3&passive=true&continue=https%3A%2F%2Fwww.youtube.com%2Fsignin%3Faction_handle_signin%3Dtrue%26app%3Ddes✔ [200] https://www.tipeee.com/science-etonnante
✔ [200] http://sciencetonnante.wordpress.com/
✔ [200] https://developers.google.com/youtube
  41/41 ETA 0s ████████████████████ Finished extracting links                                                                                                                                                      
Issues found in 1 input. Find details below.
> 
> [https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA]:
✗ [ERR] http://sciencetonn/ | Failed: Network error: dns error: no record found for Query { name: Name("sciencetonn."), query_type: AAAA, query_class: IN }
> 
> 🔍 41 Total ✅ 37 OK 🚫 1 Error (HTTP:1)

Lychee is retreiving the Youtube webpage, and follows each link that is found in this webpage.

**Comment by mre** [comment]
Yes, exactly. Now I wonder why that is the case. Do you give it that URL to check? If so, you might want to put it into a file and pass that instead.

**Comment by oupala** [comment]
`echo 'https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA' | lychee -` is ok.

**but**

`echo 'https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA' | lychee --max-redirects 0 -` is not.

It look like Youtube is redirecting to itself...

**Comment by mre** [comment]
The web is a dark and unforgiving place.

This fails:

```
echo 'https://www.youtube.com/channel/UCaNlbnghtwlsGF-Kz
AFThqA' | cargo run -- --max-redirects 1 -
```

This works:

```
echo 'https://www.youtube.com/channel/UCaNlbnghtwlsGF-Kz
AFThqA' | cargo run -- --user-agent curl/7.37.0 --max-redirects 1 -
```

Turns out YouTube has an exception for curl.
Maybe you want to pass the user-agent and see if that works for you.

It's the redirect to the cookie consent, if you're curious:

```sh
echo 'https://www.youtube.com/channel/UCaNlbnghtwlsGF-Kz
AFThqA' | cargo run -- -v -
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
     Running `target/debug/lychee -v -`
⠁ 0/1 ━━━━━━━━━━━━━━━━━━━━ https://www.youtube.com/channel/UCaNlbnghtwlsGF-
[INFO ] Redirecting to https://consent.youtube.com/m?continue=https%3A%2F%2
Fwww.youtube.com%2Fchannel%2FUCaNlbnghtwlsGF-KzAFThqA%3Fcbrd%3D1&gl=DE&m=0&
pc=yt&cm=2&hl=de&src=1
[INFO ] Redirecting to https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAF
ThqA?cbrd=1&ucbcb=1
✔ [200] https://www.youtube.com/channel/UCaNlbnghtwlsGF-KzAFThqA
```

Note that I run lychee from the source code, as I added custom logging to show the redirects.
Maybe I should add that to the lychee CLI, so that users can check the redirects with `-vv`?

**Comment by oupala** [comment]
Yes, that would be great to be able to see the redirects, it would make possible to see if it is only a cookie redirect, a language redirect, or a real redirect to another resource.

**Comment by mre** [comment]
Thanks, I've created a PR to add some logging for redirects. 👍 
With that, I guess we can close this. I appreciate the report.
