### ISSUE TITLE
url check fail for a DNS issue

### ISSUE THREAD

**Issue by oupala** [lycheeverse/lychee#1116]
When checking an url, the check fails for a DNS cause:

> * [ERR] [https://www.boite-sans-projet.org/wp-content/uploads/2017/02/Broch_Virus36-Pour-de-nouvelles    -formes-de-d%C3%A9bat-d%C3%A9mocratique.pdf](https://www.boite-sans-projet.org/wp-content/uploads/201    7/02/Broch_Virus36-Pour-de-nouvelles-formes-de-d%C3%A9bat-d%C3%A9mocratique.pdf) | Failed: Network er    ror: dns error: no record found for Query { name: Name("www.boite-sans-projet.org.lan."), query_type:     AAAA, query_class: IN }

How dos lychee get the following DNS query: `www.boite-sans-projet.org.lan.` ?

**Comment by oupala** [comment]
I was running lychee in a GitLab CI pipeline, so I cannot tell what was the DNS configuration of the GitLab runners, but I think that was the cause of the failure.

I tried then to run lychee on my workstation, where I run it as a Docker container. I do have another error than you:

> lychee "https://www.boite-sans-projet.org/wp-content/uploads/2017/02/Broch_Virus36-Pour-de-nouvelles-formes-de-d%C3%A9bat-d%C3%A9mocratique.pdf"
⠁ 1/2 ETA 0s ██████████░░░░░░░░░░ ✗ [ERR] q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BDb%EF%BF%BD%EF%BF%BD%EF%BF%BD6%EF%BF%BDu%EF%BF%BD | Failed: Unreachable mail address: q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BD✗ [ERR] q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BDb%EF%BF%BD%EF%BF%BD%EF%BF%BD6%EF%BF%BDu%EF%BF%BD | Failed: Unreachable mail address: q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BDb%EF%BF%BD%EF%BF%BD%EF%BF%BD6%EF%BF%BDu%EF%BF%BD: Invalid: Email doesn't exist or is syntactically incorrect
⠁ 1/2 ETA 0s ██████████░░░░░░░░░░ ✗ [ERR] q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BDb%EF%BF%BD%EF%BF%BD%EF%BF%BD6%EF%BF%BDu%EF%BF%BD | Failed: Unreachable mail address: q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BD⠁ 2/2 ETA 0s ████████████████████ ✗ [ERR] %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD | Failed: Unreachable mail address: %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD: Invalid: Email doesn't exi✗ [ERR] %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD | Failed: Unreachable mail address: %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD: Invalid: Email doesn't exist or is syntactically incorrect
⠁ 2/2 ETA 0s ████████████████████ ✗ [ERR] %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD | Failed: Unreachable mail address: %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD: Invalid: Email doesn't exi  2/2 ETA 0s ████████████████████ Finished extracting links                                                                                                                                                        
Issues found in 1 input. Find details below.
> 
> [https://www.boite-sans-projet.org/wp-content/uploads/2017/02/Broch_Virus36-Pour-de-nouvelles-formes-de-d%C3%A9bat-d%C3%A9mocratique.pdf]:
✗ [ERR] %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD | Failed: Unreachable mail address: %EF%BF%BD%EF%BF%BD%EF%BF%BD@lJ%EF%BF%BDw.Wf%EF%BF%BD: Invalid: Email doesn't exist or is syntactically incorrect
✗ [ERR] q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BDb%EF%BF%BD%EF%BF%BD%EF%BF%BD6%EF%BF%BDu%EF%BF%BD | Failed: Unreachable mail address: q%EF%BF%BD@C%EF%BF%BD%EF%BF%BD.po%EF%BF%BDb%EF%BF%BD%EF%BF%BD%EF%BF%BD6%EF%BF%BDu%EF%BF%BD: Invalid: Email doesn't exist or is syntactically incorrect
> 
> 🔍 2 Total ✅ 0 OK 🚫 2 Errors (HTTP:2)

It does not work either when I add the `--exclude-mail` parameter.

The link is not a 404 error as I can load the pdf file from my browser. I think you get the 404 error because of the url split on two lines.

**Comment by mre** [comment]
The two commands do different things.
Your command checks *inside* the PDF document and since PDFs are not officially supported, you run into the false positives around email detection.

```
lychee "https://www.boite-sans-projet.org/wp-content/uploads/2017/02/Broch_Virus36-Pour-de-nouvelles-formes-de-d%C3%A9bat-d%C3%A9mocratique.pdf"
```

The following command checks if the link to the PDF itself is available.
The `echo` makes it so that the link itself (and not the actual PDF document) is the input.

```
echo 'https://www.boite-sans-projet.org/wp-content/uploads/2017/02/Broch_Virus36-Pour
-de-nouvelles -formes-de-d%C3%A9bat-d%C3%A9mocratique.pdf' | lychee -
```

**Comment by mre** [comment]
If the GitLab runner doesn't resolve the domain correctly, there ain't nothing we can do about it other than fixing the config or excluding the domain. 😕

**Comment by oupala** [comment]
I agree.

**Comment by mre** [comment]
Sorry for the inconvenience.

You can exclude this domain with `--exclude www.boite-sans-projet.org`. You can also create a `.lycheeignore` file in the root of your project and add it there.

**Comment by oupala** [comment]
Yeah, I think I'll have to do that because some websites are blocking lychee (probably based on its user agent).

**Comment by mre** [comment]
Some websites indeed block unknown user agents (as in our other discussion on #1115). However, in this case, the IP address can't even be resolved for that domain. That's a GitLab DNS issue. Maybe it will "fix itself" at some point, or maybe you can use a custom runner, but that's outside the scope for now. 😅
