### ISSUE TITLE
How to check all *.md files under one folder_1 and also under folders under folder_1

### ISSUE THREAD

**Issue by Wuliyuanulb** [lycheeverse/lychee#112]
Hi,

I use --verbose folder/*.md to let lychee check links in all md files, but I also need it to check other md files under other folders. Is this supported?

Thanks

**Comment by mre** [comment]
Yeah, just use multiple arguments:
```
lychee --verbose 1/*.md 2/*.md
```
There is no limit on the maximum number of inputs. You can also mix inputs from different sources:

```
lychee --verbose 1/*.md 2/*.md https://endler.dev
```

This checks the markdown files in the folders 1 and 2 as well as all links on endler.dev. 😃

**Comment by MichaIng** [comment]
Or use extended globs to check all Markdown files in all directories below the current one recursively:
```
lychee -v '**/*.md'
```
Note the required single quotes since lychee itself does the file matching here as extended globs (`**` to match directories recursively) are not supported by default in most shells.

**Comment by mre** [comment]
@Wuliyuanulb can we close this or do you have any follow-up questions?

**Comment by joesan** [comment]
I have a question on this one. How do I specify a root directory under which I want all the markdown files scanned for broken link?

**Comment by MichaIng** [comment]
```
lychee -v '/path/to/**/*.md'
```
or
```
cd /path/to
lychee -v '**/*.md'
```
with `/path/to` being the path to that root directory.

**Comment by mre** [comment]
We use [glob](https://docs.rs/glob/) for that. According to [the docs about patterns](https://docs.rs/glob/0.3.0/glob/struct.Pattern.html), 

> ** matches the current directory and arbitrary subdirectories. This sequence must form a single path component, so both **a and b** are invalid and will result in an error. A sequence of more than two consecutive * characters is also invalid.

This also explains why `**.md` doesn't work: `**` can only stand on its own.

Just checked if lychee was picking up the current directory when using a glob.
Created the following file tree:

```
❯❯❯ tree
.
├── 1
│   └── bar.md
├── 2
│   ├── 3
│   │   └── bla.md
│   └── baz.md
└── foo.md

3 directories, 4 files
```

Here's the glob test for `ls`:

```
ls **/*.md
1/bar.md   2/3/bla.md 2/baz.md   foo.md
```

And here's the lychee command:

```
❯❯❯ lychee --verbose --progress '**/*.md'
✅ http://foo.com/ [200 OK]
✅ http://bla.com/ [200 OK]
✅ http://baz.com/ [200 OK]
✅ http://bar.com/ [200 OK]

📝 Summary
-------------------
🔍 Total: 4
✅ Successful: 4
⏳ Timeouts: 0
🔀 Redirected: 0
👻 Excluded: 0
🚫 Errors: 0
```

So it did pick up http://foo.com. 😃 Also works without the quotes around `**/*.md` on zsh.

**Comment by mre** [comment]
That should answer all questions and we can close this I guess. 😄

**Comment by MichaIng** [comment]
> Also works without the quotes around **/*.md on zsh.

True, but if the shell did not support it or has `**` support disabled (default in bash), the shell could theoretically expand `*` and lychee would then get a glob with `*` possibly pre-expanded, hence won't find all matches anymore. It's unlikely that there is a file path with literal `**`, but I like to be explicit when spamming shell commands into the world 😄.

**Comment by mre** [comment]
Oh yeah, absolutely. I recommend to always quote it so that there are no differences with varying environments. Thanks for pointing that out. 👍
