### ISSUE TITLE
remap - can it rewrite partial URLs? 

### ISSUE THREAD

**Issue by rmoff** [lycheeverse/lychee#1129]
I have a list of URLs: 

```
https://docs.lakefs.io/integrations/distcp.html
https://docs.lakefs.io/howto/import.html#working-with-imported-data
https://docs.lakefs.io/howto/garbage-collection-committed.html
```

I want to test these URLs against my local build of the docs site (at `file:///Users/rmoff/git/lakeFS/docs/_site/`). This works using `sed`: 

```
sed 's/https:\/\/docs.lakefs.io/file:\/\/\/Users\/rmoff\/git\/lakeFS\/docs\/_site/' /tmp/list.txt | \
  lychee --dump -
file:///Users/rmoff/git/lakeFS/docs/_site/integrations/distcp.html
file:///Users/rmoff/git/lakeFS/docs/_site/howto/import.html#working-with-imported-data
file:///Users/rmoff/git/lakeFS/docs/_site/howto/garbage-collection-committed.html
```

I thought that remap could do this more elegantly for me, but whilst it remaps the base URL it ignores the rest of the mapped URL: 

```
lychee --remap 'https://docs.lakefs.io/ file:///Users/rmoff/git/lakeFS/docs/_site' --dump /tmp/list.txt
file:///Users/rmoff/git/lakeFS/docs/_site
file:///Users/rmoff/git/lakeFS/docs/_site
file:///Users/rmoff/git/lakeFS/docs/_site
```

Am I misunderstanding remap, or just using it incorrectly? 

thanks!

**Comment by mre** [comment]
The remap feature is not powerful enough yet, but there is no reason why it couldn't be. It's a great idea to extend its functionality. We can support arbitrary mappings using (named) regex captures, which would be a nice feature to have.
