### ISSUE TITLE
--exclude option excludes input files

### ISSUE THREAD

**Issue by MichaIng** [lycheeverse/lychee#113]
I just recognised that the `--exclude` option takes all following arguments as exclude expressions. It took me a while understand why `Error: Failed to read file: README.md` shows up even that I passed a lot of other files and globs as input 😄. `--` or another option (argument starting with dash) ends the exclude arguments.

If this is expected, probably a note in README + help text would be good, that `--` shall be used to end the list of exclude arguments before the input file arguments start.

Otherwise, probably `--exclude` could use a single argument only. It should be enough since `(a|b|c)` regex syntax can be used to concatenate multiple expressions anyway? Or `--exclude` could be allowed multiple times.

Not sure what is best here and it is not really a bug, but since it took me 30 minutes to find out what is wrong, I thought it's a good idea to prevent other users from running into the same 😄.

**Comment by mre** [comment]
We don't do anything fancy with `--exclude`; it's just a normal structopt field:

https://github.com/lycheeverse/lychee/blob/bfeeb28e1dab261f5025a9affdd483d61bf63ca6/src/bin/lychee/options.rs#L159-L162

So I'd say that's kind of the convention in structopt when you have a field that uses `Vec<_>` as a type.
At least according to the POSIX standard it seems to be standard behavior:

See Guideline 10 [here](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html):
> The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.

I agree that it can be counterintuitive. We can debate if we want to change it if there is a way so that structopt only takes a single argument after `--exclude`. I doubt that this is possible, though and there might be good reasons for it. 😉

**Comment by MichaIng** [comment]
Yes as said, it's not a bug, just a syntax that is probably rarely enough used so that inexperienced users and as well higher experienced developers like me sometimes run into 😅.

Mostly I know this from X server calls and similar, where you want to pass multiple parameters to the client/child layer, followed by parameters to the server/parent layer, which then need to be delimited by `--`, but indeed for multiple arguments to single options, when it's not such a multi-layer thing, at least me can't remember another case, currently.

Probably it's enough to add a line about this to readme + help output, which could be even written a way that makes clear that it is expected common syntax:
> Multiple arguments are allowed for this option, remember to use "--" to separate the list of exclusions from the list of inputs.

**Comment by mre** [comment]
We have the same behavior for includes and headers. Would you add that note to all of these parameters in that case, add it to the lychee help output as a general note below all options, or just to the `README.md`?

**Comment by MichaIng** [comment]
Oh, I didn't think about that. To be effective, it would make sense in the usage/`--help` output of the binary itself, but not in full length below each option that supports multiple arguments.

Btw, I see now that it's already part of the usage info:
> `lychee [FLAGS] [OPTIONS] [--] [inputs]...`

Maybe it's really just me who run into this, even overseeing this usage reminder. If at all, probably an additional sentence for the `ARGS: <inputs>...` block would do, like:
> Prefix with "--" to separate inputs from options that allow multiple arguments.

**Comment by mre** [comment]
Sounds reasonable. #119 😄
