### ISSUE TITLE
Print scanned sources when using "--verbose" option

### ISSUE THREAD

**Issue by MichaIng** [lycheeverse/lychee#114]
Currently the `--verbose` option prints all checked links, but not the files/sources in which those URLs were found. It would be great if `lychee` would print the currently processed source as well before the checked URLs found in each source.

But I guess the concurrency of processed sources will be an issue to implement this, right?

**Comment by mre** [comment]
Yeah that should be possible. Some thoughts below.

* We have to find a balance between too little and too much output for the verbose option, though. One idea that came to mind was to have different levels of verbosity (`-v`, `-vv`, `-vvv`) similar to curl et al. I'd argue that we could show the sources at a higher level of verbosity, perhaps `-vvv`.
* Once we support recursion (#78), the output won't be linear anymore. With that I mean that lychee would print the sources, then some link checking results followed by more sources and so on. It would stop when the recursion limit is reached. That is just something to be aware of.
* I would assume that dumping the sources is mostly helpful for initial troubleshooting, right? If that's true  we could alternatively have an option to dump the scanned sources and terminate, similar to https://github.com/lycheeverse/lychee/pull/99.

**Comment by MichaIng** [comment]
> I would assume that dumping the sources is mostly helpful for initial troubleshooting, right?

Actually when using it to check larger websites with many pages, it's helpful to directly see the file where the faulty link is located, making an additional step obsolete to first search that link. So, when using verbosity levels, I would move printing false positives (which are indeed only useful on the meta level, to test or debug the lychee usage itself) to a higher verbosity level and print sources earlier, which can be helpful on a regular basis, at least the way we would currently use it.

> Once we support recursion (#78), the output won't be linear anymore.

Indeed it would get more complicated then to keep the output of sources useful without post-processing it. For a low number of recursion levels some indentation could do, but no way with 10 levels or more. Probably best is to keep it easy and simply print the currently processed source whenever it changes (and at least one failing URL was found?), so as well when moving from deeper recursion level back to higher one. The same source could then be listed multiple times, but the aim to see the source of a failed URL easily stays intact.
______________
But I just realise that it's probably two different things:
1. Print all scanned sources for testing the lychee usage itself, which make sense behind a debug level.
2. Print sources along with failed URL checks only, for regular usage to help find the location of the bad link.

**Comment by mre** [comment]
Fully agree.
We could add the input source as a field to the response. It is currently defined as:
https://github.com/lycheeverse/lychee/blob/5c8a4dfa7eb1e38b85c92c6f07e5d63b6c43b621/src/types.rs#L22-L26
Adding the input field would allow us to print the sources on failed URLs.
The downside is additional memory usage. If we assume about 50 bytes per URL and say 1000 links in total (it's probably lower in reality) then the additional runtime memory would be 50kb. I'd say that's acceptable. 😏 We could get more fancy with string interning but let's not overdo it. 
@pawroman @MichaIng what do you say?

**Comment by MichaIng** [comment]
To avoid much additional memory usage, as long as multiple files are not processed concurrently, instead a variable could hold the currently processed source string, to print it if an URL failed before printing the URL + status itself. On certain verbose level, the currently processed source could be printed directly, instead of on first failure only. A flag (or simply unsetting the variable that holds the currently processed source string) could then indicate that the processed file has already been printed to have the name only once on top of all failed (or on verbose run all processed) contained URLs.

That that becomes complicated already on recursive processing, as mentioned above, and impossible when processing multiple sources concurrently. So your idea seems to more robust and I'd say for such a process 1 MiB more or less memory usage (which is hardly possible to archive) doesn't matter much. It's a bit of output overhead to have the source/file name printed together with each URL instead of once on top of all contained ones only, but same problem regarding concurrent processing.

**Comment by joesan** [comment]
Is this in progress or implemented? I raised more or less a same issue here: https://github.com/lycheeverse/lychee-action/issues/11

**Comment by mre** [comment]
This is not worked on right now. We're looking for contributors.
The idea is to add a `source` field to the `Response` struct as mentioned in https://github.com/lycheeverse/lychee/issues/114#issuecomment-762818873. The overhead should be acceptable.

**Comment by joesan** [comment]
As a further optimization, could we just limit the printing of the source markdown files for the failing links? Because it is what I'm most interested in, to know which source file has a failing link?

**Comment by mre** [comment]
Yes, that's the plan. The current output already prints the failing links only, e.g.

```
🚫 https://example.com/README.md [404 Not Found]
```

The easiest would be to add the source file like this:

```
🚫 https://example.com/README.md [404 Not Found] (file: README.md)
```

Would that work for you?

**Comment by MichaIng** [comment]
> https://example.com/README.md [404 Not Found] (file: README.md)

The readme contains a link to itself? 😄
It's clear what you mean 👍.

As mentioned above, best overview IMO is served by `liche`. While not everything is perfect, it does some things very well:
```
index.html
	ERROR	https://somedomain.com
		Dialing to the given TCP address timed out
	ERROR	https://someotherdomain.org/page.php
		Not Found (HTTP error 404)
```
Very easy to spot affected files, to open them in an editor and go through the contained errors. But more complicated to implement with recursion as mentioned above, probably not worth it.

**Comment by mre** [comment]
Working on this in #143.

**Comment by mre** [comment]
This is merged now. @MichaIng can you give it another shot by installing lychee from the `master` branch? (git clone and cargo install)

**Comment by mre** [comment]
Same for @joesan 😉

**Comment by MichaIng** [comment]
Is there a certain option required currently? I tested with two input URLs as well as two test files with failing contained links/URLs but do not see the source file or URL after the response code field.

I definitely built from master branch, but the binary still reports v0.5.0, which still needs to be updated? Or did I do something wrong with cargo? Should actually not be possible that it is indeed an older version without any Git checkout made 🤔.

**Comment by mre** [comment]
> Is there a certain option required currently? 

Nope, should work out of the box.

> ...but do not see the source file or URL after the response code field.

The status gets printed at the end including all failed links, very similar to what you describe for liche in https://github.com/lycheeverse/lychee/issues/114#issuecomment-778146698.
I tested printing the source after every reponse, but it was way too verbose in that case. We could add `-vvv` or so to show these, but I doubt that it's helpful.

> I definitely built from master branch, but the binary still reports v0.5.0

That's weird. The current master is 0.6.0. See here: https://github.com/lycheeverse/lychee/blob/ae2d02b8a0bb5e186478c5cf6a2d1ecad0c5ac64/Cargo.toml#L17
So you might have to try again. If it doesn't print 0.6.0 something went wrong.
Can you try a fresh clone?

**Comment by MichaIng** [comment]
The clone is definitely correct:
```
# grep -m1 version Cargo.toml
version = "0.6.0"
# git checkout master
Already on 'master'
```
But the resulting binary tells otherwise:
```
# .cargo/bin/lychee -V
lychee 0.5.0
```
But I see that this should not be possible: https://github.com/lycheeverse/lychee/blob/master/src/client.rs#L17
```
# cat .cargo/.crates.toml
[v1]
"lychee 0.5.0 (registry+https://github.com/rust-lang/crates.io-index)" = ["lychee"]
```
I see cargo invokes Git as well, probably it uses the last stable release automatically somehow? I see this "updating crates" tasks before it starts compiling, but I don't know what it is about 😅. I'm rebuilding currently after another hard reset + checkout and now build only, not install, let's see.

**Comment by MichaIng** [comment]
Ignore my previous (deleted) post, if you saw it, not sure what I made wrong but now it worked, and I like how you implemented it:
```
# ./target/debug/lychee https://dietpi.com/ https://dietpi.com/docs/ - <<< 'https://doesnotexist.i.guess'
⚡ https://doesnotexist.i.guess/ (error sending request for url (https://doesnotexist.i.guess/): error trying to connect: dns error: failed to lookup address information: Name or service not known)
🚫 https://twitter.com/DietPi_ [400 Bad Request]
🚫 https://fonts.gstatic.com/ [404 Not Found]
🚫 https://twitter.com/DietPi_ [400 Bad Request]

📝 Summary
--------------------
🔍 Total...........89
✅ Successful......85
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........4

Input: https://dietpi.com/docs/
   🚫 https://fonts.gstatic.com/
      Failed (404 Not Found)
   🚫 https://twitter.com/DietPi_
      Failed (400 Bad Request)
Input: stdin
   ⚡ https://doesnotexist.i.guess/
      Runtime error (error sending request for url (https://doesnotexist.i.guess/): error trying to connect: dns error: failed to lookup address information: Name or service not known)
Input: https://dietpi.com/
   🚫 https://twitter.com/DietPi_
      Failed (400 Bad Request)
```
Twitter btw is expected to fail on all wget/curl GET and HEAD requests as well recently 😉.

> We could add `-vvv` or so to show these, but I doubt that it's helpful.

I agree, issue well solved IMO, many thanks 👍! @joesan if you agree, I'll close this issue.

**Comment by joesan** [comment]
I can give it a try. Is it integrated into the GitHub action? Do I change the version simply to 2?

`uses: lycheeverse/lychee-action@v1`

**Comment by MichaIng** [comment]
It won't be available through the GitHub action until it's released, I guess, it needs to be manually compiled. If that is currently not applicable for you, and you need more impression of the feature than what I posted above, I can run and post another command. A functional test is probably not required, but more if you're missing something or if the way it's implemented covers the idea you had when opening the issue at the action's repo 🙂.

**Comment by mre** [comment]
Actually it's already in the Github action. 😉

**Comment by mre** [comment]
Think we can close this.
Summary:
* Part of lychee master
* Part of the lychee-action@master
