### ISSUE TITLE
Provide checksums for releases

### ISSUE THREAD

**Issue by 4x0v7** [lycheeverse/lychee#115]
Hi there

This is an enhancement request.
It would be nice to have SHA256 checksums provided for releases of lychee

**Comment by mre** [comment]
Yeah that makes sense. It's not the top priority right now, but if you want to give it a shot, the code is here:
https://github.com/lycheeverse/lychee/blob/master/.github/workflows/release.yml
We would have to add another step to calculate and upload the checksum.
This other pipeline could help: https://github.com/deild/macos-config-check/blob/25195984ac087876bb66e93f96d5dc966ce6be2b/.github/workflows/release.yml

**Comment by 4x0v7** [comment]
Thanks! I'll have a look at those examples and see what's possible

**Comment by mre** [comment]
@4x0v7 any updates?

**Comment by 4x0v7** [comment]
haven't had a chance to look into this yet

**Comment by mre** [comment]
All good. Just wanted to know if you need support. 😊

**Comment by mre** [comment]
Gonna close this for now to keep the issue tracker clean. @4x0v7, if you get around to working on it, feel free to reopen. 😊
