### ISSUE TITLE
Ignore links in prefix attributes

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#1209]
E.g.

```html
<html lang="en-EN" prefix="og: https://ogp.me/ns#">
```

**Comment by xlai89** [comment]
Hi @mre ,

I had a very good first experience with lychee. Thank you for developing the tool!
I am also learning to program more with rust and to contribute more in the OS community. 
May I try working on this issue?

Some guidance would be really helpful though. 
Is it a valid way to extend the element/attribute combinations in [`html5gum.rs`](https://github.com/lycheeverse/lychee/blob/master/lychee-lib/src/extract/html/html5ever.rs#L138) and [`html5ever.rs`](https://github.com/lycheeverse/lychee/blob/master/lychee-lib/src/extract/html/html5gum.rs#L59) and then add "html" into the function [`is_verbatim_elem`](https://github.com/lycheeverse/lychee/blob/master/lychee-lib/src/extract/html/mod.rs#L34)? Would this impact other use cases, where "html" should not be excluded, when `include_verbatim` is `false`?

**Comment by mre** [comment]
Hey @xlai89,
thanks for considering to work on this! That would be great. 👍 

The changes would be quite similar to https://github.com/lycheeverse/lychee/pull/1187.
Perhaps you want to tackle that one first? You can try to follow the comments and see if you can help out.
It's of course totally fine to also tackle this issue first. You'll probably follow the same structure anyway, so the order shouldn't matter that much.

**Comment by xlai89** [comment]
Thanks for the hint. I'll try to understand and maybe work on PR #1187 first.
