### ISSUE TITLE
Make release notes readable

### ISSUE THREAD

**Issue by szepeviktor** [lycheeverse/lychee#1239]
Currently the nightly is a mess.
Please consider popping the text into a text editor,
remove bump-s, then remove non-bump-s. (with a regexp search or line sorting)

Something like this
https://github.com/szepeviktor/lychee/releases/tag/nightly

**Comment by mre** [comment]
The nightly releases are auto-generated. 
https://github.com/lycheeverse/lychee/blob/master/.github/workflows/nightly.yml
If we want to do this, someone would have to format it in the CI pipeline.

@szepeviktor, would you be willing to open a PR for it?
@kemingy FYI

**Comment by kemingy** [comment]
We can create a release template file like https://github.com/mosecorg/mosec/blob/main/.github/release.yml. The auto-generated release note will use this format.

**Comment by mre** [comment]
Oh, I'm all for it!

**Comment by szepeviktor** [comment]
> Would you like to look into that as well szepeviktor?

No.

**Comment by mre** [comment]
Done https://github.com/lycheeverse/lychee/releases/tag/nightly
