### ISSUE TITLE
App identifier dropped from Google Play store link, rendering link-check error

### ISSUE THREAD

**Issue by keunes** [lycheeverse/lychee#1245]
Hello,

In our markdown file, we have the following link: `[Google Play](https://play.google.com/store/apps/details?id=de.danoeh.antennapod)`. The action gives the following error:
```text
### Errors in _i18n/nl/documentation/general/ads.md
* [404] [https://play.google.com/store/apps/details](https://play.google.com/store/apps/details) | Cached: Error (cached)
```
The part with the question mark seems to get dropped from the URL, making the link, indeed, wrong. Are these parts with the question mark dropped on purpose, or would this be a bug?

**Comment by mre** [comment]
I transferred this issue to the lychee repo.

**Comment by mre** [comment]
Turns out, this is actually an issue with pulldown-cmark.
Here is a repro: https://github.com/mre/pulldown-cmark-multiline-link-repro
You can run it yourself to confirm.

### Input:

```md
works: [](https://example.com)
broken: [](https://example.com?
id=foo)
```

### Output:

```
"works: [](https://example.com)\nbroken: [](https://example.com?\nid=foo)\n" -> [
  Start(Paragraph)
    Text(Borrowed("works: "))
    Start(Link(Inline, Borrowed("https://example.com"), Borrowed("")))
    End(Link(Inline, Borrowed("https://example.com"), Borrowed("")))
    SoftBreak
    Text(Borrowed("broken: "))
    Text(Borrowed("["))
    Text(Borrowed("]"))
    Text(Borrowed("(https://example.com?"))
    SoftBreak
    Text(Borrowed("id=foo)"))
  End(Paragraph)
]
```

Can you report it [upstream](https://github.com/raphlinus/pulldown-cmark)?

**Comment by keunes** [comment]
Closing as out of spec.
