### ISSUE TITLE
Error "unable to get local issuer certificate", while the browsers are happy with the site

### ISSUE THREAD

**Issue by mgrojo** [lycheeverse/lychee#1263]
See https://github.com/ohenley/awesome-ada/issues/115

*    [ERR] https://www.ada-europe.org/ | Failed: Network error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (unable to get local issuer certificate)

The site is secure for Firefox and Chromium. Why is then failing for this link checker?

**Comment by mre** [comment]
Humm... maybe an openssl issue? Or maybe we need to pass some options to reqwest?

**Comment by mre** [comment]
Works for me:

```sh
echo 'https://www.ada-europe.org/' | lychee -v -
✔ [200] https://www.ada-europe.org/
🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

Can you try on a different machine?

**Comment by mgrojo** [comment]
I was using lychee only as a GitHub action. I will try to install it locally and test it.

Might it be then a problem when running inside GitHub's cloud? But I cannot understand why only this site is affected, of all the links in the awesome-ada list.

**Comment by mgrojo** [comment]
> ```shell
> echo 'https://www.ada-europe.org/' | lychee -v -
> ```

I installed using `cargo install --locked lychee`

And I can reproduce the problem:

```
echo 'https://www.ada-europe.org/' | lychee -v -
⠁ 1/1 ETA 0s ████████████████████ ✗ [ERR] https://www.ada-europe.org/ | Failed: ✗ [ERR] https://www.ada-europe.org/ | Failed: Network error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (unable to get local issuer certificate)
⠁ 1/1 ETA 0s ████████████████████ ✗ [ERR] https://www.ada-europe.org/ | Failed:   1/1 ETA 0s ████████████████████ Finished extracting links                     
Issues found in 1 input. Find details below.

[stdin]:
✗ [ERR] https://www.ada-europe.org/ | Failed: Network error: error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1883: (unable to get local issuer certificate)

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```

```
lychee --version
lychee 0.13.0
```

**Comment by mre** [comment]
Then the question is what's special about my machine. 😅
I didn't do anything out of the ordinary, though.

**Comment by mgrojo** [comment]
I running it on Ubuntu 22.04.3 LTS and the GitHub action on 22.04.2 LTS. My knowledge of TLS is very limited. Is the OS involved in the root certificates that you trust? Which one are you using?

**Comment by mgrojo** [comment]
I've seen that `curl` also fails on the site. Both programs are using this openssl version:

Package: libssl3
Version: 3.0.2-0ubuntu1.10

But after further investigation, it might be a problem in the server. This checker https://www.digicert.com/help/ says this:

> The server is not sending the required intermediate certificate.
> 
> In most cases, solving this problem in Apache is as simple as adding "SSLCertificateChainFile /path/to/DigiCertCA.crt" to your apache configuration file after/near your SSLCertificateFile line.
> 
> You can find the missing intermediate in the zip file containing your certificate, or download it from your customer account area.
> 
> Follow the directions on [our certificate installation guide](https://www.digicert.com/ssl-certificate-installation-apache.htm) to install the missing intermediate.
> 
> If you have any problems correcting this issue, please contact our helpful support team and we would be happy to assist.

It is surprising to me, however, that browsers don't warn about this, but OpenSSL library aborts.

**Comment by mre** [comment]
Awesome research and troubleshooting. 👍

**Comment by jacopok** [comment]
Hi, I stumbled into this issue with a website I'd like to link to. I will not open an issue since this is not a problem with `lychee`, but I'd like to ask for advice.

Under the assumption that I'm happy to link to it despite the CA issue, is there a way to not have `lychee` raise an error? 

In the [linked issue](https://github.com/ohenley/awesome-ada/issues/115#issuecomment-1875672160) it's mentioned that changing the link to `http` can be used as a workaround, but that does not seem to work (it still raises an error for me).

**Comment by mre** [comment]
Can you try `--insecure` in combination with the http link?

For what it's worth, it works on my end.

```
echo 'https://www.gssi.it/people/students/students-physics/item/15633-tissino-jacopo' | lychee -
🔍 1 Total (in 0s) ✅ 1 OK 🚫 0 Errors
  ```
