### ISSUE TITLE
Support GitLab token to access private projects

### ISSUE THREAD

**Issue by sanmai-NL** [lycheeverse/lychee#1266]
A GitHub token is already accepted as CLI argument. But I don't see what it translates to in terms of HTTP request.
See https://docs.gitlab.com/ee/api/repository_files.html#get-raw-file-from-repository for how to access a raw file from a private project. I'm not sure that is appropriate for my use case: I simply hyperlink to private project landing pages, which are flagged by Lychee under CI.

**Comment by mre** [comment]
Gitlab is currently not supported, but we can add a `gitlab_token` argument similar to GitHub. 
Contributions welcome. I'm not sure when I would get the opportunity to add this myself.

The GitHub token gets passed to the GitHub crate, octokit. That's the only place where it gets used. However, for gitlab, we can start to pass it as a header if it's a gitlab URL.

**Comment by sanmai-NL** [comment]
I tested and found that specific support for GitLab is unnecessary, using the `--header` CLI/configuration parameter `PRIVATE-TOKEN=...`.  However, this is not usable yet for our applications in CI, due to #1297 and in particular #1298.

**Comment by mre** [comment]
Closing this in favor of fixing https://github.com/lycheeverse/lychee/issues/1298.
