### ISSUE TITLE
Some sites report error when everyhting is okay

### ISSUE THREAD

**Issue by InCogNiTo124** [lycheeverse/lychee#1268]
We use lychee as a weekly action at github.com/zszazi/Deep-learning-in-cloud

However, sometimes some sites are reported ERR while in reality they work. Here is an example of a result:

https://github.com/zszazi/Deep-learning-in-cloud/issues/92

For example, sites `gpueater.com` and `qblock.cloud` both resolve as ERR but can be visited through browser. Any idea?

**Comment by InCogNiTo124** [comment]
Interestingly enough, both gpueater.com and qblock.cloud have their SSL certificates issued by `Sectigo RSA Domain Validation Secure Server CA`

**Comment by mre** [comment]
Yeah, that was the one I meant, thanks.
You can use https://www.digicert.com/help/ to check the domains in question. I got some warnings/errors at least.
So maybe it's not an issue with hosted CI runners, but with the actual servers?

**Comment by mre** [comment]
Closing this as it seems to be unrelated to lychee from what I can tell.
