### ISSUE TITLE
Regex match group result not working in remapping

### ISSUE THREAD

**Issue by aj-stein-nist** [lycheeverse/lychee#1274]
Hello, @nikitawootten-nist and I were testing lychee to remap URLs with regex groups like documented in [the current version of your documentation](https://lychee.cli.rs/#/usage/config).

```toml
# Remap URI matching pattern to different URI.
# This also supports (named) capturing groups.
remap = [
    "https://example.com http://example.invalid",
    "https://example.com/(.*) http://example.org/$1",
    "https://github.com/(?P<org>.*)/(?P<repo>.*) https://gitlab.com/$org/$repo",
]
```

With regards to the last remap, according to output when testing this feature, the groups in the pattern do `(?P<org>.*)/(?P<repo>.*)` do work, but the string replacement literally writes `"https://gitlab.com/$org/$repo"`, *not* the matched name it could be (so not `"https://gitlab.com/aj-stein-nist/cool-new-relocated repo"`, literally `"https://gitlab.com/$org/$repo"`). We tried all nature of things and it appears this is a bug. It always returns the literal string version.

I would be willing to help look into this and fix it.

**Comment by mre** [comment]
Sorry for the inconvenience. This is actually a bug that is resolved in `master`. I haven't released a new version with the fix yet, but you can use a nightly build in the meantime or build from source.
https://github.com/lycheeverse/lychee/releases/tag/nightly

**Comment by aj-stein-nist** [comment]
I was trying to figure out where exactly, it looks like from a quick skim we are talking about https://github.com/lycheeverse/lychee/commit/97573123ef023ad533b380811abdc4cfd89a60d1? Feel free to correct, but I shall close this bug in either case. Thanks again.

**Comment by mre** [comment]
Yes, that's the commit.

**Comment by askalski85** [comment]
Hi @mre, when you are going to release a new version featuring this fix? It is great that the fix is in-place and available, thank you for awesome work!

**Comment by smartcontracts** [comment]
+1 for a docker release! ☺️

**Comment by smartcontracts** [comment]
IMO it's worth reopening this issue until this fix gets released. You can work around this by building from source but most people will be using the releases.

**Comment by sanmai-NL** [comment]
@mre Would it be possible to cut a release soon, please? We use it to map Cloudflare-protected public URLs to the Wayback machine.

**Comment by mre** [comment]
Version 0.14.0 just got release. Finally 😅

**Comment by mre** [comment]
Oh, and there's also a Docker release. See https://hub.docker.com/r/lycheeverse/lychee/tags and search for 0.14.0
