### ISSUE TITLE
Broken links not detected in Markdown

### ISSUE THREAD

**Issue by chipzoller** [lycheeverse/lychee#1282]
Hey 👋 firstly wanted to say THANK YOU for this tool. It's really been a great help!

Asking for a bit of help to figure out why a broken link isn't being detected inside a Markdown file which, according to the logs, is being scanned. Using the Action with the following inputs:

```yaml
          fail: true
          debug: false
          args: --verbose --no-progress './**/*.md' './**/*.html'
```

I have also played around with those globs to force it to pick up any Markdown file anywhere but it doesn't seem to make a difference.

See latest run [here](https://github.com/kubecost/docs/actions/runs/6659597917/job/18099014703). Have a test PR being used to troubleshoot where the issue lies but so far still scratching my head. The file [here](https://raw.githubusercontent.com/kubecost/docs/795e1054df2de46d3ef87fc556b8061a7c76ce20/kubecost-cloud/using-the-kubecost-cloud-ui/kubecost-cloud-abandoned-workloads.md) has a broken link in both the `/foo.md` path and the `/foo/bin/bar.md`.  I see two instances where this is being scanned yet it's not detecting broken links. I know it has picked up on these before. These aren't excluded in the .lycheeignore file. What could possibly account for this? Any suggestions on what to troubleshoot next?

**Comment by mre** [comment]
Hi, try to set `--base .`:
`args: --verbose --no-progress --base . './**/*.md' './**/*.html'`

For a more general discussion on the topic, check out https://github.com/lycheeverse/lychee/issues/1265.
I'd love to get your input on this matter in the linked issue.
Curious to hear your thoughts on what should be sane defaults for lychee around checking root-relative links.

**Comment by chipzoller** [comment]
Thanks very much, that seems to have done the trick. And thanks for referring me to another issue. I see there's a PR filed there so I'll add my two cents.

Closing as this has been resolved by adding the `--base .` argument to lychee.
