### ISSUE TITLE
--offline still requires dns configuration

### ISSUE THREAD

**Issue by stephen-huan** [lycheeverse/lychee#1303]
Running
```shell
lychee --offline .
```
errors with the message
```text
Error: Failed to create request client

Caused by:
    0: Network error
    1: builder error: error reading DNS system conf: No such file or directory (os error 2)
    2: error reading DNS system conf: No such file or directory (os error 2)
```
if there is no network configuration. Ideally `--offline` would modify the codepath so dns isn't required at all.

My specific use case is a bit contrived, but basically I want to use `lychee` in a [sandboxed environment](https://nixos.org/manual/nix/stable/command-ref/conf-file.html#conf-sandbox) without network. It's still useful to lint that local links are valid as cross-linking can easily get out of date when one is re-organizing their webpage.

If it's too much effort to support such a niche use case I understand, thanks!

**Comment by roberth** [comment]
It's not necessarily about _wireless_ configuration, but requiring an `/etc/resolv.conf` to exist is a problem for me too.

It seems that this problem could be solved in the most general way in https://github.com/seanmonstar/reqwest/issues/2046.

**Comment by mre** [comment]
Thanks for creating the issue and also thanks for providing a swift pull request to upstream. Here's hoping that this will be merged soon.

**Comment by roberth** [comment]
Oh that read like I referenced a PR, but I didn't write one (yet?). I'm not productive in Rust yet, so I figured I'd wait for a response first.

**Comment by mre** [comment]
Oh, sorry, I checked on my phone and it looked like a PR.

As a workaround, can you try to create a dummy `/etc/resolv.conf`?
Something like

```
nameserver 8.8.8.8
nameserver 8.8.4.4
```

**Comment by mre** [comment]
@roberth, any update on this? The upstream issue on `reqwest` didn't seem to get much traction. Did you try the workaround above by any chance?

**Comment by mre** [comment]
So looking at the upstream issue, it seems like we can pass our own resolver in that case.
We could define our own dummy resolver, similar to 
https://github.com/seanmonstar/reqwest/blob/e639bdc1264c266a84dae3bae3193e07cae6861b/src/dns/gai.rs#L9
and use that when `--offline` is set. 
If someone wants to give this a shot, please add a comment or create a PR.

**Comment by mre** [comment]
Oh, okay. Thanks for the update. 

Invalid configs should definitely not be silently ignored. Perhaps we should switch to https://github.com/bnjjj/twelf
We used it for another project, and it worked quite fine.

**Comment by roberth** [comment]
I'm adding a helper function in Nixpkgs to make this use case easier, as well as a test in Nixpkgs that can catch a regression of this use case when `lychee` gets updated there.
- https://github.com/NixOS/nixpkgs/pull/298665

Should I add Nix integration to the [features](https://github.com/lycheeverse/lychee?tab=readme-ov-file#features) when that's done?

**Comment by mre** [comment]
Interesting. I don't know much about `Nixpkgs`. 
We already mention `NixOS` support in the installation section [here](https://github.com/lycheeverse/lychee?tab=readme-ov-file#nixos).
Is Nix integration different from this?

**Comment by roberth** [comment]
It is a bit different, and a somewhat more advanced use case. It does make use of package, which was always defined in the Nixpkgs repository, but it doesn't install it to a user's profile or anything.

The goal of the `testers.lycheeLinkCheck` function is to use Nix as a build tool to manage both the building and checking of a static site. That's especially nice if you're already building the site in the Nix sandbox.

You could think of it as a generic CI integration, that's easy to run locally.

**Comment by roberth** [comment]
I've updated https://github.com/NixOS/nixpkgs/pull/298665 to explain the use case a bit more.

**Comment by mre** [comment]
I see. Thanks for the explanation.
Perhaps we can mention it in the installation section or a separate section in the `README.md` somewhere, as it might not be strictly a feature of the CLI tool then?

**Comment by stephen-huan** [comment]
> However, when putting together a test for it, I wasn't able to reproduce the failure, and indeed the latest `lychee` in Nixpkgs seems to work fine in the Nix sandbox. I don't really know what changed, but I'm quite happy about it!

I can confirm this as well. Thanks roberth as well for the PR to nixpkgs!
