### ISSUE TITLE
Possible redirect loop in lychee 1.3.0, may be resolved on nightly

### ISSUE THREAD

**Issue by nathany** [lycheeverse/lychee#1313]
Hi Matthias. In lychee 1.3.0 on macOS 14.1.2, I'm seeing a link be tested many, many times. It doesn't seem like it will ever complete. Options like `--max-retries 1 --max-redirects 2` don't seem to help.

```
lychee output/get-programming-with-go-manuscript.html
```

![redirect-loop](https://github.com/lycheeverse/lychee/assets/4566/bad65aa7-bf48-406b-a54d-5558121cd1c6)

If I open https://www.simple-talk.com/opinion/geek-of-the-week/rob-pike-geek-of-the-week/ in a web browser, it eventually redirects to https://www.red-gate.com/simple-talk/opinion/geek-of-the-week/rob-pike-geek-of-the-week/.

The offending HTML looks like this (generated by AsciiDoctor). This link only occurs once in the HTML.

```html
<blockquote>
"We wanted a language with the safety and performance of statically compiled languages such as C++ and Java, but the lightness and fun of dynamically typed interpreted languages such as Python." (<a href="https://www.simple-talk.com/opinion/geek-of-the-week/rob-pike-geek-of-the-week/" class="bare">www.simple-talk.com/opinion/geek-of-the-week/rob-pike-geek-of-the-week/</a>)
</blockquote>
```

If I build lychee from source, it appears to resolve the issue, among other hangups that are happening in 1.3.0. So I'm reporting it anyway for a few reasons:

* I'm not sure which issue in the [nightly release](https://github.com/lycheeverse/lychee/releases/tag/nightly) resolved it, and I'd like to be sure it was intentionally fixed.
* It may provide a useful test case
* Encouraging another 1.x release, because I'd like to set up `lychee-action`.

**Comment by mre** [comment]
Thanks for the feedback. Gotta finally release a new version of lychee then. 😃 I was planning to do that quite a while ago. There is still one regression, which will break the sentry documentation, but I didn't have time to look into it yet. Apart from that, it should work okay and fix issues with retry handling as you mentioned.

**Comment by mre** [comment]
lychee version 0.14.0 finally got released. 🎉
Thanks to this release, the issue should be resolved now.
Please reopen if this is not the case, and apologies for the long delay.
