### ISSUE TITLE
Nightly tag is missing pre-builts binaries

### ISSUE THREAD

**Issue by guimochila** [lycheeverse/lychee#1323]
Hi 👋 !

I have been using the nightly version with pre-built binaries and I can see the builds from the nightly version isn't there any more. It is now only available via the source code?

Thank you.

**Comment by ArkadiuszSkalski-TomTom** [comment]
@mre Could you please take a look?
I would not mind to get a regular release using latest features ;-)

The mainline has important fixes and features many people are waiting for them for a long time already. If this issue remains stale for longer I believe people will just fork out from this repo.

**Comment by askalski85** [comment]
@mre Could you please take a look?
I would not mind to get a regular release using latest features ;-)

The mainline has important fixes and features many people are waiting for them for a long time already. If this issue remains stale for longer I believe people will just fork out from this repo.

**Comment by mre** [comment]
Sorry for the delay. Busy times. There will be a new release tomorrow. 😇

**Comment by mre** [comment]
Thanks to the pull request by @askalski85 in https://github.com/lycheeverse/lychee/pull/1330, this is resolved. 🥳 

On top of that, lychee version 0.14.0 finally got released. 🎉 
Thanks to this release, all fixes be in the latest release now.
Please reopen if this is not the case, and apologies for the long delay.
