### ISSUE TITLE
--accept says "invalid digit found in string" for documentation example

### ISSUE THREAD

**Issue by koppor** [lycheeverse/lychee#1329]
The documentation says:

> Use "lychee --accept '200..=204, 429, 500' <inputs>..." to provide a comma-separated list [...]

https://github.com/lycheeverse/lychee/blob/f3ac86acbd09df849cbad0090f19b30f346474f3/README.md?plain=1#L398

When executing that, I get "invalid digit found in string"

```cmd
>lychee --accept '200..=204, 429, 500'
error: invalid value ''200..=204,' for '--accept <ACCEPT>': invalid digit found in string
```

    lychee 0.13.0

I tried some variants:

- Does not work: `lychee --accept '200' https://www.example.org`
- Works: `lychee --accept "200" https://www.example.org`
- Does not work: `lychee --accept "200..=204" https://www.example.org`

Last working lychee version was 0.10.0. Beginning with 0.10.1 the aforementioned syntax does not work.

---

Maybe, "just" a new release has to be made, because it seems PR https://github.com/lycheeverse/lychee/pull/1167 is not release. I cannot build a binary for myself, because of https://github.com/microsoft/vcpkg/issues/35949#issuecomment-1875269123.

**Comment by mre** [comment]
> Maybe, "just" a new release has to be made

Yes, I think so. There will be a new release tomorrow.

**Comment by mre** [comment]
lychee version 0.14.0 finally got released. 🎉 
Thanks to this release, the issue should be resolved now.
Please reopen if this is not the case and apologies for the long delay.

On top of that, the error message for TOML parsing errors is more extensive now, which should help with troubleshooting.
