### ISSUE TITLE
Read .gitignore

### ISSUE THREAD

**Issue by Ekleog-NEAR** [lycheeverse/lychee#1331]
Currently, lychee has its own `.lycheeignore` format.

It’d be very nice if it could read the `.gitignore`, in order to avoid having to duplicate all information there.

See also the discussion we had about our lychee usage at https://github.com/near/nearcore :)

**Comment by mre** [comment]
Currently, we use [`jwalk`](https://github.com/Byron/jwalk) for file traversal, which has limited support for `.gitignore` files.
@Byron, is that correct? Should I create an issue to add `.gitignore` support to `jwalk`?
Alternatively, how hard would it be to add `.gitignore` support to lychee with `jwalk`?

There's also [`walkdir`](https://github.com/BurntSushi/walkdir), which has `.gitignore` support.

**Comment by Byron** [comment]
> There's also [`walkdir`](https://github.com/BurntSushi/walkdir), which has `.gitignore` support.

Can it be that you mean the [`ignore`](https://crates.io/crates/ignore) crate? I just checked and `walkdir` definitely doesn't have `.gitignore` support or hides it from prying eyes.

If I were you, I'd probably try to use the `ignore` crate on the largest input I have and see if the performance is acceptable.

> Should I create an issue to add `.gitignore` support to `jwalk`?
> Alternatively, how hard would it be to add `.gitignore` support to lychee with `jwalk`?

You can create an issue but I wouldn't implement it for the sole reason that it wouldn't be a quick & fun thing for me to do - I didn't write `jwalk` and I am glad it's still working 😅. Thus it might be easier to [use `gix` for that](https://docs.rs/gix/latest/gix/struct.Repository.html#method.excludes), probably after checking if a directory contains a repository, [this code does exactly that](https://github.com/Byron/gitoxide/blob/f1b33ba7518881adfe31a03c366000e1a6e0d7d4/gitoxide-core/src/organize.rs#L31) - you'd definitely want to avoid to call [`gix::open(…)`](https://docs.rs/gix/latest/gix/fn.open.html) on any directory you encounter.

Once a repo is available and paths within the repo are traversed, you should be able to [prime the `AttributeStack`](https://docs.rs/gix/latest/gix/struct.AttributeStack.html#method.at_path) to the path at hand and then [check if it's excluded()](https://docs.rs/gix/latest/gix/worktree/stack/struct.Platform.html#method.is_excluded).

I hope that helps.

**Comment by mre** [comment]
@thomas-zahner fixed this. 🎉
