### ISSUE TITLE
Feature request: ignore all links between specific section/lines of a file

### ISSUE THREAD

**Issue by agriyakhetarpal** [lycheeverse/lychee#1384]
## Feature description

Hi! I was wondering if Lychee can be configured to ignore a specific set of links between two comments of a file, or with in-line comments in a file. For example, I can put out comments in a Markdown file with (`<!-- -->`) or in Python files with (`#`), and so on – and Lychee would not parse those links at all.

## Motivation

Many links in many files are flaky, and it is not viable to ignore a file completely sometimes – where ignoring all links present between a specific section of a file would be great for CI when using the Lychee action (while also keeping the error on failure input).

## Example and proposed solution

This may vary based on different file formats and how comments work for them, but here's an exhibit for a Markdown (`.md`) file:

```markdown
[Link 1](https://google.com)

<!-- lychee: linkcheck stop -->

[Link 2](https://amazon.com)
[Link 3](https://twitter.com)
[Link 4](https://github.com)

<!-- lychee: linkcheck start -->

[Link 5](https://youtube.com)
[Link 6](https://github.com/lycheeverse/lychee) <!-- pragma: no linkcheck -->
```

would disable checking Link 2, Link 3, and Link 4, and also Link 6.

## Additional context

I was unable to find a feature or a flag that can provide the requested functionality, but there is always a chance I may have overlooked in the case that there is one. The semantics of what the comment-based indicators can be can be discussed, but I would suppose it helps to have something that provides a start-stop sign between lines of files, and not just an in-line comment after a link (which would make it cumbersome to mark multiple links with that).

**Comment by mre** [comment]
Hmm... intriguing!

I'm not 100% sure that I would add that feature to lychee, but there is a workaround you can use today.
Here is a script that I call `lychee_skip`, which does just that with `awk`:

```sh
#!/bin/bash

# Ensuring that the script exits on the first error
set -eo pipefail

# Check if at least one argument is passed
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <file>"
    exit 1
fi

FILE="$1"

# Using awk to:
# 1. Exclude lines between 'linkcheck stop' and 'linkcheck start' markers.
# 2. Exclude lines ending with 'pragma: no linkcheck'.
awk '
/<!-- lychee: linkcheck stop -->/,/<!-- lychee: linkcheck start -->/{next}
/<!-- pragma: no linkcheck -->$/ {next}
1
' "$FILE"
```

You can add your own delimiters for different files etc.

```sh
❯❯❯ cat input_file.md                                                                                                                                                                 ✘
[Link 1](https://google.com)

<!-- lychee: linkcheck stop -->

[Link 2](https://amazon.com)
[Link 3](https://twitter.com)
[Link 4](https://github.com)

<!-- lychee: linkcheck start -->

[Link 5](https://youtube.com)
[Link 6](https://github.com/lycheeverse/lychee) <!-- pragma: no linkcheck -->
```

```sh
❯❯❯ cat input_file.md | ./lychee_skip.sh -
[Link 1](https://google.com)


[Link 5](https://youtube.com)
```

Then you can pipe that to lychee.

```
❯❯❯ cat input_file.md | ./lychee_skip.sh - | lychee -
```

Alternatively, if you prefer a Rust solution:

```rust
use std::env;
use std::fs::File;
use std::io::{self, BufRead, BufReader};

fn main() -> io::Result<()> {
    let args: Vec<String> = env::args().collect();
    if args.len() < 2 {
        eprintln!("Usage: {} <file>", args[0]);
        std::process::exit(1);
    }

    let filename = &args[1];
    let file = File::open(filename)?;
    let reader = BufReader::new(file);

    let mut skip_section = false;
    for line in reader.lines() {
        let line = line?;
        if line.contains("<!-- lychee: linkcheck stop -->") {
            skip_section = true;
            continue;
        }
        if line.contains("<!-- lychee: linkcheck start -->") {
            skip_section = false;
            continue;
        }
        if skip_section || line.ends_with("<!-- pragma: no linkcheck -->") {
            continue;
        }

        println!("{}", line);
    }

    Ok(())
}
```

Of course, it could be extended to support more file formats and custom delimiters.

Perhaps you could maintain that in a separate repo for now to see if there's any interest.
I'd be happy to mention the project in the `README.md` if you like. What do you think? 😃

**Comment by mre** [comment]
Glad to hear that this works for now. I'll close this, but if people find it in the future and would like to have that functionality in lychee itself, we can talk about that.
