### ISSUE TITLE
Issues checking anchors/fragments in markdown files

### ISSUE THREAD

**Issue by f-hollow** [lycheeverse/lychee#1425]
The README [claims](https://github.com/lycheeverse/lychee?tab=readme-ov-file#features) that `lychee` supports `Anchors/Fragments`.

My `README.md` is as follows:

```markdown
# Test lychee

## Anchor

This is a section I am trying to link to.

## Another section

You can find the _Anchor_ section [here](#ancho).
```

Running `lychee` on this `README.md` returns this:

```console
$ lychee README.md 
  1/1 ━━━━━━━━━━━━━━━━━━━━ Finished extracting links
🔍 1 Total (in 0s) ✅ 1 OK 🚫 0 Errors
```

Apparently, the link `[here](#ancho)` is faulty. The correct link would be `[here](#anchor)`.

Am I doing anything wrong?

I look forward to successfully resolving this issue as I really need a tool that can check markdown anchors for issues like given above.

**Comment by mre** [comment]
Can you try this?
```
lychee --include-fragments README.md
```

**Comment by f-hollow** [comment]
Ah, sorry! I assumed all the features listed in the table would work out of the box.

Now the link checking works perfectly. Exactly what I was looking for!

It might be worthwhile to add in the Features section that some features are disabled by default and can be activated using respective command-line arguments. But that's up to you.

Then I will close this issue. Thank you!

**Comment by mre** [comment]
True. The question is how to phrase it or where to put the description to avoid confusing the reader.
Perhaps we could mention it in the lychee docs (https://lychee.cli.rs/) somewhere. Pull requests welcome in case you have an idea. The repo is here: https://github.com/lycheeverse/lycheeverse.github.io

In the meantime, I'm happy that this resolved your problem.

**Comment by mre** [comment]
I've added some documentation about anchor links here: https://lychee.cli.rs/recipes/anchors/.
