### ISSUE TITLE
Converting Uri to Url string

### ISSUE THREAD

**Issue by thomas-zahner** [lycheeverse/lychee#1436]
I have a use-case where I need to convert lychee's `Uri` into a string. In this use-case I send the converted string to some web-browser and would like to simply use `new Url(stringConvertedFromLycheesUri)`. So I'd like to get a string which is a valid `Url` which I would expect to be simple since the `Uri` struct just wraps a `Url`.

However, the implementation currently looks as follows:

```rust
impl Uri {
    /// Returns the string representation of the `Uri`.
    ///
    /// If it's an email address, returns the string with scheme stripped.
    /// Otherwise returns the string as-is.
    #[inline]
    #[must_use]
    pub fn as_str(&self) -> &str {
        self.url.as_ref().trim_start_matches("mailto:")
    }
}
```

This implementation is then also used for `AsRef<str>` and `Display`.
So in my use-case I need to do the following to get a back a valid URL string:

```rust
match uri.scheme() {
    "mailto" => format!("mailto:{}", uri.as_str()),
    _ => uri.to_string(),
}
```

Could we update the implementation so that we have a possibility to get the URL string directly? Maybe this should also be the default behaviour and the `mailto` should only be trimmed in a special method?

**Comment by mre** [comment]
Sure, good idea. Will you create a PR?

**Comment by thomas-zahner** [comment]
Ok awesome, will do :+1:
