### ISSUE TITLE
Optionally: Collect all URLs and deduplicate them?

### ISSUE THREAD

**Issue by rauschma** [lycheeverse/lychee#1452]
Rationale: If a website has the same broken link on many of its pages (e.g. in its header or footer) then you get a lot of noise.

**Comment by mre** [comment]
We already do that per file. For multiple files, we cache the result, so we don't check the same link twice.
So, essentially, we already deduplicate the links.
We could deduplicate the output maybe, but I'm not sure if it's worth the additional complexity. Is there anything in particular that we're missing apart from that?

**Comment by rauschma** [comment]
That’s already pretty good, thanks! Output deduplication would be nice to have but it’s not really that urgent then.

**Comment by mre** [comment]
Yup. I'll go ahead and close this one then.

One more note on the output: you can use `lychee --dump` to get the full list of links across all inputs. This list can be sorted or redirected to a file. This way you can sort of build that URL-centric view already. On top of that, you can use it as input for the next run. Then it will be deduplicated from the get go. So 

```sh
lychee --dump | sort | uniq > links.txt

# Later...
lychee links.txt
```
