### ISSUE TITLE
URL reference to other Markdown treated as E-Mail check

### ISSUE THREAD

**Issue by joesan** [lycheeverse/lychee#146]
I'm having a Markdown in which I refer to other Markdown files using the @ notation. For example., to link to another Markdown, I use 

`[please have a look here](@/posts/some/path/mk.md)`

When I run it through the action, the above gets checked as E-Mail. Is there a way to ignore such links or to interpret it as a link instead of an E-Mail?

**Comment by mre** [comment]
If you want to exclude those links while still checking mail addresses, you can try 
```
--exclude '@/posts'
```

(Have not tested that, but it's probably close to what you want.)

If you want to skip all mail addresses from getting checked, try 

```
--exclude-mail          
```

**Comment by mre** [comment]
That said, I'm not sure if these links should be detected at all. The `@` in front of a path is a common pattern in static site generators, so I wonder if we should treat them as differently, e.g. as relative URLs by stripping away the `@/` and applying `base-url` if set.

**Comment by joesan** [comment]
I was thinking about that as excluding them might not be a good idea as these are indeed valid HTTP links pointing to other Markdown files. So I like your second approach where you check them by prepending a base-url if set, if not check for the file in the same location.

**Comment by mre** [comment]
Cool, agreed. Will see what I can do.

**Comment by joesan** [comment]
Could you post a reference to the source file that I should look at? I might try to get this implemented!

**Comment by mre** [comment]
Oh that would be cool. Guess you could start by adding your snippet from above as a test right below this one:
https://github.com/lycheeverse/lychee/blob/ae2d02b8a0bb5e186478c5cf6a2d1ecad0c5ac64/src/extract.rs#L263-L268
Then you'd have to follow the trail and see where it fails.

**Comment by mre** [comment]
And this here needs to be adjusted to check for '@/':
https://github.com/lycheeverse/lychee/blob/ae2d02b8a0bb5e186478c5cf6a2d1ecad0c5ac64/src/uri.rs#L53-L55

Maybe this will also be relevant:
https://github.com/robinst/linkify/pull/8#issuecomment-778605835
linkify only allows URLs with a schema at the moment. They are looking for help to push schema-less URLs over the finishing line.

**Comment by joesan** [comment]
Fixed in PR https://github.com/lycheeverse/lychee/pull/150
