### ISSUE TITLE
Support URL Encoded Anchors

### ISSUE THREAD

**Issue by Silvenga** [lycheeverse/lychee#1467]
It appears that lychee assumes a different behavior from browsers regarding URL encoded anchors.

Given an anchor, such as `#tangent%3A-kustomize`, targeting the element `id="tangent%3A-kustomize"` lychee fails with `Failed: Cannot find fragment`. This appears to only occur with anchors that are URL encoded. Oddly, this only happens when processing local files, and not remote files:

```bash
.\lychee -v --include-fragments "dist\posts\helm-and-gitops\index.html"

✗ [ERR] file:///C:/Users/.../dist/posts/helm-and-gitops/index.html#tangent%3A-kustomize | Failed: Cannot find fragment
```

```
.\lychee -v --include-fragments https://silvenga.com/posts/helm-and-gitops

✔ [200] https://silvenga.com/#tangent%3A-kustomize
```

Although, I think that URL is incorrect - it should be `https://silvenga.com/posts/helm-and-gitops#tangent%3A-kustomize`.

Double checking with browsers, both Firefox and Chromium-based browsers appear to support URL encoded anchors.

**Comment by andreySadomovskiy** [comment]
Have the same issue, but with `%e2%80%99` symbol.

**Comment by mre** [comment]
If someone wants to tackle this, here's what to do.

## Bug Summary
Lychee fails to handle URL-encoded anchors in local files.

## Reproduction Steps
1. Create test.html:
```bash
cat << EOF > test.html
<html>
    <body>
        <a href="#tangent%3A-kustomize">test</a>
        <h1 id="tangent%3A-kustomize">Test Header</h1>
    </body>
</html>
EOF
```

2. Run Lychee:
```bash
lychee -v --include-fragments test.html
```

Expected: Link is valid
Actual: Error - "Cannot find fragment"

## Fix
Update lychee to properly decode URL-encoded anchors in local files.
