### ISSUE TITLE
`https://www.gnu.org/` fail with "Too Many Requests"

### ISSUE THREAD

**Issue by 6543** [lycheeverse/lychee#1504]
```file=wow.html
fail:

 https://www.gnu.org/software/make/
 https://www.gnu.org
 https://gnu.org
```

lychee reports them as failed but curl (` curl -I https://www.gnu.org`) just report them as working:

![image](https://github.com/user-attachments/assets/0ebc93d2-c4eb-4ceb-aa71-64f6e6b2d38d)
![image](https://github.com/user-attachments/assets/bc430a9b-8212-4c60-a8ae-884bc1ba4958)

lychee 0.15.1

**Comment by thomas-zahner** [comment]
gnu.org responds with the status code `429 Too Many Requests` which means that you are being rate limited. Unfortunately, this can happen when you send too many requests to a webpage. So this is not a bug by lychee as everything is reported as expected. However, there are ways to mitigate the problem as documented on: https://lychee.cli.rs/troubleshooting/rate-limits/

**Comment by 6543** [comment]
no the problem is that if i use curl afterwards (same system) it is totally fine!!!

**Comment by 6543** [comment]
to reproduce:

run lychee first, then check with curl it still works

**Comment by mre** [comment]
Can you print the verbose output?

```sh
lychee -vvv https://www.gnu.org
```

Also, can you try to set a different user agent with `-u`? Try to set it to curl. The link that @thomas-zahner posted contains some more info on how to do that.

**Comment by mre** [comment]
Actually, here's the link, which describes how to set the user agent: https://lychee.cli.rs/troubleshooting/network-errors/

**Comment by 6543** [comment]
yes setting the useragent to curl works ... that's just stupid :/

but nothing you can fix ...

**Comment by 6543** [comment]
still do you have a hardcode list/heuristic where to fake the user agent, and those could add gnu ?

**Comment by mre** [comment]
We don't. I also don't think it would help much as the number of pages with such checks in place is shockingly large and growing. However, setting the user agent to curl for all links is probably fine. We just don't do it by default as we'd like to be good citizens of the web.

**Comment by 6543** [comment]
Thanks :)
