### ISSUE TITLE
Documentation for headers in TOML

### ISSUE THREAD

**Issue by devin-purple** [lycheeverse/lychee#1507]
The CLI argument works (`--header "Host=something.com"`)

I cannot find anywhere in the documentation that shows how to put this into the `lychee.toml`

In the [example](https://lychee.cli.rs/usage/config/) it just shows `headers = []` which is not helpful.

**Comment by mre** [comment]
Have you tried this?

```toml
headers = ["Host=something.com"]
```

**Comment by mre** [comment]
You might be running into https://github.com/lycheeverse/lychee/issues/1441#issuecomment-2170424574

**Comment by devin-purple** [comment]
I've tried `headers = ["Host=asldkfjasldfkj.com"]`  in .toml, does not seem to work. I should get all 400s with a bad hostname.

Maybe related to #1441, I am reading a list of links from a local file and sending a custom header.

**Comment by mre** [comment]
I'm beginning to think header parsing from the config is broken. Maybe it never worked.

**Comment by cc-stjm** [comment]
I've just come across this - I think you have to specify

```
header = ["foo=bar"]
```
in the .toml

the documentation has
```
headers= ["foo=bar"]
```

(Note plural)

**Comment by mre** [comment]
Aha! Thanks for the feedback. Would you like to open a pull request to fix the documentation?
