### ISSUE TITLE
Nightly release not updated since 9th of August

### ISSUE THREAD

**Issue by sebastiaanspeck** [lycheeverse/lychee#1515]
The nightly release hasn’t been updated since the 10th of August. Could this be fixed?

**Comment by mre** [comment]
Hm, you're right. Not sure what happened there. Maybe the token expired? 🤔 I'll check.

**Comment by mre** [comment]
Updated the token and triggered the nightly pipeline again. It's green, and the binaries showed up again.
My hope is that it's fixed.

**Comment by mre** [comment]
Thanks for the hint, Sebastian. 😊
