### ISSUE TITLE
Setting the `format` flag within a custom `lychee.toml` config file does not work

### ISSUE THREAD

**Issue by afalhambra-hivemq** [lycheeverse/lychee#1533]
Hello,
I'm just trying to see if I can define the format inside my custom `lychee.toml` config file, but I found a couple of issues:

With the following config

```toml
format = "json"
```

I get the following error message:
```bash
   [ERROR] Error while loading config: Cannot load configuration file `./lychee.toml`: Failed to parse configuration file

Caused by:
    TOML parse error at line 38, column 10
       |
    38 | format = "json"
       |          ^^^^^^
    unknown variant `json`, expected one of `Compact`, `Detailed`, `Json`, `Markdown`, `Raw`
```

So then, I decided to change from `json` to `Json`, but it does not work and the output is shown in the default format `compact`.

**Comment by mre** [comment]
Nice catch! It's fixed in `master` now. Stay tuned for the next release. 😊
