### ISSUE TITLE
404 when checking youtube-nocookie url

### ISSUE THREAD

**Issue by mattr-rsolomon** [lycheeverse/lychee#1562]
Hi, 
Youtube links in [no cookie url](https://support.google.com/youtube/answer/171780?hl=en#zippy=%2Cturn-on-privacy-enhanced-mode) form are returning 404. I understand from the previous Youtube related issues that Youtube URLs have their quirks, but wanted to ask if there is a way to properly handle youtube no-cookie URLs ?

thank you 🙌

```
<!-- testfile.html -->
<html>
  <body>
    <div>
      <iframe src="https://www.youtube-nocookie.com/embed/BIguvia6AvM" id="widget2"></iframe>
      <iframe src="https://www.youtube.com/watch?v=BIguvia6AvM"></iframe>
    </div>
  </body>
</html>
```

```
lychee --version
lychee 0.17.0

lychee ./testfile.html --verbose
     [404] https://www.youtube-nocookie.com/embed/BIguvia6AvM
     [200] https://www.youtube.com/watch?v=BIguvia6AvM
```

**Comment by mre** [comment]
Thanks, yeah, that's a bug.
We also don't handle `/embed/` URLs as well, so that's two bugs. 😆

**Comment by mre** [comment]
Should be fixed; thanks for reporting!

**Comment by mattr-rsolomon** [comment]
that was quick! thank you for resolving the issue!!
