### ISSUE TITLE
Is the format of `.lycheecache` stable?

### ISSUE THREAD

**Issue by wiktor-k** [lycheeverse/lychee#1567]
Hi,

Thanks for your great project!

I'd like to use `.lycheecache` as an input to my blogging system (to show info such as "as of [date]" as used in academic world) and would like to know if the file format is stable.

Thanks for your time! :wave:

**Comment by mre** [comment]
Interesting use-case! I wouldn't want to make any stability guarantees, but I also don't see it changing in the foreseeable future. At the end, it's just a CSV file with comment support (lines with `#` at the start). If we add fields, then likely at the end, but I wouldn't even know what to add there.

In summary, it's probably safe to use.
