### ISSUE TITLE
xml namespace false positive http://www.w3.org/1999/xhtml

### ISSUE THREAD

**Issue by sethbattin** [lycheeverse/lychee#169]
I turned on lychee over a set of static content of..."mixed quality".  It started detecting a 404 for http://www.w3.org/1999/xhtml

Once upon I time I may have known what that meant immediately, but if so i had blacked it out.  So grep led me to this line in some poorly cultivated html:
```html
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
```

For everyone else who needs a reminder, this is a ["strictly confirming XHTML1" doctype declaration](https://www.w3.org/TR/xhtml1/#strict).  It's mostly pointless in the modern web, it literally is a 404, and the content should be updated.  However it is **not** an error.

Obviously workarounds are to use `--exclude www.w3.org`.  For my case, I downgraded my old document to non-conforming by deleting the xhtml nonsense.

I can't say whether this warrants a bugfix or some special-case in the code.  I don't even have an opinion about how validation of xml namespaces should work generally in this awesome utility.  I just wanted to call attention to this error in case it's easy to fix.

**Comment by mre** [comment]
Let me start by saying that I've rarely seen such a well-written issue description. Your command of the English language is excellent. 😃 
On the more technical side of things, we could add a set of "known false positives" &mdash; a blacklist of some sort. 
I'd implement it as a `RegexSet`, with patterns similar to the one you mentioned. We have to be careful not to be too restrictive, as [www.w3.org](https://www.w3.org/) resolves without issues for me. I'd opt for explicitness over implicitness in this case.
It should indeed be an easy fix; thanks for the suggestion.

**Comment by mre** [comment]
@sethbattin this should be fixed in `master` now.
