### ISSUE TITLE
relative broken links not detected

### ISSUE THREAD

**Issue by lenisha** [lycheeverse/lychee#183]
Relative Links in the github pages index.html are broken but not detected:

https://github.com/lenisha/linkchecker-test/runs/2122896789?check_suite_focus=true
```
+ lychee '--exclude=^(javascript|chrome):.*' --verbose --accept=200,403,429 --base-url https://lenisha.github.io/linkchecker-test/   https://lenisha.github.io/linkchecker-test/ --output /tmp/lychee/out.md
+ exit_code=0
+ '[' 0 -ne 0 ']'
+ cat /tmp/lychee/out.md
+ echo
+ echo ::set-output name=exit_code::0
📝 Summary
---------------------
🔍 Total...........17
✅ Successful......17
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........0
```

while  index.thml has broken link https://github.com/lenisha/linkchecker-test/blob/main/index.html#L53
```
<a class="nav-link pr-3" href="./abouterror.html">About</a>
```
that points to https://lenisha.github.io/linkchecker-test/abouterror.html

Could it be also checked locally? Similar to discussion #15

**Comment by lenisha** [comment]
@mre  is there any option to detect problems with relative links right now?
I tried to go against the live website with base-url
```
lychee '--exclude=^(javascript|chrome):.*' --verbose --base-url https://lenisha.github.io/linkchecker-test/   https://lenisha.github.io/linkchecker-test/ 
```

and tried against files files in PR
```
lychee  --exclude="^(javascript|chrome):.*"   --accept=200,403,429 "**/*.md" "**/*.html"
```

non have found the simple error
```
<a class="nav-link pr-3" href="./abouterror.html">About</a>
```

**Comment by pawroman** [comment]
> @mre is there any option to detect problems with relative links right now?

There should be, once https://github.com/lycheeverse/lychee/pull/99 is merged. Right now, link-parsing debugging is a bit cumbersome (e.g. you have to modify the source).

**Comment by mre** [comment]
No clue why it doesn't find the relative links, though. @pawroman do you know why?

**Comment by lenisha** [comment]
weird thing is when I explicitly point to index.html page it finds it
```
lychee --verbose '--exclude=^(javascript|chrome):.*' --accept=200,403,429 --base-url https://lenisha.github.io/linkchecker-test/ https://lenisha.github.io/linkchecker-test/index.html --output /tmp/lychee/out.md
+ exit_code=2
+ '[' 2 -ne 0 ']'
++ dirname lychee/out.md
+ mkdir -p lychee
+ echo 'Errors were reported while checking the availability of links.'
+ echo
+ echo '```'
+ echo
+ cat /tmp/lychee/out.md
+ echo
📝 Summary
+ echo '```'
+ echo
+ echo '[Full Github Actions output](https://github.com/lenisha/linkchecker-test/actions/runs/662263907?check_suite_focus=true)'
+ cat /tmp/lychee/out.md
+ echo
+ echo ::set-output name=exit_code::2
---------------------
🔍 Total...........28
✅ Successful......27
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........1

Errors in https://lenisha.github.io/linkchecker-test/index.html
✗ https://lenisha.github.io/linkchecker-test/abouterror.html [404 Not Found]
```

**Comment by mre** [comment]
After thinking about this some more I think I know what's up:
The `html`  file extension triggers the HTML mode in lychee. URLs without any file extensions get treated as plaintext, in which case relative URLs don't exist (currently at least).
We can probably safely assume that a URL returns HTML by default, so we have to change the condition here to return `FileType::HTML` by default if there is no extension:

https://github.com/lycheeverse/lychee/blob/ae2d02b8a0bb5e186478c5cf6a2d1ecad0c5ac64/src/collector.rs#L141

**Comment by mre** [comment]
@lenisha, this is fixed in `master` now. Will publish a new version of the lychee-action (1.0.7) shortly.
