### ISSUE TITLE
Consider adding support for image, audio and video links - <img>, <audio> and <video> HTML tags src parameter

### ISSUE THREAD

**Issue by frederickjh** [lycheeverse/lychee#190]
Please consider adding support for links to images, audio and videos. The `<img>`, `<audio>` and `<video>` HTML tags all have the **src** parameter with the link to the source file.

**Comment by mre** [comment]
These should work already:

foo.html:

```
<img src="https://endler.dev/2021/codeprints/tweet_felix.avif" />
<audio src="horse.ogg" controls>
<video width="320" height="240" controls>
  <source src="movie.mp4" type="video/mp4">
  <source src="movie.ogg" type="video/ogg">
  Your browser does not support the video tag.
</video>
```

```
lychee --verbose foo.html --base-url https://endler.dev
✔ https://endler.dev/2021/codeprints/tweet_felix.avif [200 OK]
✗ https://endler.dev/horse.ogg (404 Not Found)
✗ https://endler.dev/movie.ogg (404 Not Found)
✗ https://endler.dev/movie.mp4 (404 Not Found)

📝 Summary
---------------------
🔍 Total............4
✅ Successful.......1
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........3
```

The current limitation is that you have to use a HTML file for that. If you check a website it won't work right now because of #15, which will be fixed soon.

**Comment by mre** [comment]
This should be fixed in `master`. Can you check again @frederickjh?

**Comment by mre** [comment]
Closing this to keep the issue tracker clean. Feel free to reopen if you still run into issues. 😃

**Comment by mre** [comment]
Great success! 🥳
