### ISSUE TITLE
Feature request: Check usage of HTTP when HTTPS is available

### ISSUE THREAD

**Issue by lebensterben** [lycheeverse/lychee#192]
Often time I'd prefer to use HTTPS urls when it's available, and gets an warning if I didn't use HTTP instead.

It seems that there's no such functionality currently, and it'd be great if users can opt-in for this feature.

**Comment by mre** [comment]
So you if we find a HTTP link, we check if a corresponding HTTPS link exists and if so, we print a warning? Perhaps in combination with an optional flag `--prefer-https` or so? 
Is that what you meant?

**Comment by lebensterben** [comment]
@mre 
Yes exactly!

**Comment by mre** [comment]
Okay sounds good. Any takers?

**Comment by lebensterben** [comment]
@mre Let me take a try. I will come back if I need any help.
