### ISSUE TITLE
Silently ignore unsupported schemes

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#199]
URL schemes like `slack://` or `file://` are not supported, because reqwest doesn't support them.
Nevertheless, they show up as errors in the output, e.g.

```
✗ slack://user?team=acme&id=user (builder error for url (slack://user?team=acme&id=user): URL scheme is not allowed)
```

We should silently skip those. 
This is not as easy as it sounds.

First I thought about implementing a condition in `extract.rs`:

```rust
for link in links {
        match Uri::try_from(link.as_str()) {
            Ok(uri) if accepted_scheme(&uri) => {
                requests.insert(Request::new(uri, input_content.input.clone()));
            }
            Ok(uri) => {
                info!(
                    "Scheme {} in url {} is not supported at the moment",
                    uri.scheme(),
                    link
                );
            }
            //...
```

where `accepted_scheme` was something like

```rust
// Only a limited set of schemes is accepted at the moment
fn accepted_scheme(uri: &Uri) -> bool {
    match uri.scheme() {
        None => false,
        Some(scheme) => return scheme == "http" || scheme == "https",
    }
}
```

This is not ideal, because we'd have to maintain the list of supported schemes ourselves. If reqwests adds support for `file://` for example, we'd have to add it here (after having to find out that it's supported now).

A more robust way is to work with the response of the reqwest builder here:

https://github.com/lycheeverse/lychee/blob/bcb3933b224175088812823c8d4dd7c09f7395a1/src/client.rs#L249-L256

We could check if the returned error is of kind `builder` (see https://docs.rs/reqwest/0.11.2/reqwest/struct.Error.html#method.is_builder).
Then we could return a new `Status::Unsupported` or something, which would indicate that the request currently cannot be handled. 

Pseudocode:

```rust
 let request = match self 
     .reqwest_client 
     .request(self.method.clone(), url.to_owned()) 
     .build() 
 { 
     Ok(r) => r, 
     Err(e) if e.is_builder() => return Status::Unsupported(e),
     Err(e) => return e.into(), 
 }; 
```

Then in the final stats report we could decide if we want to show the count of unsupported links or not.

Open for alternative ideas.

**Comment by MichaIng** [comment]
Many thanks, I just recognised this and am looking forward for the next release to contain this fix 👍.
