### ISSUE TITLE
`http://security.debian.org/debian-security|deb` is recognized as a URI

### ISSUE THREAD

**Issue by spacewander** [lycheeverse/lychee#210]
When I use lychee (version 0.5.0) to check our project, I find that some text is recognized as a URI by mistake.

For example, `sed -i 's|^deb http://security.debian.org/debian-security|deb http://mirrors.huaweicloud.com/debian-security|g' /etc/apt/sources.list` is recognized as two URI: `http://security.debian.org/debian-security|deb` and `http://mirrors.huaweicloud.com/debian-security|g`.

Since `|` is not a valid URI character, I think it is a bug. Is it fixed in the master branch?

**Comment by mre** [comment]
Hey @spacewander,
we use linkify for parsing URLs from plaintext. I opened a pull request over there.
https://github.com/robinst/linkify/pull/19

**Comment by mre** [comment]
@spacewander, the changes were merged into `master` now. Can you try again by compiling the latest `master`?

**Comment by spacewander** [comment]
solved
