### ISSUE TITLE
Some YouTube links are reported as `401 Unauthorized` error due to `oembed` API limitation

### ISSUE THREAD

**Issue by micalevisk** [lycheeverse/lychee#214]
Hi! I didn't understand why `https://www.youtube.com/watch?v=MCs5OvhV9S4` is reported as `401` instead of `200` :confused: The same for `https://www.youtube.com/watch?v=iHVs_HkjdmI`

```bash
$ curl -I https://www.youtube.com/watch?v=MCs5OvhV9S4
HTTP/2 200 
content-type: text/html; charset=utf-8
x-content-type-options: nosniff
cache-control: no-cache, no-store, max-age=0, must-revalidate
pragma: no-cache
expires: Mon, 01 Jan 1990 00:00:00 GMT
date: Sun, 11 Apr 2021 20:15:08 GMT
content-length: 435464
x-frame-options: SAMEORIGIN
strict-transport-security: max-age=31536000
p3p: CP="This is not a P3P policy! See http://support.google.com/accounts/answer/151657?hl=pt-BR for more info."
server: ESF
x-xss-protection: 0
```

### steps to reproduce

```bash
$ echo "https://www.youtube.com/watch?v=MCs5OvhV9S4" > foo
$ lychee --no-progress foo
✗ https://www.youtube.com/watch?v=MCs5OvhV9S4 (401 Unauthorized)
📝 Summary
---------------------
🔍 Total............1
✅ Successful.......0
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........1

Errors in foo
✗ https://www.youtube.com/watch?v=MCs5OvhV9S4 (401 Unauthorized)
```

---

edit:  
related to https://github.com/humhub/humhub/issues/2501

**Comment by mre** [comment]
Hi, guess it's because the YouTube video in question is not embeddable.
https://stackoverflow.com/a/5655148/270334.
This is a bug indeed, but we'd have to find a way to check these as neither oembed nor the YouTube link directly returns a proper status code.

**Comment by mre** [comment]
These links could be skipped a la https://github.com/humhub/humhub/pull/2502/files, but maybe there is another way to check them.

**Comment by micalevisk** [comment]
you're right because `curl -I https://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=MCs5OvhV9S4` do return `401`.

https://github.com/lycheeverse/lychee/blob/33e952b428c165aa55f3eee133555c9d53b469aa/src/quirks/mod.rs#L50

What I didn't is why `lycheeverse` can't just do a "normal" request (a direct to the target URL) http request as a fallback (or "retry") to `401` responses to YouTube links. Would you mind explaining it for me (a non-rust user)?

**Comment by mre** [comment]
Normal requests to non-existing videos don't return the expected status code.

```
curl -I 'https://www.youtube.com/watch?v=thatsnotavalidvideo'
HTTP/2 200
```

The page exists, but the video does not. Nevertheless it returns a 200 OK.
I'd bet that most link checkers get this wrong.

**Comment by mre** [comment]
Two alternatives I found on https://stackoverflow.com/questions/1383073/how-do-i-check-if-a-video-exists-on-youtube-using-php:

We could use the new V3 of the YouTube API:
```
https://www.googleapis.com/youtube/v3/videos?id={the_id_of_the_video}&key={your_api_key}&part={parts}
```

This requires an API key, though, which not every user will have.
Alternatively, we can check for the video thumbnail:

```
curl -I 'https://img.youtube.com/vi/iHVs_HkjdmI/0.jpg'
HTTP/2 200
```

I don't know if there will be cases where a video thumbnail doesn't exist, though. Otherwise that sounds like a fine alternative to oembed for me.
@pawroman any objections to using that?

**Comment by micalevisk** [comment]
thanks @mre! The second one sounds good to me. Since youtube is all about thumbnails, I'm pretty sure that this approach can be used.

When you release an alfta version let me know (by closing this issue) so then I will test it with this repo: https://github.com/jwasham/coding-interview-university (there's a ton of youtube videos in there)

**Comment by micalevisk** [comment]
just to summarise what I've tested:

| video visibility |  `https://www.youtube.com/oembed` returns | `https://img.youtube.com/vi/{video_id}/0.jpg` returns |
|:--|:--|:--
public | `200` but `401` if isn't embeddable | `200`
unlisted | `200` but `401` if isn't embeddable | `200`
private  | `404` but `401` if isn't embeddable | `404`
partially blocked video | `200` but `401` if isn't embeddable | `200`
age-restricted | `200` but `401` if isn't embeddable | `200`

**Comment by mre** [comment]
Alrighty. Thanks for the investigation. I can't see any downside from using the thumbnails then. 😀

**Comment by mre** [comment]
You might want to link your research from the StackOverflow post [here](https://stackoverflow.com/a/60030459/270334)

**Comment by mre** [comment]
This should be fixed in `master` now.

**Comment by ikabod** [comment]
> I can't see any downside from using the thumbnails then.

Compared to the oembed method with json format, checking for the thumbnail needs much more bandwidth and of course a little bit more time.

Example:

https://www.youtube.com/oembed?url=https://www.youtube.com/watch?v=U0u3-2CGOMQ&format=json (884 Byte)

https://img.youtube.com/vi/U0u3-2CGOMQ/0.jpg (44,46 KByte)

I check about 150 videos per day and currently only 2 of them returns a 401 status with the oembed method.

If we calculate with an average bandwidth of 35 KByte for the thumbnail method and 900 Bytes for the oembed method in my case I have 5.25 MByte compared to 135 KByte.

For most users this may not be important, but may be for some it is.

So the best of both would be to check first with the oembed method and if it returns 401 check with thumbnail method again.

**Comment by mre** [comment]
We don't download the image (the request body) but stop after the response headers. So the overhead should be minimal.
