### ISSUE TITLE
Underscores in URLs sometimes break the (markdown?) link parser

### ISSUE THREAD

**Issue by buddhist-uni** [lycheeverse/lychee#253]
The following URLs in markdown files in my repo are being parsed incorrectly by v0.7.0:

| My URL | Is getting parsed as |
-----|----
| `https://upload.wikimedia.org/wikipedia/commons/6/6d/Arahats_-_Flickr_-_odako1.jpg` |  `https://upload.wikimedia.org/wikipedia/commons/6/6d/Arahats` |
| `https://upload.wikimedia.org/wikipedia/commons/e/ec/%28Above%29_sBed-byed_%28Gopaka%29%2C_holding_a_book%3B_Wellcome_V0018272_%28cropped%29.jpg` | `https://upload.wikimedia.org/wikipedia/commons/e/ec/%28Above%29_sBed-byed` |
`https://upload.wikimedia.org/wikipedia/commons/5/56/P5290155_%2814971680537%29.jpg` | `https://upload.wikimedia.org/wikipedia/commons/5/56/P5290155`
`https://upload.wikimedia.org/wikipedia/commons/5/54/Monks_in_Wat_Phra_Singh_-_Chiang_Mai.jpg` | `https://upload.wikimedia.org/wikipedia/commons/5/54/Monks_in_Wat_Phra_Singh`
`http://www.ahandfulofleaves.org/documents/The%20Buddhist%20Religion%20A%20Historical%20Introduction_%20Robinson.pdf` | `http://www.ahandfulofleaves.org/documents/The%20Buddhist%20Religion%20A%20Historical%20Introduction`
`http://www.karunabv.org/uploads/1/2/6/3/12630738/__applying_compassion_bbodhi_110312.mp3` | `http://www.karunabv.org/uploads/1/2/6/3/12630738/`
`http://www.karunabv.org/uploads/1/2/6/3/12630738/chanting-kbv__2_.pdf` | `http://www.karunabv.org/uploads/1/2/6/3/12630738/chanting-kbv__2`
`http://home.ubalt.edu/ntygfit/ai_01_pursuing_fame/ai_01_tell/jd_morality_.htm` | `http://home.ubalt.edu/ntygfit/ai_01_pursuing_fame/ai_01_tell/jd_morality`

**Comment by buddhist-uni** [comment]
Here is a simple markdown file which demonstrates the bug: [underscore_urls.md](https://github.com/lycheeverse/lychee/files/6531686/underscore_urls.md)

**Comment by mre** [comment]
Thanks for reporting @buddhist-uni.

The underscores (`_`) have a special meaning in Markdown and emphasize the enclosed text, so `_hello_` becomes  _hello_.
As a result, our Markdown parser emits separate events for the different sections of the URL:

`example.org/_hello_` would emit `MDEvent::Text("example.org")` and `MDEvent::Text("hello")` as individual events; so by the time the text reaches the link parser, it is already split up.

There are a few ways to solve the issue:
1. Use proper Markdown links. This should work: `[example](example.org/_hello_)`.
2. Use `txt` file extension: `underscore_urls.txt` will use our plaintext parser and work as expected.

We could also add a `--fuzzy` flag to lychee, which would always use the plaintext parser (no matter the file extension), but it sounds like a hack.

**Comment by lebensterben** [comment]
@mre 

Would underscore break reference link?

```markdown
[title][id]

[id]: www.example.com
```

**Comment by buddhist-uni** [comment]
Thanks for the reply!

I understand that _'s mean italics in Markdown, but not in the_middle_of strings: only _at the ends_ of words.

Here is one of those links, happily parsed correctly by GitHub Markdown:

- http://www.karunabv.org/uploads/1/2/6/3/12630738/chanting-kbv__2_.pdf

As far as I'm concerned, if you're parsing md in a way that's different from everyone else: that's a bug.

I'm using Jekyll with [front matter](https://jekyllrb.com/docs/front-matter/), so changing the extension is not possible nor is it feasible in this case to wrap the links in brackets/parentheses (as I'd then have to write a custom liquid tag to _undo_ that operation in the templates).

I agree that a fuzzy flag is a bit of a hack: why not just parse markdown the same way as everyone else?

**Comment by lebensterben** [comment]
@buddhist-uni 
I agree with @mre that you should use standard links, either inline links or reference links.
See https://spec.commonmark.org/0.29/

> As far as I'm concerned, if you're parsing md in a way that's different from everyone else: that's your bug, even if your way is technically compatible with the original spec.

No. What's incompatible is GitHub, or more specifically GFM.

The parsing is stricy complicated to common mark.

**Comment by lebensterben** [comment]
we'd provide an optional feature to support gfm via https://lib.rs/crates/comrak

this is not always desirable, so it should be optional.

**Comment by buddhist-uni** [comment]
> GitHub, or more specifically GFM

and Kramdown, which I'm using, and others.

In any case, since I'm not going to be the last person to use nonstandard markdown, a flag to turn off the markdown parser might be a good idea. :)

**Comment by buddhist-uni** [comment]
Yeah, the problem is that Jekyll's "markdown" files aren't really markdown (even though they have the `.md` extension): they're actually Kramdown files with Yaml/json (!) on top 😞 That yaml is where I'm storing most of my links, and that's the reason I can't just wrap them in brackets.

**Comment by lebensterben** [comment]
you can always generate HTML first and then check the links.

This is easier for both of us.

**Comment by buddhist-uni** [comment]
Yes: I have ways to get around this bug if you'd rather not fix it. It's your project. Perhaps you should add a "GitHub / Jekyll Markdown Files" column to your README chart with an ❌ if you're not planning on supporting them? 🤷‍♂️

But, I am curious what cases your md parser handles _correctly_ that the naive parser doesn't, because it occurs to me that the current behavior isn't even correct for CommonMark:

`https://site.with/a_surprise_.php` (not wrapped in link brackets): assuming our commonmark user _intended_ to italicize "surprise", they would probably hope that Lychee would check "https://site.with/asurprise.php", right? They certainly did not intend "https://site.with/a"

But yes I understand it's easier for both of us if I just go away and figure this out myself and stop trying to give unwanted feedback 😂

**Comment by buddhist-uni** [comment]
Looks fine to me: 
![FAA11ACE-F10A-43DD-B95D-AA2E477A8327](https://user-images.githubusercontent.com/61610173/119626150-1c2a2400-be35-11eb-976b-fab3f4bea1fb.jpeg)
Shouldn't the parser just toss the span tag? Why not just stick to actual links (<a> tags, etc)?

But anyway: this is why I can't "easily" Lychee my generated html

**Comment by lebensterben** [comment]
great question.

**Comment by mre** [comment]
> Why even bother trying to parse a <code> block?

Because nobody ever encountered that case and so there is no rule to exclude `<code>` blocks yet.

We could check the element type here and exclude codeblocks:
https://github.com/lycheeverse/lychee/blob/1865f7a309cba21af1c2d7e98e2ccaad0810c120/lychee-lib/src/extract.rs#L104-L108

**Comment by buddhist-uni** [comment]
> there is no rule to exclude <code> blocks yet

Now we're talking! 

That would fix it for me, though I'm afraid it might break other people who want to parse a code block? 

Perhaps a runtime flag: `--exclude-tag=code` could let users specify any tag types they want to skip? Like `--exclude-tag=script` might be popular too.

In the (distant) future, that option might even be extended to support `--exclude-tag=#id` and `--exclude-tag=.class`. What do you think? 🙂

**Comment by mre** [comment]
Mixed feelings.

This would surely allow fine-grained control over lychee's behavior.
On the other hand, users have to be aware of the underlying issue first and then know about the parameter, which can resolve it.

The entire parsing topic is a rabbit-hole. 🐰

Supporting different (Markdown) parsers sounds like a good alternative to me. We should at consider one that supports Github Flavored Markdown as that is quite a popular variant.

**Comment by buddhist-uni** [comment]
> 2\. Use `txt` file extension: `underscore_urls.txt` will use our plaintext parser and work as expected

Just to follow up, [I did this hack](https://github.com/buddhist-uni/buddhist-uni.github.io/runs/2681961902) and indeed it worked as expected. So, for any future people having this issue, I added this step to my workflow:

~~~
- name: Rename .md files to .txt
  run: |
   cd $GITHUB_WORKSPACE
   sudo apt-get install -y rename
   find . -name "*.md" -exec rename 's/\.md$/.txt/' {} +
~~~

then ran lychee on `**/*.txt` instead of `.md`

**Comment by mre** [comment]
A generic solution would be hard to pull off, but I'm glad you found a workaround so I guess we can close this.
