### ISSUE TITLE
Suggest possible fixes for broken URLs to archive sites?

### ISSUE THREAD

**Issue by kaihendry** [lycheeverse/lychee#283]
As mentioned upon https://github.com/lycheeverse/lychee-action/issues/37#issuecomment-878248088

It would be good to have a `--fix` flag that could perhaps rewrite dead URLs into working archived URLs like that provided by

* http://web.archive.org/

**Comment by mre** [comment]
This can be done with the [Wayback Machine API](https://archive.org/help/wayback_api.php) if anyone wants to give it a try.
Here is a sample request:  
https://archive.org/wayback/available?url=example.com
