### ISSUE TITLE
Ensure cookies are not re-used between requests

### ISSUE THREAD

**Issue by pawroman** [lycheeverse/lychee#29]
Certain websites use cookies to throttle/rate-limit requests. Not storing cookies between requests is one strategy to avoid being rate-limited.

I'm not sure what the current behavior is, but would be good to ensure this.

**Comment by mre** [comment]
Just checked and it looks like cookie handling would have to be added explicitly in reqwests:
https://www.reddit.com/r/rust/comments/bb1tuo/question_how_to_use_cookies_with_reqwest/
So I think we're all good here for now. Do you think we can close this? 😃

**Comment by pawroman** [comment]
Awesome. Yeah, good to close :+1:
