### ISSUE TITLE
Consider retrying on certain HTTP codes only

### ISSUE THREAD

**Issue by pawroman** [lycheeverse/lychee#30]
The purpose of a link checker is to ensure that the tested links are all still valid.

However, some HTTP codes indicate permanent issues and resources that are gone. In my experience, 404 is usually not worth retrying.

You can argue that retries should only happen for certain subset of the HTTP codes, to speed up the link checking process. This might be a configurable option.

**Comment by mre** [comment]
Nice idea! We could add a `skip-retry` option that defaults to `404`. If anyone is interested in working on this, post a comment here. @pawroman and me are happy to help. 😊

**Comment by mre** [comment]
So after looking at the code again, I'm not sure if there's anything left to do here.
At the moment we accept any HTTP status code and don't retry if we get a "valid" response.

https://github.com/lycheeverse/lychee/blob/2a80760f586688e8512e895da49709314375b1bc/lychee-lib/src/client.rs#L191-L193

So no matter if we receive a 200 or a 404, we don't retry. Only if there was an invalid status code we check again.
Makes sense to me actually. What do you think?

**Comment by mre** [comment]
I think this is done. Closing this to keep the issue tracker clean. @pawroman feel free to reopen. 😉
