### ISSUE TITLE
[Question] Is there a way to customize the 404 logic?

### ISSUE THREAD

**Issue by BrunoQuaresma** [lycheeverse/lychee#300]
I have an app built using NextJS, and usually, the 404 page of NextJS returns the 200 status code because it is a static page. So, I would like to check the page using its body, looking for the canonical meta tag. Is that possible?

**Comment by mre** [comment]
Closing this as there is a preferable solution provided by @lebensterben and for the reasons stated in the comments.
Your input was very welcome @BrunoQuaresma and thanks for using lychee. 😃
