### ISSUE TITLE
Load --exclude from a file

### ISSUE THREAD

**Issue by dblock** [lycheeverse/lychee#302]
We like having a link checker in https://github.com/opensearch-project/OpenSearch, but we also often encounter URLs that no longer work in things like license files. Therefore we can't just fix the links. This leads to a fairly long list of URLs to exclude, which we keep adding to a GitHub action job, which reads poorly.

In https://github.com/opensearch-project/OpenSearch/pull/1189 I've hacked our workflow to read the exclusions from a file, but it's not an ideal implementation :) 

Should we add `--exclude-file` to lychee?

**Comment by lebensterben** [comment]
@dblock 
lychee currently support config file. so at least you can put those urls in it.

**Comment by dblock** [comment]
> @dblock
> lychee currently support config file. so at least you can put those urls in it.

Oh where/how? I see README mentions a config file, but can't find a reference/example.

**Comment by lebensterben** [comment]
indeed.

**Comment by mre** [comment]
Good idea!

**Comment by dblock** [comment]
This was implemented in #306, and released in 7.0.1.
