### ISSUE TITLE
Publish workflow fails

### ISSUE THREAD

**Issue by dblock** [lycheeverse/lychee#305]
Since https://github.com/lycheeverse/lychee/pull/225 the publish CI check is failing, which seems to be "by design". This was confusing to me trying to contribute for the first time - I wasn't sure whether I broke something. 

Maybe that workflow should be disabled/removed until it can succeed?

**Comment by mre** [comment]
Yeah I'm not happy with that tbh. We can of course publish lychee-lib whenever we have to do breaking changes, but it would be great if we could still ensure green builds for feature branches.

**Comment by dblock** [comment]
I am still trying to fix it in #304

**Comment by dblock** [comment]
@mre If you know how to fix https://github.com/dtolnay/proc-macro2/issues/298 we'll be in business.

**Comment by mre** [comment]
Yay! 🌻
