### ISSUE TITLE
Consider treating codes other than 200 as success

### ISSUE THREAD

**Issue by pawroman** [lycheeverse/lychee#31]
Currently, we only consider 200 status code as success. But in some cases codes like 206 Partial Content might be treated as success, e.g. the entire content might not be needed.

This should probably be a configurable option.

**Comment by mre** [comment]
Oh actually it is: https://github.com/lycheeverse/lychee/blob/a7673562d7d4ca58defe1088a5e6aa1cbe373e5d/src/options.rs#L123-L126
But we should probably set a sane default like `["200", "204", "206"]` or so.

**Comment by mre** [comment]
@pawroman do you think we should change the default? If not I'd say we can close this because the success codes can be configured like so: `--accept 200,204,206`.

**Comment by pawroman** [comment]
Hi, sorry for the delayed response.

Looks good as it is, thanks for confirming :+1:

**Comment by mre** [comment]
No worries. Glad we got this covered. 😊
