### ISSUE TITLE
Shall --exclude-loopback affect "localhost" as well?

### ISSUE THREAD

**Issue by MichaIng** [lycheeverse/lychee#319]
Currently using the `-E` option does not exclude the `localhost` hostname, which I somehow expected.

Strictly seen this is correct, as the option aims to exclude the "loopback IP address range" explicitly, while `localhost` is only a common local hosts entry pointing to the loopback IP, while it can point to anything else or not exist at all.

So just the question whether it does make sense to still affect `localhost` as well, or whether to have an own option for it (probably doesn't make sense as a single `--exclude` does it) or have it implied with `-E, --exclude-all-private`?

**Comment by mre** [comment]
@pawroman what do you think?

**Comment by lebensterben** [comment]
loopback is determined by std's function https://doc.rust-lang.org/stable/std/net/enum.IpAddr.html#method.is_loopback

which already includes 127.0.0.1

https://doc.rust-lang.org/stable/std/net/struct.Ipv4Addr.html#associatedconstant.LOCALHOST

**Comment by lebensterben** [comment]
By RFC 6761, localhost is reserved for loopback purpose.

https://datatracker.ietf.org/doc/html/rfc6761#section-6.3

So the only correct way of handling it is to follow std and the standard, that treat it as loopback.

**Comment by MichaIng** [comment]
> By RFC 6761, localhost is reserved for loopback purpose.

The wording isn't actually that strict.

>    3.  Name resolution APIs and libraries SHOULD recognize localhost
>        names as special and SHOULD always return the IP loopback address
>        for address queries and negative responses for all other query
>        types.  Name resolution APIs SHOULD NOT send queries for
>        localhost names to their configured caching DNS server(s).

It's `SHOULD` and not `MUST` 😉. On the Linux distros I work, it is practically a "must", as a whole lot of software simply requires and expects it do be like that, but I'm not sure if it is that clear on all OSes 🤔.

**Comment by lebensterben** [comment]
https://datatracker.ietf.org/doc/html/rfc2119#section-3

> that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

Should 'localhost' be treated differently from std and RFC, it'd be against most peoples expectations.

If its really needed, we can add one more configuration option. that's much better than breaking the principle of least surprise

**Comment by MichaIng** [comment]
Don't understand me wrong, I'm clearly on your side in this, which is the reason why I opened the issue. Just for completeness and understanding possible implications, it needs to be taken care that there is a difference between an IP, which is somehow absolute and via `MUST` bound to specific purposes, and practically it is impossible to access a remote host directly (without redirection, embedding etc) with any loopback/LLA/private IP address. But there are no such `MUST` bound strict rules for hostnames, and also practically one can make `localhost` point to any random remove host via `hosts` entry. But I agree that it will meet "most peoples expectations" (including mine) to imply `localhost` in loopback exclusion. Any different hosts entry, at least on all systems I know, could be seen as wanton destruction 😄.

**Comment by mre** [comment]
I'd accept a PR for adding localhost to the exclusions when using `-E`. Bonus points for adding some documentation on the reasoning and a link to the RFC. Any takers?

**Comment by MichaIng** [comment]
Shall it be with the `-E` flag only, or with `--exclude-loopback` already, since it practically is the loopback address?

**Comment by mre** [comment]
Let's do both, yeah. Would you like to tackle this?

**Comment by MichaIng** [comment]
I cannot guarantee that I find time soon, but I'll have a look into it. So far I cannot imagine that it's hard to implement, even for a Rust newby like me 🙂.

**Comment by MichaIng** [comment]
PR up: #351
