### ISSUE TITLE
Why `lychee` does not defaults to `--help` ?

### ISSUE THREAD

**Issue by fauust** [lycheeverse/lychee#327]
Hi!
`lychee` defaults to trying to parse a `README.md` file and this is quite strange IMO.

Maybe defaulting to `--help` would be more appropriate?

I am not sure about the reason of this behavior (there is maybe a very good one) and sorry if this was already discussed.

**Comment by mre** [comment]
Not much thought went into that other than the idea that the tool would be used mostly in code repositories where a `README.md` would be a somewhat sane default. One could argue that an even better one would have been '**/*.html' or anything similar, but we didn't have glob functionality back then.
To be honest I didn't think that the tool would grow into what it is now. The number use-cases has increased so it's a good time to revisit that default.

Especially given that running lychee in a directory without a `README.md` is not very welcoming:

```
> lychee
Error: Failed to read file: `README.md`, reason: No such file or directory (os error 2)
```

 I'd say we should change it to `--help`.

**Comment by MichaIng** [comment]
To not make a breaking change, it could also keep scanning `README.md` if present, and only show the help when not. But probably it's not worth to hassle with this when it could simply behave like most other command line tools and show the help right away.

**Comment by fauust** [comment]
OK, thanks.

It could also be considered a bit intrusive to start parsing a bunch of `*.md` files without the user explicitly asking for it.

I did a quick research and I could not find any best practice or standards for CLI tools, so maybe `--help` is the most natural one.

**Comment by fauust** [comment]
Maybe something to take in consideration before doing the move is if something like `cat foo.md | lychee` (or derivate) is desirable... I can't see any benefits so far but others may.

**Comment by mre** [comment]
Catching those issues before 1.0 is great because we're still in a phase where we can make breaking changes without bumping the major version. Most users call lychee with some arguments already I think, so not much would change.

We support `stdin` with `lychee -`. Reading from stdin without `-` would look like lychee is busy when calling it without any arguments, which could be confusing. 

In summary, let's make `--help` the default. @fauust are you willing to try a PR? 😊

**Comment by fauust** [comment]
I would love to but I am really not a developer...

**Comment by mre** [comment]
No worries. In this case it's all structopt magic. 🪄 🐰 🎩 See PR. 😄 #329
