### ISSUE TITLE
Use structopt-toml as a config loader?

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#34]
I just found [`structopt-toml`](https://github.com/dalance/structopt-toml/) and it looks like it covers all of what we need for our config loader. The code is quite similar and also uses `serde` in the background. The advantage is that we could outsource some code to this crate and avoid duplication of default values in our `config.rs`.

Here is an example from their docs:

```rust
use serde_derive::Deserialize;
use structopt::StructOpt;
use structopt_toml::StructOptToml;

#[derive(Debug, Deserialize, StructOpt, StructOptToml)]
#[serde(default)]
struct Opt {
    #[structopt(default_value = "0", short = "a")]
    a: i32,
    #[structopt(default_value = "0", short = "b")]
    b: i32,
}

fn main() {
    let toml_str = r#"
        a = 10
    "#;
    let opt = Opt::from_args_with_toml(toml_str).expect("toml parse failed");
    println!("a:{}", opt.a);
    println!("b:{}", opt.b);
}
```

@pawroman, @akrantz01 what do you think? Am I missing a feature here that we need?
If anyone wants to work on a PR, feel free to comment here.

**Comment by pawroman** [comment]
Nice find, definitely worth a try :+1:

**Comment by mre** [comment]
structopt-toml doesn't seem to be very actively maintained at the moment. At least the last couple of issues didn't get a reply yet. Given that we don't have any problems with maintaining our own solution at the moment, I'd say let's close this issue.
