### ISSUE TITLE
Fix URI cache to cache URIs across multiple files

### ISSUE THREAD

**Issue by MichaIng** [lycheeverse/lychee#348]
As tested [here](https://github.com/lycheeverse/lychee/pull/243#issuecomment-913027437), the URI cache for caching URI check results across all input files, does not work as expected.

There is a test for repetition in a single file: https://github.com/lycheeverse/lychee/blob/master/lychee-bin/tests/cli.rs#L218-L229
But this worked before the new URI cache was implemented. This test may be extended to use two identical files.
@mre 
Is it actually intended that two identical URLs in two separate files contribute only 1 to the total of the summary, or is it still 1 per input (and only the actual request skipped internally)? In the latter case, expanding or implementing the test would be more difficult.

**Comment by mre** [comment]
The cache should work across files. At least that's the goal. So the same link should always only count as 1 in the total, no matter in how many files it occurs.

**Comment by MichaIng** [comment]
Okay great, I'll try to extend the cache accordingly.

**Comment by MichaIng** [comment]
PR up: #349
I hope I did the syntax right 😅.

**Comment by mre** [comment]
Current status: Caching across files is currently disabled. See [test_caching_across_files](https://github.com/lycheeverse/lychee/blob/d96c1269ff34f67f0a94cf66503b0a497621e088/lychee-bin/tests/cli.rs#L240).
We're planning to bring this back at some point.
https://github.com/lycheeverse/lychee/pull/349#issuecomment-937741323
