### ISSUE TITLE
429 Too Many Requests

### ISSUE THREAD

**Issue by dcroote** [lycheeverse/lychee#367]
We've seen `HTTP status client error (429 Too Many Requests) for url` for github.com urls intermittently even when using the GITHUB_TOKEN `env` and reducing concurrency to 10 threads. A few examples of Action runs where this occurred: [1](https://github.com/api3dao/api3-docs/runs/3957376822?check_suite_focus=true), [2](https://github.com/api3dao/api3-docs/runs/3957001728?check_suite_focus=true), [3](https://github.com/api3dao/api3-docs/runs/3952001663?check_suite_focus=true), [4](https://github.com/api3dao/api3-docs/runs/3969888775?check_suite_focus=true) and [here is the workflow itself](https://github.com/api3dao/api3-docs/blob/5808205be067a89ee6ed99538332e2beadca35d3/.github/workflows/check-links-imgs.yaml). Note the workflow uses a cached installation of lychee installed via cargo from a specific commit sha rather than the v0.7.1 marketplace Action because of additional functionality that's been added since that release.

I think the ideal solution would be as described in #348 to avoid hitting the same url repeatedly from different files (which is indeed the case with the urls causing failures in the Actions runs above), but I can see this is complex (#349).

Another theoretical idea could be running lychee twice, once with high concurrency using `--exclude github.com` and again with minimal concurrency and `--include github.com`.

A third might be identifying github.com urls and applying different internal handling of how they're requested?

Would love to get your thoughts and also confirm it isn't a usage issue.

Overall though great tool, it's helpful to check both internal and external urls + images / img tags quickly

**Comment by JAremko** [comment]
I test files in batches with [separate lychee-actions](https://github.com/syl20bnr/develop.spacemacs.org/tree/gh-pages/.github/workflows). They run ~2 hours apart from each other.  It would be cool if there was an arg that can set up the root directory.  `-base`doesn't work in the action for some reason. I ended up encoding it in the file path [doc/**/*.html](https://github.com/syl20bnr/develop.spacemacs.org/blob/41b1561d60237b24441fff9cf9dc2dde10008635/.github/workflows/doc_links.yml#L24) 

I think gists  should also be tested with tokens. See https://github.com/lycheeverse/lychee-action/issues/54

On the other hand there might be a way to fix it for good  by splitting link checking process into 2 actions.
First one collects all the unique URLs (normalizing, removing # etc) and stores them somehow.  Maybe simply output them in a parseble form as a part of CI log. Or maybe in issue. 
The second action goes through this list and tests the links, if it hits recoverable error it generates another list and the cycle continues :grin:  It would be much less "hacky" if there was a way to schedule an action from an action :thinking:

**Comment by JAremko** [comment]
Actually, there is https://github.com/marketplace/actions/schedule-job-action thingy. But it seems to require personal token.  Wouldn't work for my use case.

**Comment by JAremko** [comment]
Other solution would be an introduction of "URL health". "Healthy" URL is an URL that has been successfully tested in last 24 hours and it doesn't need to be tested again for some time.  :face_with_thermometer:  URL is an URL that  has a recoverable error or timed out less than X times  in a row. And :skull:  URL is  everything else.

**Comment by MichaIng** [comment]
> `--base` doesn't work in the action for some reason.

Note that this option does not define the root directory for input files but the root path or URL for the contained relative/internal links, like `<a href="/subdir/page.html">`. For the inputs you hence still need to define file names, a regex or an URL you want to check links on.

> I think gists should also be tested with tokens.

Makes sense, probably all subdomains of `github.com` should use the token as well.

**Comment by JAremko** [comment]
Actually, if link checker would have some kind of state shared between runs, I like the idea of storing links and their statuses (health) in an issue for further reinspection. Basically, using such issue as a config file of sorts.
The action can update that config issue with the list of ignored URLs, add the dates when URLs has been tested last time, what URLs are in "temporary outage" list. It would be much easier to see whats going on :thinking: 

@MichaIng  Should'v RTFM :face_with_head_bandage:  :palm_tree:

**Comment by mre** [comment]
> Other solution would be an introduction of "URL health". "Healthy" URL is an URL that has been successfully tested in last 24 hours and it doesn't need to be tested again for some time. 🤒

Yeah that is planned. #163

**Comment by rigtorp** [comment]
Honoring rate limit headers would be a good idea and not too difficult, here's how it's done in pytest-check-links:
https://github.com/jupyterlab/pytest-check-links/blob/master/pytest_check_links/plugin.py#L301

```
        if response.status_code >= 400:
            if retries and self.sleep(response.headers):
                self.uncache_url(url_no_anchor)
                return self.fetch_with_retries(url, retries=retries - 1)
```
and `self.sleep` tries to sleep if the Retry-After header is present (https://github.com/jupyterlab/pytest-check-links/blob/master/pytest_check_links/plugin.py#L243).

**Comment by dcroote** [comment]
@rigtorp - thanks for the resources. This would be helpful for sites that include a Retry-After header, but unfortunately GitHub has its own set of headers. See [the above comment](https://github.com/lycheeverse/lychee/issues/367#issuecomment-952116663) by @mre.

**Comment by rigtorp** [comment]
@dcroote They do support it, it's a standard header implemented by all the reverse proxies and caches. So it's the more generic solution. The rate limit headers are typically only implemented for APIs, where a API consumer can use them to throttle work items pulled from a queue for example.

First to generate rate limit:
```bash
while true; do curl --head "https://github.com/rigtorp/MPMCQueue"; done
```

After some time:
```
HTTP/2 429 
date: Wed, 01 Dec 2021 21:51:55 GMT
server: Varnish
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-content-type-options: nosniff
x-frame-options: deny
x-xss-protection: 1; mode=block
content-security-policy: default-src 'none'; style-src 'unsafe-inline'
content-type: text/html; charset=utf-8
retry-after: 60
content-length: 1474
x-github-request-id: B2AC:C7D8:6E231:76832:61A7EE7B
```

Here github is asking to wait 60 seconds.

**Comment by mre** [comment]
Current status for people coming in just now:
* Response caching was implemented in https://github.com/lycheeverse/lychee/issues/163. Enable it with `--cache`.
* If you're getting 429s on Github, check that you have a `GITHUB_TOKEN` set. This can significantly improve the situation by allowing way more requests.
* You can exclude domains with `--exclude pattern`, e.g. `--exclude github.com`.
* You can reduce the number of concurrent requests to avoid running into the rate-limiter: `--max-concurrency`
* You can run lychee multiple times on a subset of the requests as @JAremko described above.
* I wrote a crate for parsing rate limit headers: https://github.com/mre/rate-limits. Planning to use it in combination with https://github.com/lycheeverse/lychee/issues/36 to respect the server settings.

With that, I guess we can close this and focus on the open issues for the missing functionality.
