### ISSUE TITLE
Question: Should `Accept: text/html` be a default header?

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#37]
[Crates.io returns 404 when not specifying a custom `Accept: text/html` header](https://github.com/rust-lang/crates.io/issues/788).

I wonder if we should make that header a default for all requests. 
Not sure how many other websites have the same issue, but I'm wondering if it can hurt to specify the encoding just in case.
On the other side there might be scenarios where we expect JSON as a response or other encodings,
so it might be a bad idea. Still wanted to get it out there.

Does anyone have any experience with this?

**Comment by pawroman** [comment]
Good question. I have not encountered this in the wild, maintaining a sizeable collection of links that I'm checking regularly. Maybe it's not a very common issue?

Perhaps we should build a document with "common quirks" such as this?

E.g. accept status might need setting to 200,204,206 etc, `Accept: text/html` header (or even `Accept: */*`) needs to be set, etc.

Users can work around these using the configuration flags, but the documentation and/or program output should hint how to deal with such issues.

**Comment by mre** [comment]
Great idea! Started a troubleshooting guide [here](https://github.com/lycheeverse/lychee/blob/master/TROUBLESHOOTING.md). We can always extend it and move some of the common workarounds into a module if we like.
