### ISSUE TITLE
`error sending request for url...` errors

### ISSUE THREAD

**Issue by markzegarelli** [lycheeverse/lychee#374]
Running lychee 0.8.0 locally on my mac.

I'm trying to set up Lychee as part of my CI process for a large documentation site, that checks the output directory after a build.

However, in the output, I get more than 2x the number of the following, compared to 404s:
```
(error sending request for url (<url>): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

This error appears on both local and external URLs.

Is there a way to prevent or suppress these errors? I am mainly interested in 404s.

**Comment by mre** [comment]
Looks like you run into some DNS issues. For the domains that are failing, can you open them in a browser?
If not, these might be internal links and you might not have them in your /etc/hosts or you have to connect to a VPN first. Also, do the DNS errors only occur for a limited number of domains? Maybe just one site that isn't reachable? That might point to an internal server as well.

In any case, there is not way to ignore dns errors right now. 
reqwest (the library we use for making the requests) has a method to check if the error happened during connection: https://github.com/seanmonstar/reqwest/blob/ab49de875ec2326abf25f52f54b249a28e43b69c/src/error.rs#L94-L95
So in theory we could add a flag like `--ignore-connect` to make these error messages go away. I'd like to hear some opinions on this. The flag could potentially shadow unexpected errors. An alternative is to use `--exclude` for the domains where errors are expected. This would already work today and wouldn't require any changes.
