### ISSUE TITLE
.git suffix should be ignored on GH links

### ISSUE THREAD

**Issue by JAremko** [lycheeverse/lychee#384]
Links like `https://github.com/Microsoft/python-language-server.git `  reported as (404 Not Found: Not Found)  while `https://github.com/Microsoft/python-language-server` is totally fine and GH actually redirects `.git` links there. 
It meters for the cases when  lychee detects links in config files and code samples that use such links to install dependencies (for example ruby gems, python stuff).

**Comment by mre** [comment]
lychee follows redirects (up to a configurable number), so that's strange.

**Comment by JAremko** [comment]
@mre  [her's log](https://pipelines.actions.githubusercontent.com/Q1WnMNC8nyjtXJl4ZWhckdi4BFkbWSyv02VlZ0A1uZABuKU4JR/_apis/pipelines/1/runs/137/signedlogcontent/2?urlExpires=2021-11-05T12%3A08%3A10.7053658Z&urlSigningMethod=HMACV1&urlSignature=FeRbMLIF4cH9iFOTCgIBXDgjBWPURYaakcfW0JYiSYQ%3D)  

The  line says:
```
2021-11-05T06:12:24.9985312Z Errors in layers/+lang/python/README.html
2021-11-05T06:12:24.9986519Z ✗ https://github.com/Microsoft/python-language-server.git (404 Not Found: Not Found)
```

Looks like it detects [this link](https://develop.spacemacs.org/layers/+lang/python/README.html#microsoft-python-language-server)
```
git clone https://github.com/Microsoft/python-language-server.git
cd python-language-server/src/LanguageServer/Impl
dotnet build -c Release
dotnet publish -c Release -r <RUNTIME>
```

**Comment by mre** [comment]
Yeah that's a bug. It should have detected that as a 200. I wonder what's up...

**Comment by JAremko** [comment]
@mre 

I requested the link from chrome:
```
Request URL: https://github.com/Microsoft/python-language-server.git
Request Method: GET
Status Code: 301  (301 Moved Permanently)
```

Yeah nothing special about it :thinking:

**Comment by mre** [comment]
Seems to work on my machine with lychee. 🤔 

```
❯❯❯ echo https://github.com/Microsoft/python-language-server | lychee --verbose -
✔ https://github.com/Microsoft/python-language-server [200 OK]

🔍 1 Total ✅ 1 OK 🚫 0 Errors

❯❯❯ echo https://github.com/Microsoft/python-language-server.git | lychee --verbose -
✔ https://github.com/Microsoft/python-language-server.git [200 OK]

🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

@JAremko can you test again?

**Comment by JAremko** [comment]
@mre  
`https://github.com/Microsoft/python-language-server.git: Failed: 404 Not Found: Not Found`

https://github.com/syl20bnr/develop.spacemacs.org/issues/162

**Comment by mre** [comment]
It gets weirder then. That would mean that the action is doing something else than lychee. Checked the action params, but don't see anything special. Still don't know how this can be. Maybe it has something to do with the fact that it runs on Github's servers, but I doubt it.

**Comment by JAremko** [comment]
@mre  Well, us I understand it uses GH token to access URLs like `https://github.com/Microsoft/python-language-server.git`  Maybe the process getting messed up by the redirect or GH doesn't support this type of access on `.git` URLs :thinking:

**Comment by mre** [comment]
Hum. I tested with a Github token to no avail. 😕

**Comment by jazanne** [comment]
i'm experiencing the same issue - for the moment i added all `.git` links to my exclude list

**Comment by lukehsiao** [comment]
I'm also seeing the same. One additional note that in my case it is a `.git` link to a private repo.

**Comment by mre** [comment]
Taking a look at https://github.com/syl20bnr/develop.spacemacs.org/issues/162 linked by @JAremko again I can see that lychee ran into Github's rate limiting, returning a lot of `429`s. When this happens, we use the Github API as a fallback, but the API doesn't handle `.git` links, so it returns a 404. @jazanne, @lukehsiao, please check if you also check a lot of Github links and hence you're also affected by the rate limiting.

**Comment by lukehsiao** [comment]
In my case, lychee is only checking about 10 URLs total, all of which return 200 OK except for the `.git` URL, which returns a 404.

I'll also note that I'm getting 200 OKs from other links in the private repo (e.g., to issues, to the README, to the changelog, etc.) It's just the `.git` in the documentation for how to clone the repo that it is 404-ing.

**Comment by mre** [comment]
If you have some time, can you try with the version from https://github.com/lycheeverse/lychee/pull/453?

Locally, you can install the version from this PR with

```
cargo install --git https://github.com/lycheeverse/lychee --branch strip-git
```

**Comment by mre** [comment]
In your case the bug is a different one: you don't run into Github's rate-limiting, but instead a private repo can't be checked without the API token (returns a 404 to not leak any information to the caller) and the API cannot handle `.git` URLs. So what I did was strip `.git` if it's the final part of the URL.

**Comment by lukehsiao** [comment]
Got it. Looking at that patch, I highly suspect it would work.

Unfortunately, I'm actually seeing lychee crash with 

```thread 'tokio-runtime-worker' panicked at 'not currently running on a Tokio 0.2.x runtime.', /home/lukehsiao/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.25/src/runtime/handle.rs:118:28```

when I provide a github token locally. This is likely a separate issue, though...

**Comment by lukehsiao** [comment]
When running on your strip-git branch, rather than a tokio panic, I'm seeing "Network error while trying to connect to an endpoint via (reqwest or hubcaps)"

**Comment by mre** [comment]
> panicked at 'not currently running on a Tokio 0.2.x runtime.'

Ouch. That's bad. One of the dependencies needs still needs a 0.2 runtime and is not compatible with newer versions. Checked with `cargo tree`, but couldn't see anything suspicious. I'll update all dependencies in #454. Let's see if it helps. That's a separate issue, though as you rightly assessed. The other error "Network error while trying to connect to an endpoint via (reqwest or hubcaps)" is more in line with what you can expect without setting a Github token. That's a normal 404 and we have no way to know if the private repo exists without a valid access token.

**Comment by mre** [comment]
Merged the dependency update to `master` and the `strip-git` branch on top of it. 
If you wanna test again with that version, use
```cargo install --git https://github.com/lycheeverse/lychee --branch strip-git```
Hope that fixes the panic. 🤞  If not... 😕

**Comment by lukehsiao** [comment]
Amazing! Two updates for you, then.

1. #454 fixes the panic for me (leaving just the single `.git` URL failing)

```
✔ https://github.com/private/repo/actions/workflows/ci.yml/badge.svg [200 OK]
✔ https://github.com/private/repo/actions [200 OK]
✔ https://github.com/private/repo/issues/ [200 OK]
✔ https://github.com/private/repo/compare/v0.0.1-alpha.0...v0.0.1 [200 OK]
✔ https://github.com/private/repo/releases/tag/v0.0.1-alpha.0 [200 OK]
✔ https://github.com/private/repo/compare/v0.0.1...v0.1.0 [200 OK]
✔ https://github.com/private/repo/issues [200 OK]
✗ https://github.com/private/repo.git: Network error when trying to connect to an endpoint via hubcaps
```

2. The strip-git branch fixes the .git, but appears introduce some different errors:

```
✗ https://github.com/private/repo/issues: Network error while trying to connect to an endpoint via reqwest
✗ https://github.com/private/repo/actions: Network error while trying to connect to an endpoint via reqwest
✗ https://github.com/private/repo/actions/workflows/ci.yml/badge.svg: Network error while trying to connect to an endpoint via reqwest
✗ https://github.com/private/repo/compare/v0.0.1-alpha.0...v0.0.1: Network error while trying to connect to an endpoint via reqwest
✗ https://github.com/private/repo/issues/: Network error while trying to connect to an endpoint via reqwest
✗ https://github.com/private/repo/releases/tag/v0.0.1-alpha.0: Network error while trying to connect to an endpoint via reqwest
✗ https://github.com/private/repo/compare/v0.0.1...v0.1.0: Network error while trying to connect to an endpoint via reqwest
✔ https://github.com/private/repo.git [200 OK]
```

**Comment by mre** [comment]
Thanks for the quick turnaround! 🙏 

The issue with the failing links is a tricky one: AFAIK the Github API doesn't allow checking for repo endpoints like issues, releases, or actions. For public repos that's not an issue, because a simple request will check if it exists. In your case however it's a private repo, so a normal check returns a 404 and a check with the Github token won't work either because of the API limitations. What we did before was to _assume_ these things would work if the private repo existed, but a user could disable issues or pull requests on a per-repo basis. Even then, I'd say the best way forward is to revert this stricter check and stay in line with the user expectation of returning a 200 -- even though we can't be 100% sure that's correct. But the alternative of returning a ton of errors for private repos is worse and most people won't change the repo settings. 

Sounds good?

**Comment by lukehsiao** [comment]
Ah, that's quite nuanced!

> What we did before was to assume these things would work if the private repo existed, but a user could disable issues or pull requests on a per-repo basis. Even then, I'd say the best way forward is to revert this stricter check and stay in line with the user expectation of returning a 200 -- even though we can't be 100% sure that's correct. But the alternative of returning a ton of errors for private repos is worse and most people won't change the repo settings.

Frankly, I think you're the boss here and either option sounds reasonable to me :). If I'm weighing in, I'd probably think that the revert you suggest is a more friendly default, even if it might be inaccurate. But I think as long as there is some docs, users could adjust either way.

**Comment by mre** [comment]
Pushed an update to the `strip-git` branch. It should work as discussed now. Can you try again?

**Comment by lukehsiao** [comment]
Absolutely. There were two warning when compiling:

```
warning: associated function is never used: `new`
  --> lychee-lib/src/types/uri.rs:41:8
   |
41 |     fn new<T: Into<String>>(owner: T, repo: T) -> Self {
   |        ^^^
   |
   = note: `#[warn(dead_code)]` on by default

warning: associated function is never used: `with_endpoint`
  --> lychee-lib/src/types/uri.rs:49:8
   |
49 |     fn with_endpoint<T: Into<String>>(owner: T, repo: T, endpoint: T) -> Self {
   |        ^^^^^^^^^^^^^

warning: `lychee-lib` (lib) generated 2 warnings
```

But, it does behave as you described and seems great to me!

```
✔ https://github.com/private/repo/actions/workflows/ci.yml/badge.svg [200 OK]
✔ https://github.com/private/repo/issues [200 OK]
✔ https://github.com/private/repo/actions [200 OK]
✔ https://github.com/private/repo/issues/ [200 OK]
✔ https://github.com/private/repo/releases/tag/v0.0.1-alpha.0 [200 OK]
✔ https://github.com/private/repo/compare/v0.1.0...v0.1.1 [200 OK]
✔ https://github.com/private/repo/compare/v0.0.1-alpha.0...v0.0.1 [200 OK]
✔ https://github.com/private/repo/compare/v0.0.1...v0.1.0 [200 OK]
✔ https://github.com/private/repo.git [200 OK]
```

**Comment by lebensterben** [comment]
@mre 
Another approach is to actively look up for README file according to https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-readmes

This helps to avoid quite a few unnecessary links on GitHub itself. (E.g. links to homepage, various tabs of repo, etc.)

The downside may include:
- We need to handle relative path. (Not really an issue)
- We may miss URLs in repo's description since it's not in README but appear on the repo page

**Comment by mre** [comment]
Not sure I understand. Not every repo has a `README` and the file name could vary (`README.md`, `README.txt`, `README`, lowercase?). How would we determine if it's an actual 404 if we don't find the right file? Would we try them all or do another API call to find the right one?

**Comment by untitaker** [comment]
why does lychee not attempt to initiate a clone over https (and abort it)? I'm sure just for determining 404s you can emulate a part of the protocol with a regular http client, and afaik github-token can be used for private repo cloning (just different kind of header probably)

**Comment by mre** [comment]
All great ideas! But let's not forget that lychee is a link checker and that Github already has a more prominent spot than   other sites. As always, we have to find a trade-off between performance, maintainability and correctness. At the end of the day we also need to divide our limited free time among all issues. 😉

So I propose to merge #453 with what we discussed so far, which should fix this issue and https://github.com/lycheeverse/lychee/issues/449. Always open for PRs though.

**Comment by lukehsiao** [comment]
I agree that lychee should *not* initiate a clone, and prioritize simplicity and performance. Thanks for this fix!

**Comment by lebensterben** [comment]
> Not sure I understand. Not every repo has a `README` and the file name could vary (`README.md`, `README.txt`, `README`, lowercase?). How would we determine if it's an actual 404 if we don't find the right file? Would we try them all or do another API call to find the right one?

Let's try to find README file by emulating the way how GitHub finds it if it exists.
- If it does exist, the readme file contains the links users actually want to check with lychee. Note that when you open a GitHub repository page, it contains the README and other GitHub UI elements, where the UI elements are not really relevant.
- If it doesn't, then the GitHub repo page contains only GitHub UI elements and there's not need to check.

**Comment by lukehsiao** [comment]
@lebensterben I don't think this issue has anything to do with READMEs, as lychee is just a generic link checker, not a README link checker.

**Comment by lebensterben** [comment]
@lukehsiao I understand what you mean. But consider this:

Users may want to ask lychee to (recursively) check all links in a repo by providing a git repo's URL. In many cases README is where most links are, since it acts as a summary or index page for a repo. Depending on the type of repo, you may even not having any URLs elsewhere. (which is what I experienced most)

**Comment by mre** [comment]
This should be fixed in `master` now. 🎉 Recursion isn't supported yet, so I'd postpone the discussion about fetching the `README`. Quite honestly, I think it goes a bit too far for a general link checker, but we can revisit this in the future. Thanks everyone for your input. Feel free to open a new issue in case you see any odd behavior.
