### ISSUE TITLE
Lychee claims my email address is unreachable

### ISSUE THREAD

**Issue by hannobraun** [lycheeverse/lychee#389]
I checked my website using Lychee:
```
$ lychee https://hanno.braun-odw.eu 
📝 Summary
---------------------
🔍 Total...........28
✅ Successful......26
⏳ Timeouts.........0
🔀 Redirected.......0
👻 Excluded.........0
⚠ Unknown..........0
🚫 Errors...........2

Errors in https://hanno.braun-odw.eu/
✗ Hanno%20Braun%20%3Channo@braun-odw.eu%3E (Unreachable mail address: Hanno%20Braun%20%3Channo@braun-odw.eu%3E)
✗ hanno@braun-odw.eu (Unreachable mail address: hanno@braun-odw.eu)
```

It complains that my email address is unreachable, which is not true (I've just confirmed).

**Comment by mre** [comment]
I think it parses the mail address incorrectly. There is a `>` at the end.  Can you post the relevant HTML here as well for troubleshooting please?
The second one looks fine. We use the check-if-email-exists, so it might be a bug over there.

**Comment by hannobraun** [comment]
Here's the HTML:
``` html
<a href="mailto:Hanno%20Braun%20%3Channo@braun-odw.eu%3E">
    hanno@braun-odw.eu
</a>
```

I think I'm doing the right thing here. That's just the URL encoding of `Hanno Braun <hanno@braun-odw.eu>`. At least Thunderbird handles it correctly.

You can test yourself by going to any page on [https://hanno.braun-odw.eu/](https://hanno.braun-odw.eu/) and clicking on the email address near the upper-right corner.

**Comment by hannobraun** [comment]
> We use the check-if-email-exists, so it might be a bug over there.

I think I figured out what the problem is.

[`check-if-email-exists`](https://crates.io/crates/check-if-email-exists) has a [live demo](https://reacher.email/). If I enter my email here, I get this:
```
{
  "input": "hanno@braun-odw.eu",
  "is_reachable": "unknown",
  "misc": {
    "is_disposable": false,
    "is_role_account": false
  },
  "mx": {
    "accepts_mail": true,
    "records": [
      "mxext2.mailbox.org.",
      "mxext1.mailbox.org.",
      "mxext3.mailbox.org."
    ]
  },
  "smtp": {
    "error": {
      "type": "SmtpError",
      "message": "permanent: 5.7.1 Service unavailable; Client host [54.165.232.17] blocked by RBL; https://www.spamhaus.org/sbl/query/SBLCSS / https://www.spamhaus.org/query/ip/54.165.232.17"
    }
  },
  "syntax": {
    "address": "hanno@braun-odw.eu",
    "domain": "braun-odw.eu",
    "is_valid_syntax": true,
    "username": "hanno"
  }
}
```

Relevant subset:
```
"smtp": {
    "error": {
      "type": "SmtpError",
      "message": "permanent: 5.7.1 Service unavailable; Client host [54.165.232.17] blocked by RBL; https://www.spamhaus.org/sbl/query/SBLCSS / https://www.spamhaus.org/query/ip/54.165.232.17"
    }
  },
```

Looks like they got their IP blocked:
https://check.spamhaus.org/listed/?searchterm=54.165.232.17

Maybe Lychee could emit a better error message here, or not use their service (can this check run locally?).

**Comment by mre** [comment]
@amaurym fyi
You can run it locally, but I don't think it's easy.
You can disable the email check with `--exclude-mail` as you probably know already, but that doesn't help you.

**Comment by mre** [comment]
> Maybe Lychee could emit a better error message here, or not use their service (can this check run locally?).

You're right. I've tried to improve the error message in #463. In this specific case it is still very vague as I'm getting a different error message locally than what you posted. In fact I get no error at all, and the only think that indicates that something went wrong is `CheckEmailOutput::is_reachable`, which gives me `Invalid`, which isn't correct of course. 🤷‍♀️ At least it should more details now _if_ they are available.

I'm considering to disable e-mail checking by default in the future. There are pros and cons to this, though. I think we'll leave it on for now, but keep it as an option if we see more experiences like this. 

Thanks for the bug report @hannobraun. 😃
