### ISSUE TITLE
Publish images to Docker Hub

### ISSUE THREAD

**Issue by pawroman** [lycheeverse/lychee#40]
To make the project more user friendly, and easier to integrate into existing workflows, we should add Docker image builds for releases/tags and publish them to Docker Hub.

**Comment by mre** [comment]
I registered the lycheeverse namespace on Dockerhub now so we can proceed with building the image.
Propose to base in off of alpine or debian slim. Contributions welcome.

**Comment by mre** [comment]
This one looks great: https://github.com/marketplace/actions/publish-docker

**Comment by mre** [comment]
Proposing to use Debian for the base image as it provides better perf in comparison to alpine builds, and SSL support is easier to configure according to https://blog.logrocket.com/packaging-a-rust-web-service-using-docker/.

**Comment by pawroman** [comment]
> Proposing to use Debian for the base image

Absolutely agreed. Debian slim is a great base from my experience. Can't say the same about alpine (it's a bit non-standard and causes all sorts of random issues)

**Comment by mre** [comment]
Yay, we have an official image now and the latest `master` build is already published. 🐳 
It's based on Debian slim and automatically generated whenever we push to `master` or release a new tag.
