### ISSUE TITLE
Add support for URLs without scheme/protocol

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#408]
linkify 0.8.0 was just released with an exciting new feature:

> New option url_must_have_scheme on LinkFinder that can be set to false to allow URLs without scheme/protocol such as example.com.

Changelog [here](https://github.com/robinst/linkify/blob/main/CHANGELOG.md#080---2021-11-26).

This would allow us to check even more links. 😃 
We should add support for that behind a feature flag:

* [x] Add flag `--no-scheme`, which is off by default.
* [x] If `--no-scheme` is enabled, create linkify with [the new feature](https://github.com/robinst/linkify/blob/bac4a6412a16fa44e4836a09f5dbdfba9a2da21a/demo/src/lib.rs#L5):
  ```rust
  let mut link_finder = LinkFinder::new();
  link_finder.url_must_have_scheme(!no_scheme);
  ```
* [x] Add tests

We could eventually even make this the default, although we have to do a lot of thorough testing before that.

Thanks to @robinst and @timvisee for working on this on the linkify side.

**Comment by mre** [comment]
I made some attempts to integrate this, but I hit too many false-positives unfortunately. Closing.

**Comment by robinst** [comment]
What kind of false-positives did it find? I think the feature still needs a bit of tuning so it would be helpful to know these cases. For example, maybe IP addresses should not be recognized without scheme. But in general, yeah, it's just hard to get the balance right.
