### ISSUE TITLE
Lychee fails with 503 on www.php.net

### ISSUE THREAD

**Issue by MichaIng** [lycheeverse/lychee#440]
Since a few days all links of the `www.php.net` host fail with 503, which I can replicate from different machines and locations with a single `www.php.net` URL to check. Using browsers, `curl` and `wget --spider`, GET and HEAD requests all work fine. I also tried a few other user agents and between GET and HEAD, HTTP and HTTPS with Lychee, but it keeps failing the exact same way. I'm puzzled as it is not the user agent and I can't replicate it with any other client.

Can someone replicate this and does someone have any idea how this can be and at best how to resolve it? We test thousands of links all without issues or with simple explanations when one fails, but I am out of ideas how to debug that one.

**Comment by mre** [comment]
Must be something we're doing in lychee, because `reqwest` works as expected:

```
use std::collections::HashMap;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let resp = reqwest::get("https://www.php.net").await?;
    println!("{}", resp.status());
    Ok(())
}
``` 

```
200 OK
```

Same for http://www.php.net. 
Currently don't know where the problem is. 😕 Could you try a different user-agent?

**Comment by MichaIng** [comment]
> Could you try a different user-agent?

Already done.

> I also tried a few other user agents

There must be some dark magic going on, I'm somehow eager to know what the issue is, must be an interesting or funny one  😄. I'll try to look into the code, and check packets via `tshark`.

**Comment by mre** [comment]
Any update on this btw?

**Comment by mre** [comment]
Weird. We didn't change much around checking links that could fix this. It's likely something they fixed on their end, but thanks for the update.

**Comment by MichaIng** [comment]
Issue reappeared. Not sure what they are doing 😄.

**Comment by mre** [comment]
Hum... seems to work again over here. Can you check?

```
❯❯❯ echo 'http://www.php.net' | lychee -
🔍 1 Total ✅ 1 OK 🚫 0 Errors
❯❯❯ echo 'https://www.php.net' | lychee -
🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

**Comment by MichaIng** [comment]
Still failing here with latest lychee release (in case you tested development build): https://github.com/MichaIng/DietPi-Docs/runs/5512501346?check_suite_focus=true

**Comment by MichaIng** [comment]
Still failing: https://github.com/MichaIng/DietPi-Docs/runs/5650313828?check_suite_focus=true
```
✗ [503] https://www.php.net/manual/en/index.php | Network error: Service Unavailable
✗ [503] https://www.php.net/ | Network error: Service Unavailable
✗ [503] https://www.php.net/download-logos.php | Network error: Service Unavailable
✗ [503] https://www.php.net/manual/en/getting-started.php | Network error: Service Unavailable
```

**Comment by mre** [comment]
Seems to be a Github Actions issue, though. At least for me it works locally. :/

**Comment by MichaIng** [comment]
You are right, now it works locally here as well (it did not when I opened the issue). Probably PHP explicitly blocked access for GitHub runners/IPs 🤔. I will try again with a custom user agent from GitHub actions, just to rule that out.

However, now it seems to be nothing on lychee end, so I'll close this issue. But I'll keep posting here if I find out something.
