### ISSUE TITLE
Twitter quirk stopped working

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#448]
It seems like our workaround for checking tweets doesn't work anymore.
Currently I'm getting a 429 with the Googlebot useragent.
It seems to work _sometimes_ however, indicating that it could be a temporary issue.
I asked on Twitter:
https://twitter.com/matthiasendler/status/1479224185125748737

In the meantime let's disable Twitter checking to avoid flaky builds as in #446.

**Comment by mre** [comment]
Potential workaround: use nitter.net instead.
It's a lightweight Twitter interface that works without JavaScript.
Example: https://nitter.net/matthiasendler/status/1479224185125748737

**Comment by mre** [comment]
Code is on Github: https://github.com/zedeus/nitter

**Comment by mre** [comment]
I checked the Twitter [Terms of Service](https://twitter.com/en/tos) and the [robots.txt](https://twitter.com/robots.txt) and they are fine with crawling (but not scraping i.e. storing content for a long time). Since all we do is check if a link is "up", we should be good. Apart from that, nitter.net is yet another public website for us and we can't prevent documents containing links to it anyway. I'm not a lawyer, though. 😉

**Comment by lebensterben** [comment]
well in that case we may implement those private APIs ourselves

**Comment by mre** [comment]
I'm a bit worried about long-term maintenance of that part. It's a pretty quick change to rewrite twitter.com to nitter.net. If that turns out not to be enough we can think about taking over the [api from nitter](https://github.com/zedeus/nitter/blob/master/src/api.nim), but in that case the nitter maintainers will probably be quicker to fix it if possible and I like that the logic is in one place.

**Comment by mre** [comment]
nitter gave me some "over quota" issue lately. I'm not sure if it's a good replacement for Twitter links, but it's still better than nothing.
