### ISSUE TITLE
Don't check for email addresses in verbatim code

### ISSUE THREAD

**Issue by norswap** [lycheeverse/lychee#471]
Small thing, but with this input:

```
    go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
```

(So this instruction in a markdown code code block.)

you get lychee output:

> ✗ github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0 (Unreachable mail address: github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0)

Which is obviously not the desired outcome. Verbatim blocks should probably be ignored.

**Comment by lebensterben** [comment]
This is a bug obviously...

**Comment by mre** [comment]
@norswap thanks for the bug report. This is an issue in linkify. https://github.com/robinst/linkify/issues/29
@lebensterben good input. Is there a spec where these rules are defined? Can you mention it in the linkify issue above?

**Comment by mre** [comment]
In general I think the verbatim part is fine but the e-mail address detection needs to be improved. This line would not show up if the false-positive was filtered out correctly.

**Comment by mre** [comment]
Excluding code blocks will be tackled in #523.

**Comment by mre** [comment]
This gets ignored in the latest `master` now. 🎉 
If I have an input file like this called `test.md`:

<pre>
Some content.
```
go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0
```
Other test content
</pre>

and I call lychee, the code block will be ignored by default:


```
❯❯❯ lychee test.md
🔍 0 Total ✅ 0 OK 🚫 0 Errors
```

The old behavior can be restored with `--include-verbatim`:

```
❯❯❯ lychee --include-verbatim test.md
Issues found in 1 input. Find details below.

[test.md]:
✗ [ERR] github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0 | Unreachable mail address: github.com/golangci/golangci-lint/cmd/golangci-lint@v1.43.0: Invalid: Email doesn't exist or is syntactically incorrect

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```
