### ISSUE TITLE
Option to ignore hubcaps failures

### ISSUE THREAD

**Issue by DanySK** [lycheeverse/lychee#474]
Hi,
I'm using lychee to check link integrity for a whole website.
Does the tool check the same link multiple times? Despite providing a valid token, I get many:

```
✗ http://github.com/<foo>: Network error (hubcaps)
```

That I would not expect.

Is there a way to tell lychee to ignore these errors?
Something like `--ignore-error=429` would be great.

Alternatively or in addition, would it be possible to wait and retry after a 429?
Something like `--wait-after-cap=60` to retry links after a minute if the cap has been reached.

**Comment by mre** [comment]
You can use
```
lychee --accept 200,429 ...
```

We should make the retry interval configurable. It's currently making three attempts and waits 1, 2, and 4 seconds respectively between each retry.
The goal is to use [tower](https://github.com/tower-rs/tower) to write a service around the client in the long run and properly handle rate limiting and backoff there.

* https://github.com/lycheeverse/lychee/issues/367
* https://github.com/lycheeverse/lychee/issues/36

**Comment by mre** [comment]
@DanySK did this fix your issue?

**Comment by DanySK** [comment]
Partly: it can skip 429 entirely, but retry count and timeout can't be set.

**Comment by mre** [comment]
True, we should make those configurable. I just keep forgetting to do it. 😅

**Comment by mre** [comment]
The retry count is already configurable through `--max-retries`, the timeout can be configured with `--timeout` and for the wait time between requests I created a pull request at #525.

**Comment by mre** [comment]
`--retry-wait-time` is in `master` now. Let me know if that solves your problem @DanySK. 😊

**Comment by mre** [comment]
A proper solution would be https://github.com/lycheeverse/lychee/issues/36, with which we track the individual state of every website. This way we avoid overloading the servers and can do proper rate-limiting by parsing the respective headers and storing them in the website state.
For now, increasing the `--retry-wait-time` should at least help in simple cases.

**Comment by DanySK** [comment]
I'm waiting for the option to hit docker hub, as soon as it does I'll try it out

**Comment by mre** [comment]
Hum... it should already be in.
Did you try
```
docker pull lycheeverse/lychee:master
```
I'm away from my computer so I can't verify.

**Comment by DanySK** [comment]
I am using `latest`, which I guess points to the latest stable then?

**Comment by mre** [comment]
Guess we can close this. `latest` should have the changes and the next release of lychee will as well. Using tower for retries is tracked in #36.
