### ISSUE TITLE
Windows Setup: lychee-v0.8.2-windows-x86_64.exe doesn't do anything

### ISSUE THREAD

**Issue by san-ouadghiri** [lycheeverse/lychee#478]
Here is what I did
- I downloaded lychee-v0.8.2-windows-x86_64.exe
- Double clicked on it

I see a window open and close super fast (like a killed cmd maybe?). Nothing seems to actually happen.
After that, my system doesn't recognize the 'lychee' term so I guess the setup did not occured. I tried running the .exe 'as admin' with no greater success.

Did I miss something?
Linked to https://github.com/lycheeverse/lychee/issues/59.

**Comment by san-ouadghiri** [comment]
Yeah I get that. But my system doesn't recognize "lychee" as a program. I guessed after double clicking on the exe that would be a recognized cmd.
Am I wrong?

I setup the tar.gz on my wsl but I'm still interestzd on making it work on Windows.

**Comment by lebensterben** [comment]
> I guessed after double clicking on the exe that it would be a recognized cmd. Like unfolding a folder somewhere and add the command to the $Path and... am I wrong?

Wrong.

> But my system doesn't recognize "lychee" as a program (if I do lychee --help for example).

You need to specify the full path to the binary or put it in your PATH.

**Comment by san-ouadghiri** [comment]
Oh ok got it.
So indeed doing a 
 `.\lychee-v0.8.2-windows-x86_64.exe --help`
 
Works just fine. As nothing is documented on the README.md around those I just assumed a lot of things.
Thanks for the feedback @lebensterben.
