### ISSUE TITLE
Failing on invalid URI

### ISSUE THREAD

**Issue by tjperry07** [lycheeverse/lychee#483]
If it encounters an invalid URI, it would be nice if it just returned it as an error instead of failing the entire link check itself.

Further research, it failed on an iframe link. I set it to exclude the link `--exclude www.loom.com --exclude https://www.loom.com --exclude loom.com` but it still picks up in it. The link is valid. 

```
thread 'tokio-runtime-worker' panicked at 'a parsed Url should always be a valid Uri: InvalidUri(InvalidUriChar)', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.8/src/into_url.rs:70:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Cannot send request: SendError(Ok(Request { uri: Uri { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("www.loom.com")), port: None, path: "/embed/6982a6dd9a984765b9c7c969a40af06e", query: None, fragment: None } }, source: FsPath("src/docs/user-experience/scheduler/creating-and-scheduling/schedule-editor.md"), element: N✔ https://docs.nylas.com/reference#account-sync-status [200 OK]

```

**Comment by mre** [comment]
This is an known issue in reqwest and there is an open pull request for it: https://github.com/seanmonstar/reqwest/pull/1399. Sadly very little traction.

We might want to support different http clients in the future like [isahc](https://crates.io/crates/isahc), [attohttpc](https://github.com/sbstp/attohttpc), [surf](https://github.com/http-rs/surf), or [h2](https://github.com/hyperium/h2).

**Comment by tjperry07** [comment]
Thanks for letting me know. I'll close this one since there is already an issue open.

**Comment by tjperry07** [comment]
Also related https://github.com/seanmonstar/reqwest/issues/668
