### ISSUE TITLE
lychee fails to check Twitter links

### ISSUE THREAD

**Issue by MichaIng** [lycheeverse/lychee#484]
Today I recognised:
```
✗ https://twitter.com/: Network error while trying to connect to an endpoint via reqwest
```
Tested v0.8.2 on different machines/architectures with different Debian and Ubuntu versions, different user agents and connection methods (HEAD and GET), all fail the same way. This affects all `https://twitter.com` URLs, not just the root.

Has someone recognised the same?

**Comment by mre** [comment]
Yes. See https://github.com/lycheeverse/lychee/issues/448.
Closing this as duplicate. 😉

**Comment by mre** [comment]
Basically the quirk stopped working because Twitter changed something on their end. Looks like the Google User Agent itself got rate-limited.
