### ISSUE TITLE
tracking issue: support local, link-local for ipv6

### ISSUE THREAD

**Issue by lebensterben** [lycheeverse/lychee#498]
`lychee` currently supports excluding private IP or link-local IP for IPv4.

They're not supported for Ipv6 addresses because the current implementation relies on `std::net` which doesn't have them on stable channel. See https://docs.rs/ip_network/latest/ip_network/struct.Ipv6Network.html#method.is_unicast_global and https://doc.rust-lang.org/stable/std/net/struct.Ipv6Addr.html#method.is_unicast_link_local

Fortunately, we can temporarily use https://docs.rs/ip_network/latest/ip_network/struct.Ipv6Network.html until https://github.com/rust-lang/rust/issues/27709 is stablized.

- [x] Implementation. (#501).
- [x] Adding tests.

**Comment by mre** [comment]
I took the freedom to close this as #501 is merged including tests. 🎉 Thanks for implementing this.
