### ISSUE TITLE
tracking issue: replace hubcaps by octocrab

### ISSUE THREAD

**Issue by lebensterben** [lycheeverse/lychee#499]
[hubcaps](https://lib.rs/crates/hubcaps) hasn't received release updates for 2 years. We currently relies on it master branch as dependency which is not reliable enough since it might stop building anytime should there be any upstream API changes.

I will make a PR to replace it by [octocrab](https://lib.rs/crates/octocrab).

**Comment by mre** [comment]
Thanks. Reference to your PR: #502.

**Comment by lebensterben** [comment]
Closing since it's merged.
