### ISSUE TITLE
RFE: Introduce parameter which will skip checking URLs in Markdown code section

### ISSUE THREAD

**Issue by ruzickap** [lycheeverse/lychee#521]
Hello.

I have in my README "markdown" file this code section, which is reported by lychee as non-working URL:

```bash
  PACKER_LATEST_VERSION="$(curl -s https://checkpoint-api.hashicorp.com/v1/check/packer | jq -r -M '.current_version')"
  curl "https://releases.hashicorp.com/packer/${PACKER_LATEST_VERSION}/packer_${PACKER_LATEST_VERSION}_linux_amd64.zip" --output /tmp/packer_linux_amd64.zip
```

See the example:

```text
$ lychee README.md
Issues found in 1 input(s). Find details below.

[README.md]:
✗ https://releases.hashicorp.com/packer/$%7BPACKER_LATEST_VERSION%7D/packer_$%7BPACKER_LATEST_VERSION%7D_linux_amd64.zip: Network error while trying to connect to an endpoint via reqwest
```

Would it be possible to introduce the new parameter to lychee which will skip checking URLs in Markdown code section?

Thank you for considering it...

**Comment by mre** [comment]
> Would it be possible to introduce the new parameter to lychee which will skip checking URLs in Markdown code section?

Yes, and it should probably be on by default.
Code blocks are rarely something that users want to check it seems.

The code for it is here: https://github.com/lycheeverse/lychee/blob/master/lychee-lib/src/extract/markdown.rs.
Actually I wonder why code blocks aren't excluded at the moment. There is a [CodeBlock tag](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/enum.Tag.html) in pulldown_cmark, but we don't match on that. The only thing I can think of is that the code block doesn't get properly recognized as a tag by the parser and instead becomes an `Event::Text` or `Event::Html`. What am I missing here?

Can you paste the content around the code section here for reference?

**Comment by ruzickap** [comment]
Here is the test case:

```bash
wget -q https://raw.githubusercontent.com/ruzickap/action-test2/main/test.md
lychee test.md
```

Output:

```text
# wget -q https://raw.githubusercontent.com/ruzickap/action-test2/main/test.md
# lychee test.md
Issues found in 1 input(s). Find details below.

[test.md]:
✗ https://releases.hashicorp.com/packer/$%7BPACKER_LATEST_VERSION%7D/packer_$%7BPACKER_LATEST_VERSION%7D_linux_amd64.zip: Network error while trying to connect to an endpoint via reqwest

🔍 2 Total ✅ 1 OK 🚫 1 Error (HTTP:1)
```

**Comment by mre** [comment]
Thanks for the test case. See https://github.com/lycheeverse/lychee/pull/523 for a potential fix.

**Comment by ruzickap** [comment]
Thank you for a quick response...

I'll leave it up to you to find the "best" solution... 

I only reported the problem, but it looks like everybody agrees to skip checking URLs inside code block by default...

**Comment by mre** [comment]
That is true, we agreed on that part at least. 😄 The tricky thing is usually how to implement it so it won't become a maintenance burden down the road.

**Comment by mre** [comment]
This is done now. I just forgot to update this issue.

```
wget -q https://raw.githubusercontent.com/ruzickap/action-test2/main/test.md
lychee test.md
🔍 0 Total ✅ 0 OK 🚫 0 Errors
```
