### ISSUE TITLE
Print errors with a different format for easier clickability

### ISSUE THREAD

**Issue by DanySK** [lycheeverse/lychee#532]
Hi, lychee currently prints errors this way:

![image](https://user-images.githubusercontent.com/1991673/156179338-f4407fa9-ebc2-40ad-9500-661c5e607be2.png)

```
[/website/explanation/sapere/index.html]:
✗ https://doi.org/10.1109/MC.2015.261: Network error (reqwest): HTTP status server error (503 Service Unavailable) for url (https://ieeexplore.ieee.org/document/7274429/)

[/website/tutorials/basics/index.html]:
✗ https://doi.org/10.1109/FAS-W.2017.116: Network error (reqwest): HTTP status server error (503 Service Unavailable) for url (https://ieeexplore.ieee.org/document/8064092/)
✗ https://doi.org/10.1109/fas-w.2017.116: Network error (reqwest): HTTP status server error (503 Service Unavailable) for url (https://ieeexplore.ieee.org/document/8064092/)
```

However, printing `URL:` has a drawback: many IDEs or logging systems (included GitHub actions) make the colon part of the link, and thus when clicking the URL does not work directly. I suggest the adoption of a slightly different format:

```
✗ https://doi.org/10.1109/fas-w.2017.116 >> Network error (reqwest): HTTP status server error (503 Service Unavailable) for url (https://ieeexplore.ieee.org/document/8064092/)
```
(or any separator beginning with whitespace, really hereby including a single whitespace)

This would disrupt scripts that parse the output of lychee, however, I think that it is a change worth implementing (it took me a few minutes to realize that the site was up again, but I was visiting it with the colon at the end).

**Comment by mre** [comment]
PR up here: #533

**Comment by DanySK** [comment]
That is very nice.

**Comment by mre** [comment]
This is merged now and will be part of the `lycheeverse/lychee:master` image in a second.
It will go live with the next release, which shouldn't be too far away.
Thanks for the improvement suggesion @DanySK. 😃

**Comment by DanySK** [comment]
Thank you for this lovely tool, my static websites finally quit being deployed with dangling links.

**Comment by mre** [comment]
Which static site generator do you use if I may ask? We should eventually propose to add lychee to [zola](https://github.com/getzola/zola), which has their own.

**Comment by DanySK** [comment]
Hugo. Huge theme gallery, fast, well organized.
