### ISSUE TITLE
Add support for domain remapping URLs to custom endpoints (schema-IP-port)

### ISSUE THREAD

**Issue by cipriancraciun** [lycheeverse/lychee#547]
`lychee` would also be great to test web servers prior to production deployment.

Say one has a HTTP server that runs on `127.0.0.1:8080`, but when it will be put into production it would actually serve `https://example.com/`.  Also say that, due to developer laziness, the web server, even in development mode, has links that use the production domain (i.e. `example.com`).

Thus it would be useful to instruct `lychee` that whenever it sees `https://example.com` it should instead make a HTTP (without TLS) call to `127.0.0.1:8080`.

To generalize, there should be the possibility to remap any HTTP/HTTPS endpoint to another HTTP/HTTPS endpoint, like for example:

~~~~
--remap-url 'https://example.com http://127.0.0.1:8080'
--remap-url 'https://example.com https://staging.example.com'
~~~~

Perhaps the first part (i.e. `https://example.com`) could be a regex to support a more generic use-case.

Also, this feature could also be used to proxy certain requests through certain proxies.

**Comment by lebensterben** [comment]
We should add a restriction that remapping rules only accept scheme + authority.

So https://john@foo.example.com:1234 is valid

But https://foo.example.com/bar is not.

**Comment by mre** [comment]
Why the restriction?

**Comment by lebensterben** [comment]
@mre 
we won't want people to abuse this feature. A huge set of remapping rules may causes performance issue. Or rules themselves may conflict with each other.

**Comment by cipriancraciun** [comment]
> We should add a restriction that remapping rules only accept scheme + authority.
> we won't want people to abuse this feature. A huge set of remapping rules may causes performance issue. Or rules themselves may conflict with each other.

Indeed allowing one to remap anything more than the origin (scheme+host+port) might easily get one in trouble by obtaining hard to debug outcomes.

However, if one says that the first mapping rule applies, and no other remappings are executed afterwards, then the semantic is clear and easy to reason about.

Moreover, allowing the remapped-to URL to contain also a path could allow one to test sites where in production a HTTP router (like HAProxy) does rewrite paths to prepend a given prefix.

However, if paths are allowed in remappings, perhaps a more useful use-case is removing path prefixes (the reverse of the previous paragraph).

But this semantic gets quickly complicated, so at least at first, I agree that remapping should be limited only to the origin part (scheme+host+ip).

**Comment by mre** [comment]
> Indeed allowing one to remap anything more than the origin (scheme+host+port) might easily get one in trouble by obtaining hard to debug outcomes.

It's one of the cases where users decided to add that complexity for themselves, though.
People will probably find a way to get in trouble this way or another. 😅

As a user, I might get confused about this behavior for more complex patterns without finding and reading that part of the documentation and from an implementation perspective allowing any sort of rewrite is easier, because we won't have to parse (scheme+host+port) and potentially introduce rewrite bugs along the way.
If the first match always wins (and we'd document that), it might provide a good trade-off between simplicity and flexibility.

**Comment by lebensterben** [comment]
let's just keep it simple.
It's always easy to add supports than removing features.

**Comment by aj-stein-nist** [comment]
> let's just keep it simple. It's always easy to add supports than removing features.

Does that mean the simple version of this feature request is supported by the devs then? This seems to be the only feature of `markdown-link-check` without parity that is stopping me from recommending to my tech lead we deprecate MLC from our pipeline. (Context in https://github.com/usnistgov/OSCAL/issues/1230#issuecomment-1122433634)

**Comment by mre** [comment]
@cipriancraciun @lebensterben, see https://github.com/lycheeverse/lychee/pull/620 for an implementation of what we discussed. Open for feedback.

**Comment by mre** [comment]
This got merged to `master` now. Thanks y'all for your input and @cipriancraciun for creating the issue.
