### ISSUE TITLE
Should automatically exclude example.[com|net|org]

### ISSUE THREAD

**Issue by johnstonskj** [lycheeverse/lychee#551]
These domains are explicitly defined by [RFC 2606](https://datatracker.ietf.org/doc/html/rfc2606), section 3 _Reserved Example Second Level Domain Names_ for describing example cases and should not be dereferenced as they should not have content.

It also describes a set of TLDs in section 2 _TLDs for Testing, & Documentation Examples_ that should be excluded, although I'm not sure about ".localhost".

**Comment by mre** [comment]
Innnteresting. Never thought of that.
We list a few exclusions here. It's a list of regexes. Wanna whip up a PR for that? ☺️ 
https://github.com/lycheeverse/lychee/blob/master/lychee-lib/src/filter/mod.rs#L12

**Comment by lebensterben** [comment]
they should just be skipped entirely, not being tested and not shown in output. And that's different from "false positive".

**Comment by mre** [comment]
Indeed. It's the wrong location then.

**Comment by mre** [comment]
Note to self:
For testing, we have to include example.* domains. One way to do this is to overwrite the config (pseudocode):

```rust
#[cfg(not(test))]
static HIDDEN_DOMAINS: &'static [&str] = &["example.com", "example.org", "example.net"];

#[cfg(test)]
static HIDDEN_DOMAINS: &'static [&str] = &[];
```

**Comment by mre** [comment]
Merged to `master` now.

**Comment by mre** [comment]
Thanks a lot for the suggestion @johnstonskj. 👍
