### ISSUE TITLE
When the next lychee version will come?

### ISSUE THREAD

**Issue by Rizwan-Hasan** [lycheeverse/lychee#558]
We're using lychee action v1.3.2 which uses the latest lychee v0.8.2. And faced a weird issue related to hubcaps.
From this PR [#502](https://github.com/lycheeverse/lychee/pull/502) it's clear that lychee already replaced hubcaps with octocrab and it's a great decision. But the latest lychee version still uses hubcaps. So, we desired to know when the next lychee release will happen with the changes of replacing hubcaps?

**Comment by mre** [comment]
Hi, I can create a new release and bump lychee-action afterwards.
What issue did you face with hubcaps?

**Comment by Rizwan-Hasan** [comment]
That's the error. And we've faced it on several workflow runs. But it also fixed automatically without any config changes.
And the time we were facing the issue all the links were valid but it's giving this error for many urls.

`2022-03-21T16:16:42.4021715Z ✗ https://github.com/allegroai/clearml/blob/master/examples/reporting/matplotlib_manual_reporting.py: Network error when trying to connect to an endpoint via hubcaps`

**Comment by mre** [comment]
Huh, then it wasn't a hubcaps issue. The local test worked on my machine (see above), so it's either a problem with lychee-action or with the pipeline. Is the Github action workflow file public so that I can have a look? And we should probably move that discussion to https://github.com/lycheeverse/lychee-action instead. Could you create a new issue there? 😉

**Comment by mre** [comment]
Some checks:
* Do you see other errors or is that the only one? Specifically, any 429 errors?
* Do you have any other Github links which work? If not, can you add one to check?
* Did you set a Github token as described in the lychee-action docs? https://github.com/lycheeverse/lychee-action#usage
   (This is only necessary if you get a 429 somewhere.)

**Comment by Rizwan-Hasan** [comment]
### Here some Github links that are working fine,

✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/click [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/hydra [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/kerastuner [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/scikit-learn [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/tensorboardx [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/autokeras [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/services/monitoring [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/fastai [200 OK]
✔ https://github.com/allegroai/clearml/tree/master/examples/frameworks/keras [200 OK]

**Comment by Rizwan-Hasan** [comment]
Here's the issue I've created on lyche-action [lycheeverse/lychee-action/issues/97](https://github.com/lycheeverse/lychee-action/issues/97)
