### ISSUE TITLE
v0.9.0 regression: Cached URLs are printed without verbosity flag

### ISSUE THREAD

**Issue by MichaIng** [lycheeverse/lychee#563]
Like:
```
↻ [200] https://dietpi.com/ | OK (cached)
↻ [200] https://golang.org/ | OK (cached)
```
Since without verbosity flag, (successfully) checked URLs are not printed, they shouldn't be printed when cached before either. But otherwise it's nice to see the cache working 👍🙂 .
_________
Just to leave the kudos somewhere: Great that URLs in the log are not printed with trailing colon `:` anymore. GitHub always added it to the link, to quickly checking failed links in the browser by clicking the link in the log didn't work, now it does 👍🙂 .

**Comment by mre** [comment]
Fixed in https://github.com/lycheeverse/lychee/pull/570. Thanks for the report.

**Comment by MichaIng** [comment]
Many thanks 👍🙂.
