### ISSUE TITLE
Support JSON input files

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#579]

**Comment by lebensterben** [comment]
what's the example use case?

**Comment by mre** [comment]
This post on HN: https://news.ycombinator.com/item?id=30903246
Even though I think it's already supported. The linked JSON file just contains URLs without a schema and that's why it didn't work out of the box when I tried it. It does work when I prefix every URL with `https://`.
Just created this issue so that we don't forget to talk about it.

**Comment by mre** [comment]
Closing this because I think it works.
