### ISSUE TITLE
Does lycheeignore file supports commenting?

### ISSUE THREAD

**Issue by Rizwan-Hasan** [lycheeverse/lychee#585]
Something like this using hash
```
http[s]?://s3\.amazonaws\.com.*
http[s]?://github\.com/.*/issues/.*
http[s]?://github\.com/.*/pull/.*
# http[s]?://.*\.linkedin\.com/.*
```

**Comment by Rizwan-Hasan** [comment]
I've just checked and doesn't support comments.

**Comment by lebensterben** [comment]
I don't think so. But this can be easily supported.

**Comment by Rizwan-Hasan** [comment]
Accidentally closed the issue!

**Comment by lebensterben** [comment]
I suggest to follow

https://git-scm.com/docs/gitignore#_pattern_format

So space is not required after hash for comment.
For tags, it should be written as \#some-tag

**Comment by mre** [comment]
Opened a PR at https://github.com/lycheeverse/lychee/pull/616 if you want to have a look @Rizwan-Hasan, @lebensterben.

**Comment by mre** [comment]
This got merged to `master` now.
