### ISSUE TITLE
[Help] Is there any way to dump the excluded links?

### ISSUE THREAD

**Issue by Rizwan-Hasan** [lycheeverse/lychee#587]
Using the `--dump` we can get all the links extracted from inputs that would be checked.
Is there any way to get the excluded links also?

**Comment by lebensterben** [comment]
I think you can extract it from json output with jq.

**Comment by Rizwan-Hasan** [comment]
I've tried with `--format json` , it's giving me failed links with statistics or only statistics (if nofail). But not giving excluded links.

**Comment by mre** [comment]
There is #268, where we could add the excluded links maybe.
Perhaps we should dump the excluded links if the `--verbose` flag is set? That feature would not be easy to discover, though. Alternatively we could use `--dump-excluded`, but it feels like it's a niche use-case and I don't want to clutter the help output with too many special cases.

If we can find a straightforward way to do it, I'm all for adding that functionality. Open for suggestions.

**Comment by mre** [comment]
Well _actually_ we could just append `[excluded]` to every excluded link when using `--dump`. 🤔 
Similar for cached links etc. Then you could just grep for that. @lebensterben what do you think?

**Comment by lebensterben** [comment]
@mre 
We might as well include reason for exclusion, at least for verbose output.

**Comment by mre** [comment]
I went ahead and merged this to `master`.
The reason for exclusion would require more work and it's debatable if
it adds any value, because it might make grepping harder and the source
of exclusion is easily deducatable from the commandline parameters
or the `.lycheeignore` file, so I skipped that for now.
