### ISSUE TITLE
Do not check links that contain wildcards in CSP rules

### ISSUE THREAD

**Issue by jiazengp** [lycheeverse/lychee#604]

**Comment by mre** [comment]
Some clarification: the asterisk character is valid and serves as a wildcard operator, which stands for any number of characters. So https://foo.example.com and https://bar.example.com would both match https://*.example.com. The question is if URLs with wildcard operators should count as valid links as per the definition of linkify. I've opened an issue for clarification whether this is something we should handle on our end or inside linkify: https://github.com/robinst/linkify/issues/37.

**Comment by lebensterben** [comment]
* is a valid character for both host and path.

**Comment by lebensterben** [comment]
things like https://*.yuanshen.site should be wrapped in pre tags since it's never intended to be a URL, but an example.

**Comment by mre** [comment]
The meta tag that OP posted is valid (according to https://wiki.mozilla.org/Security/CSP/Specification) and not wrapped in a pre tag, though. We could ignore meta tags, but I think we shouldn't.

**Comment by jiazengp** [comment]
I also think so

**Comment by mre** [comment]
Work is done in linkify to fix this issue: https://github.com/robinst/linkify/pull/43

**Comment by mre** [comment]
This is fixed now, thanks to the awesome work by @robinst in https://github.com/robinst/linkify/pull/43.
I'm no longer getting any wildcard URLs in your example:

```
✗ [404] https://b.alicdn.com/ | Failed: Network error: Not Found
✗ [403] https://widget.heweather.net/ | Failed: Network error: Forbidden
✗ [403] https://at.alicdn.com/ | Failed: Network error: Forbidden
✗ [403] https://widget.qweather.net/ | Failed: Network error: Forbidden
✗ [ERR] https://cdn.heweather.com/ | Failed: Network error: dns error: no record found for Query
```

@jiazengp, I'm not sure if this is still a problem for you, but if it is, the latest version should have the fix.
