### ISSUE TITLE
Lychee expects string for accepted status codes

### ISSUE THREAD

**Issue by vipulgupta2048** [lycheeverse/lychee#644]
With #636, Lychee add support for parsing status code using v0.10.0 I am getting the error 

```
➜  docs git:(vipul/update-lychee) ✗ lychee --version
lychee 0.10.0
➜  docs git:(vipul/update-lychee) ✗ lychee --config ./lychee.toml "README.md"
Error: invalid type: sequence, expected a string for key `accept` at line 1 column 1
```

When I am specifying status codes like:

```
# Comma-separated list of accepted status codes for valid links.
accept = [200, 301, 429]
```

The error goes away when I specify status codes as string which was the old format. I am trying to read the PR and make a patch for this. I feel like the `parse_statuscodes` function still expects string but not completely sure how the tests would have been passing then.

**Comment by mre** [comment]
Latest lychee with these changes wasn't released yet. 😉 It will be part of 0.11.0 since it's a breaking change. For now you need to use a string, yes. I can't remember if the current `master` still supports a string as an argument, though. If not, we could add that to make it backwards compatible.

**Comment by vipulgupta2048** [comment]
Thanks, I should have checked the releases first to make sure if v0.10.0 includes this change or not. My bad. Closing.

**Comment by mre** [comment]
No worries. 😆

**Comment by vipulgupta2048** [comment]
@mre Although I want to ask what the expected outcome is of having an accepted status code. Referring to #634, I have added 429 to accepted status codes, but the report and result still list Too many network request errors. Is that supposed to be expected? Check out my config here https://github.com/balena-io/docs/pull/2317

**Comment by mre** [comment]
Hum... it should work like you specified it and it should accept 429 as a valid status code. Not sure what's up with that. Can you try to pass `--accept 200,204,301,429` in the `args`? Maybe the config option doesn't get properly merged in.

**Comment by mre** [comment]
Okay then our merging is borked. I think we wanted to switch to https://github.com/mehcode/config-rs for config merging, but I can't remember the crate anymore and I can't find the issue. PRs to fix this are very welcome. I'll keep this open for now.

**Comment by mre** [comment]
@vipulgupta2048 can you test the latest `master`? I tested it locally and it merging works as expected for me. (In my test I overwrote the accepted status code by using a custom config file and it worked.)

**Comment by mre** [comment]
My config:
```toml
# Comma-separated list of accepted status codes for valid links.
accept = [200, 429]
```

**Comment by mre** [comment]
For the record, we could move to config-rs once clap is supported (https://github.com/mehcode/config-rs/issues/328)

**Comment by vipulgupta2048** [comment]
Thanks @mre, I was out on vacation so couldn't act on this. I tried building master v0.10.1, tested and it works as expected. Made a PR to get this change merged. Closing the issue.

**Comment by vipulgupta2048** [comment]
Hey @mre can you release a new patch of the lychee action? Having v0.10.1 inside?

**Comment by tooomm** [comment]
> Hey @mre can you release a new patch of the lychee action? Having v0.10.1 inside?

@vipulgupta2048 lychee v0.10.1 is already the default since [lychee-action v1.5.1](https://github.com/lycheeverse/lychee-action/releases/tag/v1.5.1) released a few weeks ago.
