### ISSUE TITLE
Mailto urls with query parameters incorrectly converted to file urls

### ISSUE THREAD

**Issue by egrieco** [lycheeverse/lychee#653]
Lychee seems to incorrectly convert `mailto:` links with query parameters into `file://` links.

`mailto:user@example.com?subject=Hello` becomes `file:///LOCAL/PATH/mailto:user@example.com`

The actual link to check (when checking emails) is `mailto:user@example.com`.

**Comment by mre** [comment]
Can you provide some more info here? What's the input file format you're using? Can you provide a minimal failing test case?

I tried it locally, but I can't reproduce:

```
echo "this is a mailto:user@example.com?subject=Hello link" | lychee -- --dump -
user@example.com
```

**Comment by mre** [comment]
Also see https://github.com/lycheeverse/lychee/pull/655.

**Comment by egrieco** [comment]
> Can you provide some more info here? What's the input file format you're using? Can you provide a minimal failing test case?

I was running this on the output of a Zola static website. The actual email address was different.

I'll try to put a test case together that shows off the behavior. I was running with the `--offline` flag. My intuition is that this doesn't happen with `--dump`.

**Comment by egrieco** [comment]
Actually, it does show the same behavior with `--dump`. The error occurs when reading from a full HTML file. I could not reproduce it by echoing just the `p` tag on line 10 from the attached files to lychee.

```zsh
$ lychee ~/Desktop/lychee-test-working.html --dump
user@example.com
```

```zsh
$ lychee ~/Desktop/lychee-test-broken.html --dump
file:///Users/egrieco/Desktop/mailto:user@example.com
```

A `.txt` extension has been added to the files since apparently you cannot attach HTML files to GitHub issues.

* [lychee-test-working.html.txt](https://github.com/lycheeverse/lychee/files/8931224/lychee-test-working.html.txt)
* [lychee-test-broken.html.txt](https://github.com/lycheeverse/lychee/files/8931225/lychee-test-broken.html.txt)

**Comment by egrieco** [comment]
P.S. I'll take a look at the code and try to issue a pull request with the fix, but that may not happen for a bit as I have a backlog of other tasks that I need to work through first. ☹️

**Comment by Stargator** [comment]
@mre There's a mailto link in [this Code of Conduct](https://github.com/exercism/dart/blob/main/CODE_OF_CONDUCT.md) that is being flagged.

The contents of the link is `mailto:abuse@exercism.org?subject=%5BCoC%5D`

**Comment by Stargator** [comment]
Update, I see now we are behind. We are using version 1.4.1. I'll update and see if that fixes things for us.

**Comment by Stargator** [comment]
@mre I hope my updates above were helpful in seeing this issue was affecting a repo.

**Comment by Stargator** [comment]
I noticed version 1.5.2 was released, [re-ran the workflow and the issue still persists](https://github.com/exercism/dart/actions/runs/3393867720/jobs/5641709186).
