### ISSUE TITLE
`--skip-missing` hangs until timeout on relative path arg, despite file not existing

### ISSUE THREAD

**Issue by polarathene** [lycheeverse/lychee#660]
When providing a relative path, I wasn't aware at the time the path was invalid (_wrong git branch, file did not exist_).
- I was testing with `--dump` prior, so I was a bit confused why `lychee` was attempting to make a network request in the first place..
- As a new user `--offline` seemed like it might have been a workaround (before I realized the issue was the file not existing, not content).
- `--skip-missing` was the actual option I should have used, although I'm not sure if `lychee` should have attempted to do such an HTTP request when the file was missing?
  - I guess some environments may have single label DNS hostnames other than `localhost` if they've got their local resolver appending a search domain(s), so maybe assuming it's a query like `example.com/path`/`localhost/path` is correct..

Example:

```console
$ lychee --offline 'path/to/file.md'
Error: Network error

Caused by:
    0: error sending request for url (http://path/to/file.md): error trying to connect: dns error: no record found for name: path. type: AAAA class: IN
    1: error trying to connect: dns error: no record found for name: path. type: AAAA class: IN
    2: dns error: no record found for name: path. type: AAAA class: IN
    3: no record found for name: path. type: AAAA class: IN
```

So that issue probably isn't a bug, and just requires the user to be aware of the difference in `--offline` (links found) and `--skip-missing` (files to parse).

I have tested `--skip-missing` with a local webserver with input arg `localhost/index.html`. If the server isn't running, nothing is output, and if it is running, it does make the request to process. I haven't set up a local DNS service to view logs, but I assume `--skip-missing` is still making DNS requests for invalid files based on that, just ignoring the errors?

Is there presently no option of assuming relative file paths for `lychee` args, avoiding the DNS queries if no file is found? Only making requests when an appropriate scheme for the arg value is present (eg `http://`/`https://`?)

---

A related issue I experienced was when I tried to add a hint to `lychee` that this really was a relative file path:

```console
$ lychee --skip-missing './path/to/file.md'
⠒ 0/0 [00:00:29] █████████████████████████ Extracting links

# Later times out with output:
🔍 0 Total ✅ 0 OK 🚫 0 Errors
```

That times out after 30 seconds, but it seems it should have known to skip much earlier? Any ideas why the behaviour differs due to `./`? (_I guess this is more explicit as a local/relative file path, but perhaps the timeout is an attempt to make a remote request/lookup_)

When using `--dump`, the `./` prefix results in the same behaviour, minus the "Extracting links" line (instead a line with a single "█" is visible).

**Comment by polarathene** [comment]
For reference, this is the current README descriptions for the related options:

```
--offline                Only check local files and block network requests
--skip-missing           Skip missing input files (default is to error if they don't exist)
```

`--offline` perhaps should have worked in this context and avoided attempts to make a request for `lychee` input args? 
- `--skip-missing`: I assume this is relevant if you have mixed inputs to check, but `--offline` could make irrelevant if only checking local files? Unless with `--offline` (and no `--skip-missing`) it would actually throw an error that the file doesn't exist, rather than the DNS error presently logged.
- Without the protocol scheme prefix, `localhost:80/index.html` would also fail with an error about an unsupported scheme. Doesn't bother me, just thought that was worth noting as it appears to be trying to infer the scheme before attempting file/http request (`--skip-missing`, will avoid the error and skip it however).

**Comment by mre** [comment]
`--offline` is misleading. I think a better name would be `--include-local` or maybe even remove it altogether and only check if `--base` is provided.
I also didn't anticipate that we do a network request on such inputs. Files with slashes before the dot are unlikely to be proper domains. Wouldn't be surprised if those inputs were actually completely valid URLs, but I haven't checked. :smile:

**Comment by mre** [comment]
Yes, as you mentioned `--skip-missing` is still making network requests; it just ignores missing inputs if they aren't available.

**Comment by mre** [comment]
The long timeout delay for local files is definitely odd. It should be instant. We should fix that. Could you create a separate issue for that if you have time?

**Comment by mre** [comment]
Thanks for testing lychee and finding these bugs. I will go through the list once I find some time. We should create individual issues for them such that contributors could work on them independently.

**Comment by polarathene** [comment]
> The long timeout delay for local files is definitely odd. It should be instant. We should fix that. Could you create a separate issue for that if you have time?

It is instant, but only if the input value is `path/to/file`, not `./path/to/file`. The 2nd half of the original issue report details that difference.

It is not dependent upon `--skip-missing` option. `./README.md` works fine if the file exists locally, otherwise it will timeout (presumably it's attempting to make a request).

I'm not sure why it times out, the DNS lookup failures are immediate, but that may be due to no `.` for the hostname, thus different DNS resolution?

I'll raise a separate issue for it as requested, along with others encountered here :+1:

**Comment by mre** [comment]
> I'll raise a separate issue for it as requested, along with others encountered here 👍

Cool, thanks for that!

**Comment by mre** [comment]
Yeah it's definitely trying to make a network request on relative paths. However it should still not take so long to return an error.

**Comment by polarathene** [comment]
> We should create individual issues for them such that contributors could work on them independently.

These should all have their own issues now :+1: 

- https://github.com/lycheeverse/lychee/issues/665
- https://github.com/lycheeverse/lychee/issues/666
- https://github.com/lycheeverse/lychee/issues/667
- https://github.com/lycheeverse/lychee/issues/668
