### ISSUE TITLE
Inputs prefixed with `./` take 30 seconds to timeout when the file does not exist

### ISSUE THREAD

**Issue by polarathene** [lycheeverse/lychee#666]
When prefixing a relative path with `./` as a hint that this is a relative path, not a DNS label/hostname to lookup (_see Network error in reference below_), `lychee` shows progress for attempting link extraction for the non-existent local (or remote) input, until it times out at 30 seconds:

```console
$ lychee './relative-path/to/file.md'
⠒ 0/0 [00:00:29] █████████████████████████ Extracting links

# At 30 seconds, lychee times out with output:
Error: Network error

Caused by:
    0: error sending request for url (http://./relative-path/to/file.md): error trying to connect: dns error: request timed out
    1: error trying to connect: dns error: request timed out
    2: dns error: request timed out
    3: request timed out
```

- Without the `./` prefix, the resolution that the input does not exist is instant.
- If the file does exist, the response is instant with the `./` prefix. Only non-existent files are affected.
- `--skip-missing` makes no difference, other than ignoring the network error shown above and implying no problems:

```console
$ lychee --skip-missing './relative-path/to/file.md'
⠒ 0/0 [00:00:29] █████████████████████████ Extracting links

# At 30 seconds, lychee times out with output:
🔍 0 Total ✅ 0 OK 🚫 0 Errors
```

---

**For reference (below works as expected):**

```
--skip-missing           Skip missing input files (default is to error if they don't exist)
```

Providing a relative local filepath, when the file does not exist results in a network error (_an implicit fallback to a `http://` request?_):

```console
$ lychee 'relative-path/to/file.md'
Error: Network error

Caused by:
    0: error sending request for url (http://relative-path/to/file.md): error trying to connect: dns error: no record found for name: relative-path. type: AAAA class: IN
    1: error trying to connect: dns error: no record found for name: relative-path. type: AAAA class: IN
    2: dns error: no record found for name: relative-path. type: AAAA class: IN
    3: no record found for name: relative-path. type: AAAA class: IN
```

`--skip-missing` hides the network failure completely (_related, it might be useful to [report skipped/empty inputs](https://github.com/lycheeverse/lychee/issues/665)_)

```console
$ lychee --skip-missing 'relative-path/to/file.md'

🔍 0 Total ✅ 0 OK 🚫 0 Errors
```

**Comment by mre** [comment]
I think the solution here ist to avoid treating relative inputs as URLs.
So we'd check if `./relative-path/to/file.md` exists on disk and if not fail immediately.
We can do so by adding a check on the input to see if it is a relative path and not convert that to a full URL.

The check needs to be added here:

https://github.com/lycheeverse/lychee/blob/34a0502baf22d0b12f3dfb801d2dc011253155bc/lychee-lib/src/types/input.rs#L150-L159

Should be pretty straightforward to do if someone wants to send a PR.

**Comment by walterbm** [comment]
@mre is anyone currently working on this task or could I help with this fix?

**Comment by mre** [comment]
Sure, go for it. Thanks!
