### ISSUE TITLE
Configuration Issues Remapping Local Relatives Paths to Routable HTTP/HTTPS Host

### ISSUE THREAD

**Issue by aj-stein-nist** [lycheeverse/lychee#683]
I am late to the party re #620 and #631 feedback, but re usnistgov/OSCAL#1329 feedback, I would like to understand how to properly use the `lychee` configuration file and `remap = []` directives to check links in a repo's Markdown files when those links are relative and they should be remapped to an external, routable HTTP/HTTPS host (in this case GitHub).

Configuration file (and current GH Action configuration): https://github.com/aj-stein-nist/OSCAL/blob/34615b9a7e2994ea014213be25836756f1564b5d/build/config/lychee_config.toml

Local error output from debugging with the configuration above:

```sh
ajs16@MYCOMPUTERNAME MINGW64 ~/code/OSCAL (1223-modularize-all-github-actions-setups-backup-lychee-config-remap-experiments)
$ lychee --config ./build/config/lychee_config.toml './**/*.md' --exclude .github
? [EXCLUDED] file:///C:/Users/ajs16/code/OSCAL/.github/workflows | Excluded
? [EXCLUDED] file:///C:/Users/ajs16/code/OSCAL/.github/CODEOWNERS | Excluded
? [EXCLUDED] file:///C:/Users/ajs16/code/OSCAL/.github/ISSUE_TEMPLATE | Excluded
? [EXCLUDED] file:///C:/Users/ajs16/code/OSCAL/.github/issue_template.md | Excluded
? [EXCLUDED] file:///C:/Users/ajs16/code/OSCAL/.github/ISSUE_TEMPLATE/question.md | Excluded
? [EXCLUDED] file:///C:/Users/ajs16/code/OSCAL/.github/ISSUE_TEMPLATE/feature_request.md | Excluded
? [EXCLUDED] file:///C:/Users/ajs16/code/OSCAL/.github/ISSUE_TEMPLATE/bug_report.md | Excluded
? [EXCLUDED] https://github.com/usnistgov/OSCAL/discussions/categories/q-a | Excluded
? [EXCLUDED] https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork | Excluded
? [EXCLUDED] https://github.com/usnistgov/OSCAL/blob/main/CONTRIBUTING.md | Excluded
? [EXCLUDED] https://github.com/usnistgov/OSCAL/pulls | Excluded
Error: Invalid path to URL conversion: projects
```

**Comment by mre** [comment]
This does indeed look correct to me, however the error is very spurious:
```
Error: Invalid path to URL conversion: projects
```

I would assume there is no more output after that?
We've seen an error like this before on a Windows machine: https://github.com/lycheeverse/lychee/issues/589.

**Comment by mre** [comment]
The code for that causes the error is located here:
https://github.com/lycheeverse/lychee/blob/c4e004bdf8ee19c4e5945628255851d5498dd400/lychee-lib/src/helpers/request.rs#L87-L106

**Comment by mre** [comment]
So in this case `Url::from_file_path(&path)` fails. 
One step into the direction might be to print the underlying error instead of swallowing it (`_e` is never used in the code above). I can extend the error so that it becomes visible unless someone else wants to give it a shot.

**Comment by aj-stein-nist** [comment]
> This does indeed look correct to me, however the error is very spurious:
> 
> ```
> Error: Invalid path to URL conversion: projects
> ```

I am guessing this might be because that it is the relative path rewrite in the remap directive but it only seems to be searching the current directory, so cannot even find this? The output, remap or not, does not seem to recursively traverse all subdirectories with Markdown files suggest (I have tried `**/*.md` and `./**/*.md` and it seems to work for HTML files in a different job (`./published/**/*.html`, locally and GH Actions, I can double check that though). This is why in testing locally I kept trying with `--exclude .github` (which it does seem to find) but that is all it finds, even in the top-level `.` in a local clone of github.com/usnistgov/OSCAL. Is there something I am missing here?

 My theory could be way off though.
 
> I would assume there is no more output after that? We've seen an error like this before on a Windows machine: #589.

There is no more output after that.

I will double check on WSL and use more Linux eand not use (Windows) Git Bash, I can also retry with GHA and remove Windows out of the equation entirely, but might take me until later today. :-)

**Comment by polarathene** [comment]
If relative paths are involved, it may be [fixed by this PR](https://github.com/lycheeverse/lychee/pull/691).

Using Docker is probably a good idea for making a reproduction if it's not windows specific.

**Comment by mre** [comment]
> The output, remap or not, does not seem to recursively traverse all subdirectories with Markdown files suggest (I have tried **/*.md and ./**/*.md and it seems to work for HTML files in a different job (./published/**/*.html, locally and GH Actions, I can double check that though)

`'./**/*.md'` should be the correct format. If that doesn't work I'm confused as well, even though I have no idea if there's some special handling for this string with Git Bash on Windows.

I will print the underlying error to be able to debug this. @aj-stein-nist, would you be comfortable with testing the latest `master` once it gets merged?

**Comment by mre** [comment]
Any update on this one? https://github.com/lycheeverse/lychee/pull/691 is merged now and there's a new lychee version and a new version of the lychee-action, so maybe it's resolved?

**Comment by aj-stein-nist** [comment]
> Any update on this one? #691 is merged now and there's a new lychee version and a new version of the lychee-action, so maybe it's resolved?

I will try to give it a shot later tonight and follow up and give feedback (hopefully, I will close). :-)

**Comment by aj-stein-nist** [comment]
I am sorry I had not addressed this sooner as I had promised. I finally discovered as part of a more complex situation in the aforementioned issue this works well, and helped me uncover some CI/CD assumptions I didn't even know I was making.

I will close this for now and reopen if relevant or create a new issue accordingly.

**Comment by mre** [comment]
All good. Thanks for the feedback!
