### ISSUE TITLE
Add `--dump-input` flag to print all files, which would be searched for links

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#684]
This is mostly helpful for debugging purposes. For example if a regular expression for file matching doesn't work as expected.
Example: `lychee --dump-input './**/*.md'` would print all file names that the glob expression matches and exit.

**Comment by mre** [comment]
Probably it should be `--dump-inputs`.

**Comment by lebensterben** [comment]
what if we utilize "log" crate and just add a CLI option --log-file to set the sink to a file?

**Comment by lebensterben** [comment]
if we want we can add our custom log level to only output certain information, e.g. only glob pattern.

**Comment by mre** [comment]
The idea was to have a command that would allow users to quickly verify that all expected inputs are covered. It can help with troubleshooting. In light of that, I'd lean towards a simple flag which wouldn't require any grepping for the inputs. 😉

**Comment by lebensterben** [comment]
we can name it as --debug-input

**Comment by mre** [comment]
Sorta prefer `--dump-inputs` because we also have `--dump` which serves a similar purpose and it would show up below each other in the help output.
