### ISSUE TITLE
Support for more formats (XML, JSON)

### ISSUE THREAD

**Issue by tooomm** [lycheeverse/lychee#696]
I would like to easily check URL's saved in a XML file.

XML and JSON are both default file formats to store data in a specific form. Often URL's are among them.
Lychee probably doesn't need to understand the format to extract all URL's.

**Comment by tooomm** [comment]
Oh, I did never throw such files at lychee. I expected them to just fail on the extension already. 🙈 

>Any specific XML files you have in mind?

For example this database file contains many links that I would like to monitor:
https://raw.githubusercontent.com/Cockatrice/Magic-Token/master/tokens.xml

The current workaround is to parse the XML with XMLStarlet and extract the URL's to a text file, then feed that file to lychee.
Only that the installation of XMLStarlet alone takes longer than all lychee run and it adds two extra steps to the CI...

I did not try the pandoc idea.

**Comment by mre** [comment]
Have you tried feeding that directly to lychee? From a cursory look it might just work, although it could also be broken in subtle ways. Just curious.

**Comment by tooomm** [comment]
I just did, and it seems to work in this case indeed! :)

Probably worth noting somewhere that lychee tries to parse any file and it generally seems to work well if there are no format or encoding specifics? Could be helpful for some.

**Comment by mre** [comment]
Sounds good. I've added a note in https://github.com/lycheeverse/lychee/commit/aa931b8c00edf09c562cc1b2d69cdc823c9c74f3. Guess we can close this. 📕

**Comment by tooomm** [comment]
For clarification:
I did also try a bit bigger JSON file. It did work, but took a while to parse.

**Comment by mre** [comment]
JSON is tricky to optimize for URL extraction, because they could appear pretty much anywhere in the document.
We could look into the document if it's public and see if we can improve parsing speed, though. It should not be slower than any plaintext document.
This is tangentially related: https://github.com/lycheeverse/lychee/issues/513

**Comment by tooomm** [comment]
For the record, here is a test json: https://mtgjson.com/api/v5/SNC.json
Parsing time looks ok when only using `--dump`.

**Comment by lebensterben** [comment]
this json files contains a lot noj ASCII characters which is just skipped by the underlying crate we use...... because it doesn't support non-ascii URL... whcih can partially explain why parsing doesn't seem slow.

**Comment by tooomm** [comment]
Interesting!

There is also https://mtgjson.com/api/v5/SetList.json, which should be ASCII only.
It's also about the same size as the above XML, but has more links.
