### ISSUE TITLE
No output for `--dump` / Allow to `--dump` extracted links to file

### ISSUE THREAD

**Issue by tooomm** [lycheeverse/lychee#698]
It looks like the dump flag will not create the expected output.

`cat /tmp/lychee/out.md` gives `No output. Check pipeline run to see if lychee panicked.`
The dumped output should have the found links, no? 🤔

**Comment by mre** [comment]
`--dump` only prints to stdout right now. It does not respect the output file. We should fix probably add support for that. 👍
