### ISSUE TITLE
List excluded URLS?

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee#704]
Is it possible to list excluded URLs?

I am adding this action to a repo in https://github.com/GitCredentialManager/git-credential-manager/pull/700, where it reports as follows:

```console
| Status        | Count |
|---------------|-------|
| 🔍 Total      | 236   |
| ✅ Successful | 158   |
| ⏳ Timeouts   | 0     |
| 🔀 Redirected | 0     |
| 👻 Excluded   | 78    |
| ❓ Unknown    | 0     |
| 🚫 Errors     | 0     |
```

Though there are some items in a `.lycheeignore` file, I would not have expected as many as 78 excludeds. Therefore I would like to understand in more detail exactly what is excluded so as to troubleshoot my configuration of Lychee.
Is it possible to configure the action to list the excludeds in the output in some way?

**Comment by mre** [comment]
At least in verbose mode we print the excluded URLs now when we check them.
```
lychee -vv .
```

Note: this will be part of the **next release**.
With that I consider this done. 🥳  Thanks for the report.
