### ISSUE TITLE
URLs with the domain name "example" are excluded, even if I set the `--include` parameter

### ISSUE THREAD

**Issue by Jiahui-Gu** [lycheeverse/lychee#712]
In the project's [README.md](https://github.com/lycheeverse/lychee/blob/master/README.md), the `--include` parameter is interpreted as: `--include <include>...                 URLs to check (supports regex). Has preference over all excludes`.

So theoretically when I use `--include [\s\S]*`, lychee should not skip any links. But lychee still skips the URLs with the domain name "example"

My CMD is:
`lychee /path/to/links.html --include [\s\S]*`

The result is:
`🔍 1 Total ✅ 0 OK 🚫 0 Errors 💤 1 Excluded`

`links.html` content is:
`<a href="http://www.example.com/default.asp"></a>`

Other than that if a URL is `http://` and I use `--include [\s\S]*`, lychee skips the URL too. I think this conflicts with the description in  [README.md](https://github.com/lycheeverse/lychee/blob/master/README.md)

**Comment by lebensterben** [comment]
http://www.example.com is hardcoded to be excluded.

**Comment by lebensterben** [comment]
See https://github.com/lycheeverse/lychee/blob/fb367ef43ae6324c9710f3eb803742a58c7db0f4/lychee-lib/src/filter/mod.rs#L14

**Comment by Jiahui-Gu** [comment]
Thank you for your reply! I love lychee. 

In order to maintain consistency with the [README.md](https://github.com/lycheeverse/lychee/blob/master/README.md), do we have any plans to disable this hardcode when we set `--include [\s\S]*`?

**Comment by lebensterben** [comment]
you need to build lychee with check_example_domains feature.

**Comment by mre** [comment]
> Do we have any plan to disable this hardcode when we set --include [\s\S]*? I think most users would also like to be able to set it up to check all links.

It's a bit of a niche use-case. I'd be fine with accepting a PR for it, but I won't be working on that myself in the foreseeable  future. 😉 @Jiahui-Gu, any interested in tackling this?

**Comment by lebensterben** [comment]
I don't think we should provide any runtime configuration option for this. It will violates RFC 2606.

**Comment by mre** [comment]
@Jiahui-Gu given that there is a workaround I'll go ahead and close the issue now. 😉
