### ISSUE TITLE
Why lychee's results are disordered in single thread?

### ISSUE THREAD

**Issue by Jiahui-Gu** [lycheeverse/lychee#721]
My CMD is:
`lychee ./links.html --threads 1 --format detailed `

The result is:
```
✗ [404] https://youtube.com/test.html | Network error: Not Found
✗ [404] https://www.microsoft.com/155 | Network error: Not Found
✗ [404] https://www.microsoft.com/15 | Network error: Not Found
✗ [404] https://www.microsoft.com/166 | Network error: Not Found
✗ [404] https://www.microsoft.com/1555 | Network error: Not Found
✗ [404] https://www.microsoft.com/144 | Network error: Not Found
✗ [404] https://www.microsoft.com/16 | Network error: Not Found
✗ [404] https://youtube.com/Videos/AllVideos/Permalink/3cb3788c-5c47-4b9e-987c-0dec41940581b/ | Network error: Not Found
✗ [404] https://www.microsoft.com/14 | Network error: Not Found
✗ [404] https://www.microsoft.com/1444 | Network error: Not Found
```

`links.html` content is:
```
<a href="https://www.microsoft.com/14"></a>
<a href="https://www.microsoft.com/144"></a>
<a href="https://www.microsoft.com/1444"></a>
<a href="https://www.microsoft.com/15"></a>
<a href="https://www.microsoft.com/155"></a>
<a href="https://www.microsoft.com/1555"></a>
<a href="https://www.microsoft.com/16"></a>
<a href="https://www.microsoft.com/166"></a>
<a href="https://youtube.com/test.html"></a>
<a href="https://youtube.com/Videos/AllVideos/Permalink/3cb3788c-5c47-4b9e-987c-0dec41940581b/"></a>
```

After comparing the order of the links changed. The `links.html` with two domains for `youtube.com` are at the end and the results are in the middle.

**Comment by lebensterben** [comment]
This is the expected behaviour.
Even if you only have 1 thread, it's still async.

**Comment by mre** [comment]
@lebensterben is correct. To elaborate, URLs get sent to the client concurrently and the results get printed in ascending order of response time.

**Comment by Jiahui-Gu** [comment]
I have an additional question: Is the order in which the URLs are sent to the client the order in which they appear in the html?

**Comment by mre** [comment]
Nope. It's the order in which the responses are coming back from the client that defines the order in the html. Remember that the entire process is async: the client is completely decoupled from the output writer. Hope that helps. 😉
