### ISSUE TITLE
Only show external links

### ISSUE THREAD

**Issue by orthl** [lycheeverse/lychee#770]
Hello,
is it possible to only see external links to another URL? For example, I crawl the URL "https://test.com" so I don't want to see the first and the second entry but the last both.

---Output---
1. https://test.com
2. https://test.com/test/
3. https://new.com
4. https://new.com/new

Thanks and best wishes
Lucas

**Comment by mre** [comment]
lychee supports multiple inputs, so "external" would be ambiguous in the following case:

```
lychee https://example.com https://example.org
```

For the first input, everything except https://example.com would be external. For the second, everything except https://example.org would be external.

If you only have a single input, you can exclude `test.com` from being checked:

```
lychee --exclude https://test.com --verbose https://test.com
```

Does that work for you?

**Comment by orthl** [comment]
Thank you very much, it works very well. 

- Is there a way to write the result in an external document?
- Is there a way to show the successful hits (external links) into the result?

![grafik](https://user-images.githubusercontent.com/70632173/191473660-8ac691e3-bb2b-409f-ae90-cfc6ab812dc9.png)

Thanks!
Lucas

**Comment by mre** [comment]
You can use the `output` option to write the result to an external file if you mean that:

```
-o, --output <output>                      Output file of status report
```


The number of excluded links is in the final output.
So if you take `total - excludes` that's the number of successful hits (external links).

If you exclude multiple patterns then it gets a little more complicated.
In this case you can try a workaround:

```
# First get the total number of links
lychee --dump https://test.com | wc -l

# Then get the number of non-excluded links
lychee --exclude https://test.com --dump https://test.com | wc -l
```

The difference between those two calls is the number of successful (external) links.
I think you don't exclude multiple patterns, though, so the first solution (`total - excluded`) should be enough?

**Comment by orthl** [comment]
Perfect. It works. Thank you very much.
