### ISSUE TITLE
Document usage of `--remap`

### ISSUE THREAD

**Issue by andygrunwald** [lycheeverse/lychee#800]
The `--remap` parameter is described like

```
$ lychee --help
[...]
--remap <remap>...                     Remap URI matching pattern to different URI
[...]
```

Neither in the README or in [lychee.cli.rs](https://lychee.cli.rs/), the usage, use-case or format is described/documented.

I found https://github.com/lycheeverse/lychee/pull/620, which documents the usecase and usage pretty well. An configuration file example can be found here: https://github.com/lycheeverse/lychee/blob/a557cba0b4fcf63c496b9dc202787e899d290e08/lychee.example.toml

However, I think having this flag documented in the README or (even better) in the documentation site incl. a usecase would be great.

**Comment by mre** [comment]
Yeah, that part could certainly be a bit clearer.
I've added https://lychee.cli.rs/#/recipes/migration and I've linked #620 and the config you mentioned as well. Hope that works. Thanks for creating the detailed issue. 👍
