### ISSUE TITLE
Lychee action times out for valid link

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee#808]
[This GitHub repository](https://github.com/exercism/problem-specifications) has [this markdown file](https://github.com/exercism/problem-specifications/blob/main/exercises/house/description.md) which links to : https://papyr.com/hypertextbooks/grammar/ph_noun.htm

Web browsers are OK with this link:

![image](https://user-images.githubusercontent.com/281700/200060254-402247fc-633e-4847-8185-d7ef79623271.png)

Curl also seems happy with it (when a user agent is used):

```console
# Without UA
❯ curl -I https://papyr.com/hypertextbooks/grammar/ph_noun.htm
HTTP/1.1 403 Forbidden
Date: Fri, 04 Nov 2022 19:10:28 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Content-Type: text/html; charset=iso-8859-1

curl: (6) Could not resolve host: extbooks

# With UA
❯ curl -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" -I https://papyr.com/hypertextbooks/grammar/ph_noun.htm
HTTP/1.1 200 OK
Date: Fri, 04 Nov 2022 19:11:28 GMT
Server: Apache
X-Frame-Options: SAMEORIGIN
Last-Modified: Sun, 31 Jul 2022 10:28:01 GMT
Accept-Ranges: bytes
Content-Length: 17655
Cache-Control: max-age=604800, no-cache, public
Expires: Sun, 06 Nov 2022 19:11:28 GMT
Vary: Accept-Encoding,User-Agent
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: origin, x-requested-with, content-type
Access-Control-Allow-Methods: PUT, GET, POST, DELETE, OPTIONS
Content-Type: text/html
```

However the Lychee action, with a user agent argument ([configured here](https://github.com/exercism/problem-specifications/pull/2145/files)), reports a timeout in [this workflow](https://github.com/exercism/problem-specifications/actions/runs/3396399378/jobs/5647424395).

Any suggestions for what could be wrong or what else I could try to figure it out?

**Comment by mre** [comment]
Hm... works on my computer.

```bash
echo 'https://papyr.com/hypertextbooks/grammar/ph_noun.htm' | lychee --verbose -
✔ [200] https://papyr.com/hypertextbooks/grammar/ph_noun.htm

🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

Can you test this command on your machine?

**Comment by wolf99** [comment]
OK yeah this works for me on local machine also.

```console
~❯ ./lychee --require-https --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" ./git/problem-specifications/exercises/house/description.md
🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

Looks like it may be specific to the lychee-action then as I've tried several runs of the job on the PR linked above.
Worth moving this issue to the  action repo?
I'm not sure why this would work differently for the action though... some container networking or smthg maybe?

**Comment by mre** [comment]
I doubt that it's a problem with the lychee-action but rather an issue with the specific network on which the Github action is executed. If it runs on a server with a well-known Azure IP address and other payloads use the same host for e.g. bot traffic then the IP could be blocked by the bot detection on the site.

There are some notes on the IP addresses Github Action Runners use [here](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#ip-addresses):

> Windows and Ubuntu runners are hosted in Azure and subsequently have the same IP address ranges as the Azure datacenters. macOS runners are hosted in GitHub's own macOS cloud.

and 

> The list of GitHub Actions IP addresses returned by the API is updated once a week. 

So one could try from a host within an Azure datacenter to find out if it's the same issue as on Github.

**Comment by mre** [comment]
I can reproduce the issue in a Github Codespace with lychee alone (not the action).
Running into a timeout:

```
> echo 'https://papyr.com/hypertextbooks/grammar/ph_noun.htm' | lychee --verbose --no-progress --require-https --user-agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.75 Safari/537.36" -
⧖ [TIMEOUT] https://papyr.com/hypertextbooks/grammar/ph_noun.htm | Timeout

Issues found in 1 input. Find details below.

[stdin]:
⧖ [TIMEOUT] https://papyr.com/hypertextbooks/grammar/ph_noun.htm | Timeout

🔍 1 Total ✅ 0 OK 🚫 0 Errors
```

You could use a self-hosted runner for Github actions but it's probably overkill.
Other than that there ain't much we can do.

**Comment by mre** [comment]
@wolf99, sorry about that. 😕 If you have any more questions on this, feel free to add a comment below. Other than that I'll go ahead and close the issue as it's unrelated to lychee.
