### ISSUE TITLE
Add `script` to verbatim tags?

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#821]
In HTML and Markdown documents, `<script>` tags usually contain non-user-facing links that are only relevant to the JavaScript inside these tags.
As such, it might make sense to exclude script tags from automatic checking. We could add the tag to our list of verbatim tags here:

https://github.com/lycheeverse/lychee/blob/9927cc57022b94b6304517be2150a1288ac1d02b/lychee-lib/src/extract/mod.rs#L11-L19

This way a user could overwrite the behavior and check inside script tags with `--include-verbatim`. 
Thoughts?

**Comment by mre** [comment]
Related: https://github.com/untitaker/hyperlink/issues/148

**Comment by untitaker** [comment]
I don't have a strong opinion on which approach is better, I found the state machine change thing in lol-html but idk if it leads to significantly different results. Might be a usecase for differential fuzzing.

**Comment by mre** [comment]
Thinking about this a bit more I wonder if it warrants its own flag like `--include-scripts`.
