### ISSUE TITLE
.lycheeignore can not exclude files / directories

### ISSUE THREAD

**Issue by ruzickap** [lycheeverse/lychee#822]
I would like to exclude some files / directories form being scanned by lychee.

Example:

```
$ mkdir -pv /tmp/test/dir

$ cd /tmp/test/

$ cat > dir/README.md << EOF
https://google.com
EOF

$ cat > .lycheeignore << EOF
^./dir/
EOF

$ lychee --verbose .
✔ [200] https://google.com/

🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

I excluded the `dir` directory in `.lycheeignore` but it was scanned by lychee :-(

Is there a way how to use `.lycheeignore` with files/directories ?

Thank you...

**Comment by mre** [comment]
That's a common misconception that keeps popping up unfortunately:
the `.lycheeignore` lists *URLs* that should be excluded not *paths*. 

To exclude the path you can create a `.lychee.toml` file with the following content:

```toml
exclude_path = ["^./dir/"]
```

Example config file: https://github.com/mre/endler.dev/blob/50d8d5f90dbafa445c9455e420a40f8866f3e1c7/lychee.toml#L28

Hope that helps.

**Comment by mre** [comment]
Very welcome. Thanks for the pull request for adding more details about the behavior.

**Comment by mre** [comment]
Closing this and moving the discussion over to your PR.

**Comment by mre** [comment]
FYI: Added a section to the lychee docs as well. https://lychee.cli.rs/#/recipes/excluding-paths
Also fixed a little typo that slipped through code review. 😄 
https://github.com/lycheeverse/lychee/commit/fbf0e9faeafbe3bcaa6b246249a2cc5e59596402

**Comment by ruzickap** [comment]
Thank you... and sorry for the typo...
