### ISSUE TITLE
Latest version has not been published to docker

### ISSUE THREAD

**Issue by jooola** [lycheeverse/lychee#835]
It seem like a few versions are missing from the dockerhub repository.

https://hub.docker.com/r/lycheeverse/lychee/tags?page=1&name=0.10

**Comment by mre** [comment]
Guess that's caused by a race-condition with the release pipeline right now.
I think I can run the pipeline again for an existing tag and _should_ work.

**Comment by mre** [comment]
Triggered https://github.com/lycheeverse/lychee/actions/runs/3501392131. Let's see how it goes.
Thanks for the heads up.

**Comment by jooola** [comment]
Latest version is now on dockerhub, seems fixed to me ! Thanks !

Unsure if you want to do the same with v0.10.2, the version seem missing as well.

**Comment by mre** [comment]
Yeah I might as well. Don't think there will be any negative side-effects.

**Comment by mre** [comment]
Seems like `v0.10.2` is the only one that's missing, so I triggered https://github.com/lycheeverse/lychee/actions/runs/3504163799 for that. I might have to set back `latest` to `v0.10.3` after that.

**Comment by mre** [comment]
Done. Thanks for the report.
