### ISSUE TITLE
Don't check preconnect links if not in verbatim mode

### ISSUE THREAD

**Issue by mre** [lycheeverse/lychee#897]
Preconnect links are used to establish a server connection without loading a specific resource yet.
Not always do these links point to a URL that should return a 200 and they are not user-facing, i.e. they don't show up in the final rendered version of a page.
Therefore I think we should only check them if `--include-verbatim` is enabled.

Examples from https://www.algolia.com/search/:

```html
<link rel="preconnect" href="https://1QDAWL72TQ-dsn.algolia.net" />
<link rel="preconnect" href="https://cdn.cookielaw.org" />
<link rel="preconnect" href="https://res.cloudinary.com" />
```

Reference: https://github.com/lycheeverse/lychee/issues/895.

**Comment by lebensterben** [comment]
We might as well deal with other pre* links all together.

**Comment by lebensterben** [comment]
preconnect:

> Specifies that the user agent should preemptively connect to the target resource's origin.

where `origin` is

> A tuple consists of:
>
> A scheme (an ASCII string).
> A host (a host).
> A port (null or a 16-bit unsigned integer).
> A domain (null or a domain). Null unless stated otherwise.

Following the same logic, we should also validate the `origin` then...

**Comment by mre** [comment]
The `preconnect` directive is primarily about establishing a network connection to the specified domain in advance of any actual request. The fact that a request to e.g. the root of https://1QDAWL72TQ-dsn.algolia.net returns a 404 doesn't necessarily mean that the `preconnect` directive is misconfigured or ineffective.

When a browser sees a `preconnect` directive, it's not immediately making a GET request to that URL. Instead, it's only performing the lower-level networking setup (i.e. DNS resolution, establishing a TCP connection, and performing a TLS handshake if the connection is secure). This is all done in _anticipation_ of a request being made to that domain later.

If a later request is made to a specific path on that domain (for example, https://1QDAWL72TQ-dsn.algolia.net/some/resource/path), the fact that the root of the domain (https://1QDAWL72TQ-dsn.algolia.net/) returns a 404 is irrelevant. What matters is whether the specific resource requested returns a valid response.

Hence, I think we should exclude `preconnect` directives.

PR for that: https://github.com/lycheeverse/lychee/pull/1187
