### ISSUE TITLE
YouTube link not checked properly

### ISSUE THREAD

**Issue by buddhist-uni** [lycheeverse/lychee#906]
Lychee claims to be using the OEmbed API to check YouTube links, but `https://youtu.be/Rvu7N4wyFpk` for example is not:

![Screenshot_20230106_090957_Termux](https://user-images.githubusercontent.com/61610173/210915681-f32754d5-173a-4e55-9e08-019ab9c08cb3.jpg)

Version 0.10.3

**Comment by buddhist-uni** [comment]
See https://github.com/lycheeverse/lychee/issues/28 for the context on using the oembed API to check YouTube links

**Comment by mre** [comment]
We no longer use oEmbed links for Youtube as they don't return a correct status code.
Instead we use the thumbnail URL, which is more reliable.
(Note that we don't download the image but just check the headers for the status code.)
See the discussion starting at https://github.com/lycheeverse/lychee/issues/214#issuecomment-817517033 and the change at https://github.com/lycheeverse/lychee/pull/232.

That said, the video URL you posted (https://youtu.be/Rvu7N4wyFpk) points to a video that is no longer available, so this is certainly a bug. I've created a PR to fix this with #908.
Thanks for the report @buddhist-uni.

**Comment by mre** [comment]
Should be fixed in `master` now if you want to try @buddhist-uni. Otherwise it will go live with the next release.

**Comment by buddhist-uni** [comment]
Ah! Non-embedable videos! Nice trick with the Thumbnail URL. And thanks for the fix 🙂

**Comment by mre** [comment]
That was @pawroman's idea.
