### ISSUE TITLE
add back `doctest`

### ISSUE THREAD

**Issue by lebensterben** [lycheeverse/lychee#932]
Recently we replaced `cargo test` by `cargo nextest` and it's vastly faster.
Unfortunately, it doesn't support `doctest` yet.

We should add a separate step in CI to run `cargo test --doc`.

**Comment by mre** [comment]
Oh, I did not know that. Here's the tracking issue: https://github.com/nextest-rs/nextest/issues/16.
In the meantime let's add back a separate step for doctests, yeah.

**Comment by mre** [comment]
We're testing the docs again, thanks to a separate step. We can move to the proper solution once it's available upstream.
