### ISSUE TITLE
Extended summary

### ISSUE THREAD

**Issue by c-martinez** [lycheeverse/lychee#94]
Hi!

I am trying to upgrade from [link-checker](https://github.com/peter-evans/link-checker) to [lychee-action](https://github.com/lycheeverse/lychee-action) however I am running into a small issue. link-checker output is plain text and very easy to process (grep) to list only broken links. lychee's output is much prettier, and I actually really like the summary it produces. However it would be great if lychee provided a way to list only links which produced errors.

Is this at all possible?

**Comment by pawroman** [comment]
Hi,

Thanks for the feedback. In default mode (without any flags), lychee (on the CLI) only prints out links that failed checks. See this -- lychee checking its own README:

```
lychee
🚫 https://example.com/README.md [404 Not Found]
```

In `--verbose` mode it produces a lot more output, including passed links and a summary. This is the default mode for the action, see: https://github.com/lycheeverse/lychee-action/blob/master/action.yml#L6

You can tweak the `args` not to include the `--verbose` flag, see: https://github.com/lycheeverse/lychee-action#usage

I hope that's helpful!

**Comment by c-martinez** [comment]
Great, I think that is what I needed to know. Thanks!
