### ISSUE TITLE
Failed: Cannot find file error

### ISSUE THREAD

**Issue by Jonas1312** [lycheeverse/lychee#941]
Thanks for this really cool tool!

I have a workflow running lychee: https://github.com/Jonas1312/knowledge-base/blob/master-pub/.github/workflows/check_links.yml

But I get this error:
```shell
## Errors per input

### Errors in base/science-tech-maths/signal-processing/signal-processing.md

* [ERR] [file:///home/runner/work/knowledge-base/knowledge-base/base/science-tech-maths/signal-processing/n](file:///home/runner/work/knowledge-base/knowledge-base/base/science-tech-maths/signal-processing/n) | Failed: Cannot find file
```

But there is not such link in the markdown file: https://github.com/Jonas1312/knowledge-base/blob/master-pub/base/science-tech-maths/signal-processing/signal-processing.md

Not sure why this happens :/

Thanks!

**Comment by lebensterben** [comment]
looks like the error comes from line 14

> $$[f * g](n) = \sum_{m=-\infty}^\infty f[m] g[n - m]$$

this is likely a issue cause by pulldown_cmark

**Comment by Jonas1312** [comment]
Math support should be released soon, maybe: https://github.com/raphlinus/pulldown-cmark/pull/622
