### ISSUE TITLE
specific status code only for one link?

### ISSUE THREAD

**Issue by sylvainOL** [lycheeverse/lychee#947]
Hello, I'd like to check several urls but only one of them gives back `401` (and it's "normal").

Is it possible to allow `401` only for one url?

**Comment by mre** [comment]
No, but it's an interesting idea.
May I ask why you want to check the URL which returns `401`?
If the outcome of this check is irrelevant you can just use `--exclude yoururl` to skip it.

**Comment by mre** [comment]
Does `--exclude` work for you? If so, I guess we can close this issue.

**Comment by sylvainOL** [comment]
well `--exclude` would exclude this specific url but I'd like to test and make it OK if response is `401`. So `--exclude` wouldn't really work for my case

**Comment by mre** [comment]
Alright, I see.

I'm a bit reluctant to add a config option for this as it's a bit of an edge case and would make the list of options even longer.
Have you considered running lychee twice instead? Once for all the normal links and once for this specific URL?

```
lychee --exclude yourspecialdomain.com ...
lychee --accept 401 --exclude .* --include yourspecialdomain.com  ...
```

That's a common workaround for such cases. E.g. see https://github.com/lycheeverse/lychee/issues/960 for another example.

**Comment by sylvainOL** [comment]
Ok let's do that although it's not the simplest but it's a workaround.
