### ISSUE TITLE
Add option to excuse domain from `--require-https`

### ISSUE THREAD

**Issue by buddhist-uni** [lycheeverse/lychee#960]
There's a site I link off to for which the html pages load fine over https, but for which the page assets don't. In this circumstance, I do want the page to be linked via http even though the request could go through via https.

I'd therefore love a command line flag something like `--http-ok-for-domain example.com` to exempt these links from `--require-https`

Thanks! 🙏

**Comment by lebensterben** [comment]
that's a server configuration issue i believe you should address it directly, not ignore it.

**Comment by buddhist-uni** [comment]
@lebensterben - Linking to someone else's domain. I'd love to fix their website for them, but unfortunately I'm not that good of a hacker yet! 😂

Also, `--require-https` appears to be recommending I use https for [e.g. this link](https://www.palitext.com/JPTS_scans/JPTS_2007_XXIX.pdf) even though it gives an invalid cert error...

**Comment by lebensterben** [comment]
both http://www.palitext.com/JPTS_scans/JPTS_2007_XXIX.pdf and https://www.palitext.com/JPTS_scans/JPTS_2007_XXIX.pdf are 404 so i don't understand why would it tell you to use https.

**Comment by lebensterben** [comment]
we currently group results by their status, success, failure, timeout, ignored, etc.

I now think we should instead group them by levels such as

- Info: Success, ignored
- Warn: Not using HTTPS, not wrapping URL in angle bracket in Markdown file (this is not implemented)
- Error: Failure, timeout

**Comment by buddhist-uni** [comment]
Oh, I'm sorry. The real link was the home page: http://www.palitext.com/ which is a redirect.

**Comment by lebensterben** [comment]
> In my browser at least

something wrong with your browser

**Comment by buddhist-uni** [comment]
Oh? The https version works fine in your browser? No CERT_NAME error?

**Comment by lebensterben** [comment]
I object this proposal because it will make CLI options very complicated.

Instead I proposed https://github.com/lycheeverse/lychee/issues/960#issuecomment-1442770795 so that this becomes a warning instead of an error for CI.

**Comment by mre** [comment]
https://www.palitext.com/ produces a cert error for me as well.
Don't want to add a CLI option for it, because it's quite a special case.
You could run lychee twice:

```
lychee --require-https --exclude palitext.com ...
lychee --exclude .* --include palitext.com ...
```

It's a little tedious, but it has the effect you want I guess.

**Comment by buddhist-uni** [comment]
> produces a cert error for me as well

Ah good! As well it should. @lebensterben, you may want to check your security settings!

> You could run lychee twice:

Ah, good idea. `--include` is ...erm... exclusive? Meaning it will _only_ check what's `include`d (if an `include` is... erm... included)?

**Comment by lebensterben** [comment]
@buddhist-uni 

I don't think my security settings is wrong... I'm testing on ios

**Comment by mre** [comment]
> Should I open a new Issue for the Cert Error thing?

What is the output you're getting?

I tried this and it looks reasonable:

```
echo 'https://www.palitext.com/JPTS_scans/JPTS_2007_XXIX.pdf' | lychee --require-https -                                                                                                                                                       ✘
Issues found in 1 input. Find details below.

[stdin]:
✗ [ERR] https://www.palitext.com/JPTS_scans/JPTS_2007_XXIX.pdf | Failed: Network error: The certificate was not trusted.

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```

**Comment by buddhist-uni** [comment]
Even though the https certificate is invalid (wrong domain name), Lychee thinks it's fine:
```
echo 'https://www.palitext.com' | lychee --require-https -
⠚ 1/1 ETA 0s ████████████████████ ✔ [200] 
🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

Shouldn't that be an error?

**Comment by mre** [comment]
Strange, I'm getting the expected error:

```
echo 'https://www.palitext.com' | lychee --require-https -                                                                                                                                                                                     ✘
Issues found in 1 input. Find details below.

[stdin]:
✗ [ERR] https://www.palitext.com/ | Failed: Network error: The certificate was not trusted.

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```

...even without `--require-https`:

```
echo 'https://www.palitext.com' | lychee -                                                                                                                                                                                                     ✘
Issues found in 1 input. Find details below.

[stdin]:
✗ [ERR] https://www.palitext.com/ | Failed: Network error: The certificate was not trusted.

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```

**Comment by buddhist-uni** [comment]
Openned #966 for the SSL issue  😊

**Comment by mre** [comment]
> So... should I close this issue and open a new issue for that?

Yup, let's move the discussion over to #966. Thanks!
