### ISSUE TITLE
Config file verbosity

### ISSUE THREAD

**Issue by afonsojramos** [lycheeverse/lychee#963]
It seems that the [verbosity set in the config file](https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml#L4) no longer works, can you update the example?

The error outputs `expected struct Verbosity`.

**Comment by vpereira01** [comment]
I think the changes made to log verbosity #956 broken verbosity setting through configuration file.

In the past a test has been added to validate the configuration file [parsing](https://github.com/lycheeverse/lychee/blob/master/lychee-bin/tests/cli.rs#L625) but it does not seem to be executed in the pipeline which might have helped introducing this issue.

PS: I don't know known Rust so I can't really help much fixing the issue.

**Comment by mre** [comment]
Can you try again with the latest `master`? (You need to compile from source for that.)

The recent changes in #956 should actually have fixed the setting and the example file  should be up to date again. We support multiple verbosity levels now, so you need to set the verbosity like this:

```toml
verbose = "warn"
```

You can set it to `info` or `error` as well.

It's true that the tests don't get executed right now. I'm working on fixing that.

**Comment by vpereira01** [comment]
I was expecting to fail but vscode setup the devcontainers which made it easy :) Nice job and nice to discover this feature :+1: 

Yes, adjusting the verbose level to strings ("warn", etc.) it works fine.

Since are using the GitHub action I think we can just wait for the next release.

**Comment by mre** [comment]
Nice. Thanks for the feedback. I'll go ahead and close this. The release is scheduled to happen very soon, so stay tuned for that.
