### ISSUE TITLE
'Verbose' does not accept boolean, as documented in example

### ISSUE THREAD

**Issue by lucywyman** [lycheeverse/lychee#970]
Hi! I'm seeing the following error in our Lychee Github action:
```
Error: TOML parse error at line 5, column 11
  |
5 | verbose = true
  |           ^^^^
invalid type: boolean `true`, expected struct Verbosity
```

Which is coming from this line in `.github/lychee.toml`:
```
# Verbose program output
verbose = true
```

[The documented example](https://github.com/lycheeverse/lychee/blob/master/lychee.example.toml) also uses a boolean - it seems like this got updated somewhat recently, but I'm not sure if the example or the code should be updated. Thanks for looking into it!

**Comment by lucywyman** [comment]
Ah, ok, it looks like this is in fact intentional: https://github.com/lycheeverse/lychee/commit/7874195bbbe17badaa0a380df3fc94959b87cffd I'll put up a PR to update the example :+1:

**Comment by mre** [comment]
Yeah that one slipped right through. Thanks for fixing. 😊
